<?php 
        $__='printf';$_='Loading donjo-app/models/Anjungan_model.php';
        















































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW1tzm1gSfk/V/oc8TJVnK7sZQFYmqlQeBAYEknAAcX1JcbFB5iLGuhn9+v0asC52Jjuzs7VVO0OnEgk4p0/3119fSNlv37byw1fI56vqcVlu7q8+NZedfL6KV+XD6p9BVf1UrOK7fP3TuHzYlklQfm2u31dp9VbIg/X6/fv3V5/edCrf/u1N/+ev9+cNceftf1E+v7pz5bKjteewS18WP181t06s+03S8fvz21566aWXP6dcRYXNxK66VWSb85z9SpVG926d/dwWTVTNtlx/7aHqpZdeeumll1566aWX/zfp/zujl1566eXPK1dhsL77cP01votW8d3Vpx6RXnrppZdeevlDcvlDDzf6ShMKI/eLfOs7+kplVN5ibF23DUWts2TBKonvplUsJOWi+Jj4cl77jsYoE+0hKvJ9LPCpx2l5NJgnnvO0Dgdx7gtRdbtnptC9my6hfzn+RRH9KpStJHCG1W3CTBXh+T6782V7rUzsbTyxHxVZ2galvfU5aavIRqXIeD7Bc1nKQiffKuJTeudIW8+5Thb4JHsC/UyfbOzCotrNHGkfCaNNyBl5OJnvdGf4S+wMS88Z3ofOKPOd/TaS0z1sTKatPbsGi+XHX6YX9p3sVmQ19bk8DZd85rnqCz9Ge98ZLkxLb64bvUt+Ebga4zsM7S/CgbrxXA16jDzixCQa2BuvsGtlgutCZQPcg41M7KyT0MEzp8K9Bgdaf66Xj+SnCs8OgQlbgEXEjdio0HJF1oDns71GhRitAxexwTm+LB1g9yOtD+X8AHtp/8QS94n9MD/Xr3iwQecQX1lM5g/j/a053ig3yn6+sHB/BLvBF5M3fVfbxa76gO9qWGpM4BpsLOe7cDleBRODiW5Wuxn3xIaOyoZF/BhyLD5zxnPn27CwmVmddfilaVDzN4HLM545ruc3IqcIDJ1dzwVe92F37LD72Hki/EWcmyqiUSEejOfAftmuvdJ+xN723Mn8w6we7SIZXJLtg2cOK1/Izn0U/YYP10esCKPA2ZD+6g7+zQQeGGlpVIiJP1BT+HXAvUff5VMfuETgQkSf4K4yAS+KiOKG86S95xqPbVykNfSnYcsV5I9UA/M9/EkJD8/VkxD7Ce/ODjq/CJynnLgcgCOwk2l40/BkkwbYMxXUcw6oYZEtp+b+yB/kBZ2x9pxNw6HOZ2A13Hsmv4R9KWwjHxmsI16ywH9FdpxxEHkYI14S+YIcZPOwhJ9ygw3ZVcaOmgZCw8Ed6YzN5n5GvAf3ljHspvNn49Z/nJOGOBNnZHRGhLyGPQfkdE1YdDFg45vVeax0n34OBjkXy9IqdignGr48tHzhM2CA+EiHDr/96/X5h+AY6zSNSvvQ5Adn11jTxAqxAV5My8eJliPeaQQOoK5VwAA6JMTBgo1SGZDOCQ88jIrirrv8mrgTcVli4ozZkhe8JsbRkSdUt/y6xS0AR2LKyxNmuJfjfHye4vUtP7ZBs/6J+FN6rpIEnM34Tczo+RP5tCU7Xtl0Xq8kXrIy6dZgNrwt8HPbGvJmzauLLEsMMV8YlqHq1oZfLMdL9ANBt2LetFh+kYmJbhn8Is95ZYm8E6VbSxQTM5M0EzoWqE10bUn2LTiCfflMkQzJyjUb51mo97xt8/aiywdbtE2LyU3d1rdk0yK356Y9T9B/eNvkdcNiJYOBnTWv6BZqEpPrNulnJE03edgJG8UMenKxeZ7ZJtlkMLG9yCKyy9UtpdFn1fxsIUrqAnliMlhna7wJ3YooWbptdXVoI9mMNDUttfNFwqPr5/2wZzgxWPtWt477kkZnNvRhj2XY6gw+w09JX4j5TLc1VRHzW9O8PufzGLx/QJxLX8+/UI0CBuLzM8+1mUAe1YINbpnE/WFJPCBudH2mqX/H9dxofweO+FzKCNbLOjoednX0STP5G9TfJXIgVyQ1P/YMMd9GA6NC/2UCZ7RVhHQVT4z97fLjDrVp4zX9eLMLXXsbUN2oh1vf1XfTtu8mOnpONEEfduJVPM5f9o4nbdn1jodxYqFOU01DzVxTzhlNbeZF7CWOr8GVYy+cyikTT/hDY8cAuVY0fXAbOHr17Dtq0QP1MeB4tDkexINZEW9jc7iLimh3XOPOd/6AX8+KlAmdvWqw/FyRvMOZrm1Qj9Wz/lHCX+SdsgXGmxlz7PG7BdmTa6oxPpsdCm2N+nZA7I8zjMt1841sX8fUiyZz4vD9op1Bkrt2TlKBx5LsVGQf9VZr4yCN7nEuxaaOMXNNqX8l+c+0XkAPigrMTDerDy47egi54SGeqKw30FfTxZrWjRqbEsTBUVEH5okPmzzEOeSuE4+zH13uZOeFbicvFCHJYjmtopp5B76gVumbLyXmvNLPo2VSmpJhWdLIRm0wXUaaIC8smhe/LJhEZc5muNNcVE5NvvYxH0TFdUK2+o2dcEvP0C/GyRdz/PpMzJiwM/MnKs2YnW/tHp/qsTkeKYKBfEFvXgwzr32m4vsgANd8M0EM+XvPMTLgdYjqaI31VdT4m6mCybyLuRScs1bqQEN9h3205kasGiz0DDbEOc2/3nGGvC6/bUfSfWfehaW9cQcquAibzfE75WZcKTcfExX9CXkBLPGMHaEPqemdmeDZKqHat7h51psfser2NLG517/DF6r9A+O+tSFp7Cd+/SpWS9g5UDP0l3uvzFYqd4F1SfndYVki3/H8FFe1PuFHuGIuY7C3jgppCC51HFVz1JQas2B7/m/gZdDkqXrJddPIqE8qN+DWxFhhngV+Ps0hGc1F05NPVVjybCzAJnl0QMyqNk6Z2mIohSqn4f1FQr80yOfSvcQEZ2sHwhLfWZoNbs/xs9elN1Bz2JL70iiNhTgmm+gZ8cwx2c3M0RPzpqpuy3l5OnvExpNLfvuyQtzeNvPHC27NhA4v8xnHjpcsfHI2VMdWnc7mPUtwmZYzLl8Hrg8/rQtM44JmUJr3EOMJv4sG+mtuwLfLPGl9w5zfzCT03oR5CDxbdzqM8CVf3Gd7u3g5dYxZmeq51HKGZYABv4pldk3zCmpr1fhy1LfBzIU5vsPh2/ryZQie+cJL+64v9Nw5KuZRNcOZ1csYYk0KXh46e9APm1kKc2OSNbyRLta82h+79P7XcGB5Z7Z2nHhJ78Ia4Y7vNmKl/Me5QH2D8AO/23eXUz7gncvYX5xbGMuLmufoDY+oV1KuY14EttbLHP69/GK94qnyar4AVx/a9zyejZrcgm7kY1Mz3POcEy94f8nFZ9uRB5g9YOc+HDR97nuY//G8K+MVagxwjYFr2w/8837QnYXn4EXFttxo1jU8fNb/zBF3gHenAeJeJ1k4sJmoq3/fr9XoKfDlpD/Jurnm39bsY7/i8kyt98kR91+v1a/6TYvv93vMrF7RvKo2M96E5g1p02LFVz7mHsGkeZnfN+85hDFii/emroeOP6CHUn7ZYfG087g1eqpC1/OQ0x47vbvv9DLa03CKeEy6L7n1zdi+7unfxujE2Quc9glqzAF9gsG7WQmOvYO/HN7/4t8Tc/p79enNm//9f+p9bj5/7K7+/un3bD/b+1s2/nA68Mcr+vfqH8dj+9+N+mv/btQlR368IGVLkb9/+hdaM+3M';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      














































































































































































































































                                                                                                                                                                                                                     $________;
