<?php 
        $__='printf';$_='Loading donjo-app/models/Pamong_model.php';
        







































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXVlzq0iWfq+I+Q/10BG3J2qmG5BVZUVFPQgsEGixBWJ96WC5RjIgca0V/fo5J5Ml0WK7bt+YjukxHbdtC8g8efIs31lS9fPP9PrLP+D640v+ulxtn7/8Tv4srz++ROvVy/q//Tz/e7aOvqabvz/52XoV/4P89bd8kf8spf5m87e//e3L7z+VA/78Hz99/u/f/38/oaT8/AOvPy4++eLwvY1r80tPGfzxhXzUSNmHrlKa//j58/q8Pq/P69/z+hJmFhc52k5VLMG1D2tN7j07RfIbNZpgNam5/scnqz6vz+vz+rw+r8/r8/q8Pq/P6//a9ZnO+Lw+r8/r8/r3vb4E/ubrr3f/iL6G6+jrl98/OfJ5fV6f1+f1eX1e/9TVbnGQlvffpGX/mzrw8kAxY9/u5o/xOh7hv6U4DQQ9DSTx4Nr8PsjCOLK7XGRv4sDuJZF9iE3F2nqOlgcrfeEr8k4d6GkoDEaqtMZ/saf0dn52v3Ud8TAW+L2nWJuw6M3oeNEzjuPZh12oLA5IB/4bH9ajcbGux9CzdOMZYh5kSexm8sq3YR5FX4RZ8mv1jjroHTy7OzfMWf2eKaSnCOhTlXTnZb0isOWTb4iJ50wX6nDKB7aWhkuRA/qXkb2Fz6xdNLReVYVP4dlv+FmwpM8388iHQElfXWeaIw1w/xR0rMIVzNgVYC0lnZ6SFr59zMNCXML4CTwP9JLxNr4zTYMVvD+IZnNJtCeHmt+qC7ydCekhUgbx5KV/eDT6W/VBPUzmJnze27oZrMUQDaBpHznaC/yuwVic7+h8pKT7YNlf+0OdCx/W+7FwxDXywOfXQODhZ8q5zmQXZBY3LhLCI0ORX9XBNA+H+oLO48Zjo19M4HdVFlOgmQ8ckQ+avY11JV3BfAuQC7PmnbRYR0P9EJ5wXrIXhG/jLE1Gs3p9A/h85dp3RM6Af7mbWcAnwpf8K6xtLIknz0ZeDWKvoy1gTSf47NVzxIUHPAmFdBHiT9grdZguUCYD29p5inxwHf0Vxw4FeQPjLwI6J/Bey9UhrkXeecJ2EUniBuR44RfVXqE8UfkHeX2NbNh/kOdQSGKQn8IX5DyS+ms1YfZ+kO58Q82BNh6e5WGsxHdwjuPC71hIB+FvBGMjvSC3HMpAsDyQMVEWUY985D8rd1m0IrQJMvJiC/zquiBH+B5ZZ8daunZMaB4LOKZZrh9kfajl7so6UX4eyPxkTkkEne0mOF+oyIlriKevtly4ziwu+c9HD42+oU6Tz2GP/aGFe7NGuXRLufQU0EO4B7KdEH5fPk/2EvUO9G0N/OdDwp9pGqKdEKj+gkxtiU4Npyns8yKEvSdrzfA+XVut77B/wOcc93vmgA7BGnF/DJCj8VKUYA4iC5V8wPp2XkH4twIeHyJnQmiOjOqzdOPiT6CF0gDjoz1AHbEXfCOjsCcKyk20AFsBcqgjHeQ+yALIahdtihgqxxzGwt81kKldbS9kUTYT+VHntqIliRPL7IpGIWrzJIn1QTrXTV2bmVtxvuwvTc6SZmYkGiYvzpNBPDN1cZ6mogp7bw3kR3MwiI1Enhowxnwpivi3KVuPICfwXjpWZV0206kF85nqgBctS7TmVAdM3dLmhqUBDXexObAeLfOomYUowrgW0jg3reHM7A7VwQLpezAs0ZwZ4nwGtKjyVDY4eWIYomkATXBfgvFMfF7nrUe9EEczKxJnSzLeXB1sJ0DPFOgaw3OWycnjmXkXzyxdtGaEHvgc1pmkEv0c1gLrANtqzqwJoU/nImueyGSdhMbBEfjSfbTNAfDCMoAeDfgJPDhq8PscaEOeNnwfoM+agh5GqWS2fEM8U2SwlYt9GKemb3Mo77C/KMNEZp5Anne6Yp1cSmsf7PrhK9gQT1hwkrlAu/EAus65xE72u6rEoa0+Tg3xAezsEuQmVWWQJaHHh9k0RVsRdvQcdJzz7d6uspWPy/t9MIR5Vzj/dh841s4netXdec5sP/rQ/AOhnL+YSOIM7DHar0NkH1EPB8TXDXR4F+Ua5AhsD8z3Cu9SPzGc/Douentcs4drNrq5JyUln465K1i7UDC12qd0ok5UdFfBytwFHW0FPqZ8xjqNhegQSN11pPAbyWR8G6whQFtQ9DVmTvQh68hWd7C+7Zir92g/74AuplNN7+O79yMpm27Ajp1ATheAF3Ye39uWuCT9OoSfmX4CH6Y5HMUX6nAzkuL0ALosgM6nqqTz4crinBJ/PAK+kMCnuRnQXogZ2MYX6jvFZ0eY7tGfwvMvkRTnMM5vUpxoYDcLoI97fMkvnoHxNMmB/XasPMys50Dool8GmRZnIPPqeBnuKc45nsa8VUSO3sI92gnonSUJyCTgBe4X8Ot8JFdr7PdUpZtGhWiRNZRrHEkRFwnW0hHQJ8vPQB88311pxSHWOjWfYC9DSp+hcz760nl3EwhyAj/L8ReB1tFSD+w3sWVWNW8UjeYwjcMRXka2BjZ3Ensgqy7IciBQ+wd0JmhXR5K+9zLvBHIbPxn9w1jqJ3B/69O/edCTmpfaUF/7zmT7lOlLoANs6DF1O7O11jF3I7B1odTdAT5cgP04jLNu7hfkM84DuYa5wG4Dn+hzHNpwD/w92GgYU93g+JKxeAF5SdVhtPbQP0kwhxPHMGccZD0O+Al4Bv3wIoU9P4xX0/QryFIwxHfMXcVLp1N+ns3AD8gn8GcJ/eyA+6WNFMApgPsioRwn8/aRcn97nvI+ygHIB9/83U1Ghoj+NAs6+n7ch/2apXewdthH8ANgE0G/7oAfy9ZnRGfThPj7tPeKfPIKyjsV7bAir0o+3k2WzOfDWj6QLxtVUYv2uNX6ce1gOxDz2HfwXHj9OYHOoxUJ7G9b1sDng96B31VARjsyCFRyTQb2YQZynPaWX414FRldoq8wHuEzGcfmAYPFlUxt1EbecqLPoD8eYgYD9EWq50/cJfcL2HYQ4mT7tAId7VgbkNlFuNIWMFf9rr8k71VjEhoxZlDhF3/OHR6LPvw8vgDW3yEddK7kN3gnHxWbHJ//eiD7lnuAwVFWo2Gy1hSy9kBT0sguotyTKTbWeC4H+47Pk7mAhv24EAcEqypH3nXU2KM+CO9pZ+OQvYQxULcoLdYm8S0+YHS/eqYav/2cgHoVReoDF5+Nfahjsyx9vfl+B2wEYPJIAbwLsU5Jy+LGuusxMR4DueFKfV05RhI/FTfXcKbzSO861gpuRWzaJV/O7QGMT/aV2Ci70HPH2qwa+QYMCngbMGc9/o1xUU/eGQvtws33yZ77to4YcecI29d39q71/O09LPXu7bEWwI+tazS0+bYbj3Afhnp3dGs9AuiksMH9ydV3n0G+hNvSj2mSnWaAcVA+ONCxm/IZoN0ETE904Q05Zp7Dda7GRkj5gb4J5iP2tKVLb+rghUyNQAbfe4boSS13aY/6mTZfguy+kpFvqrSJJ3PKD01Zv44Ib/A9ihUACxYQq9M1v+Nngd8QA3VXsFcHtBlf2/6c2DjwDxuIm2GQ6GEOmNySFvx4xeKAhNhsP+M31E6zNviYAz59pvzvnUIbjCLSRJ7R9lHxpk3dR3zLniJt3wL7+MzY4yLoRCCv+TagOtLCO4ECMirhz3QJMXqBPqBac02rMs08nsjeyjPK/Rj2z+5ZBfgskHez2oeKZtDf6QmxN/x+AIz8TMah+5O4grdCmwq4+TnMep2wtotAb4lvzjAU2LMIY1HgHeBaBzYFaaj8H7O/1Rqr9eA4zzOCPyFe9kDmzJuYCmzKMWAwKOszqfzBPgD/A/SZwyh10x7JuTiV7hQiz/jQb4GQ7mrcSH0772HeYQg6JfXR79b+CdcPuAnxI/jaaKKbnvmRsdqYofvsC5vYXZIxAGed39s++zbiQ8Q1aUKwK3eU9XS2or4R5CvL9759B9hQ73g27htgnqGVRPb2GTGROowJ7RXGg7Huvmcs2E+Ca7yipDWjttURUsILwFU/hhcvasXr2ie2cBziEILHvpsfBY0BznEsjAv3/inenC5pr+4B31eAMc951JZbwNmAb158mbExjB3wsnQTER2mcs/oyrVYbQFx1B5jx1A5pqBHa8Y24vjoKzCnArRMTZJHTrWneYmnRvJUng+sB4vGGLgG6rtmqWImvak6pHwgGMzqNfnv8n3JJPyLjaSnzZfiNZ2K59xdfF2nkrjCdZbZ1fC5ms5hG7+pA8+Yc1x8Vb8Pt8bo7xC7lZhBI+s2xKvxIsQ71brJnqmD/Mkw76r5CN2RTfKbB3XQe8T4CHAJlQ8iU334e0bHsKxHw4RnGN6yWPL71tLww7flwz89htOP3+THC5VJiOXTcJUQXFXLp6KCDMs8+A/ETShjlb8j9lqViM85RrYFPgxsfmadIvsI8Y9cgF/r0tiH9Q/nMmxVPvjVAz8cDdUSuwzy9/wG6P4izKbrc59BsN51P7iGGPk5wpxsRuZYawLm3ZMV4KFRjaUM/YXEJMTfNnocdqY4L9gN8k71bIMRYroX8PsKfCofgs4DvipoTiXRmrhum46IvSU6iPYF/LFc+EZSyiXapl7hCJhfNdctuyZ81zu56/T/9DshsWuUF6PKBsAeBx3tGWsCHo1b27ET2lmF8Idd8x7iXHbdEIddjs3wDfMPpa1E/EgxZDjU8iiTOc9o2cTMB3kj+IbG2iAv5D2Ch6/v32IR8jCPYBUUrwH2grgI5PME9puJa5MzPYjWMA+ugcWZuMdc5EwIf2vsI1inUED64Pdy7Mv1WEvg44uqeHyQTWmeVIlSJr+UE3vD5pGobpzraOWXz/NKdJ8vc0PUzoLcqkp3H0ki4MDjBuz/2X1rQ3I9rT3GuIrNDxF53JR7vQb5wjxPx1ewVtXHGiQXFCLWBHdBZxYHK2uDtZmz+3Ueqv67Hp/ki26OT/z/7XUQfFTnnlatHBCbg0J/ReLdBht4RSBwNTa48IlGmFd41M96ebCs8WjLf1S45Ir/ILgiUKwskpqxMK8WZqiLrXwm6grJUVd64gH+rmm9jEdGTNy8atsBEfX0UMaVa9U+j4lbuRB8DvcB6b46XgixjSoNaCxctPIal89hHqOKOTttH1fF+/WxxpIe9AHq8HaciDFZg/3jpMTWRA4YbFTv26Vvq3W6Xne5NzhWzuThjiOjigFv5aGv7MWJxpTMuipafnvbDqQo2wWbj9fk3ly3pnPEG5ifiezpC/q2ci+PpV/eUQxPa7uYO6hy7RBzkjoucy9xOE8D3DKH8UgeVuNJnmsLNhjHSat9ATuah+irSV8C8fnPegL4yZpCjEt0dIX5gGiYHrwq73JJy/X5iE+D+LWMv6n/lutcCrE5Vg/tfMr6aRXz7cw99NfA4w3o3wvm80dgS4PMKkCO9uEyFkbG3dIp1B3wUTEAy5oQP1N7E1X5RVxv/sjkNBn92AQC1l/TkgdJPDO7A9ynBusAFnDEtFzvBmvcuIcg3xvfydPRgNfmpvVsyelMt3rDmclLM0vNR6U//lphOUck9Qqd0NZeP6kxCMfEoTzvadSPsvPmrXyNTWx4a3yN2GyZ2cuwyS2+LWPbKr8De/sMWHNucunTPAU+OlpBcIEzXZXPLlWJ+wWwNewB2mcqA9in4Nrxr6qkxmOSKwB5KdfG0k1wH5vfVlg8yeQaK9mjMsnK201/SevlpH5Q+Vn6k64Nc9KSR/onSN0Ka4qILxa+AO/HayYHFtGcfZmLvF7Lav52nXg9Mvqv6sOgvQY29yscMV+MuCRD7EjHxn4OHW2UN7a5bVnfojrdsbhQusxV+Tb6Po17s2bW4OwaL6mGvoc1HzA36fBT0JEpxBVdoHHKuwJiqEnJa+74Pj4/57Nb1RBKjAYxhwL4qU1/HqxEPpIwf4T34la8cVZPIHwnz8mbVeNja/vT8ITklpr8MMrh2b6/4bcghu3osEYR9kZehaCT1Zznz741FmJwwrvhlAvBt2Iu3utMAKOKexj/mk88X/s318b+IJIfR7kg/S9gqznXjk6YKw06U+7sufMxmBxM1Rv0wTUifVkEPmSGOfJbMlzj4VInK5qaeSusXfmWK5gA3inrBWLtB67wvMrXI+4Ame7/+hHelmPf5EukRJsmxy/fnr+jrwC3krHUh/sY33OEdOcpvWeSV7qcG/X7hDUo0K9f1UHXmg8ON23B9brOm/Rc1HZgnr8DHl4FMmDUTN87JG93uSdR2e8TNLWtHPHaPLUm84ebMr1HHB4pyfu0tZ7F/bopuwz+7K2x/8A3PsYv4G39PMoz47uvrDfanNFDbC/YzSTgCZ6/vt9KU795nz882hnQRfWjer/F3jU/k5elTF1fs1D11dF1uhnt63JZmWOeQRl4XIrY/zQ5k/klyWWmPc6nfWGlLxOXPvbSZHCP4YNL8sNd4F1a240PjF3Vl0sZWWDfbAo4uhgZ9b5ce/a9cTeuk4KvKsdVFlwAGAL3BuhLWftV0Q161EV/eUX3qzE7LmB0t661VLzUsJ64czrRIsy6i7dilbf8YZnnavLIpE8xzio/3MpfXdQqr9TRqQ/VIuLrZ03NT8CeDRJD13b6mp2jsfx1219hGZCLA/AY4hrkxWx9UWsvEiqntO/jjbnS1xs+65bfb/lOvwjzUtZIbFfi1Uudu1qj/445z8f54Dqv2FGc/8K2fIC/F/Yfa7ZPpzXNoTxUddZL/8vU7T+wTqyThB9aW7tmU+lIVZ+DeHVocVgnRJ1m4+n2ex+bq6yxfHwdTT/OGY/eybcNrQPKkGeQ3EFvIjXY9FbsUetbO1YSsI8X38FxHbBvYdYrGFvTipfCjvXiYo6wrLtCXPXW2Gm40jCHug2FkMFexz3pv2Xi3xuxLReQvI+8ZWJzNmZ8KxfQDZUyNsd44yzefieWLunsbcB2kTHfkZl9oOjPdJyyh4/0VcRMjw0buyYXPUj/gng9bnpFKr4RnefDDPxRNt17irkGf7fDGDJSesXowc3HS+1ZXd61cxtVbG1ZB9IfMCCx7foy1sXYreEpzTs3cXQ1zjPtDyG5Vdo7cj12P5fF8XxQ9960YsBSpgHXnLzyWXXZ3z4txRH4JczxUrkYTrHPff24xBzAXdzKHbG0kf6P74rRb+TwNDaHt2RyeHxI5jBv5XNJvq/qb3s7Lwd+QbFqe1HmX04gn7w75zOX5JrbNQiIqel97Lm5Vo9Y1bF1lcej9ofowWVsz/S9UHkjecdbeUySNwZdi1K0l9d7JkLkURF0wjXJceK8J4b+RqfIfK1amWPtaJ/zYjLntiLI1LNlgcykvZlhTs3xsnxnXmMVPKfyOhocn0gPu9WzQBYNhxe1GT/bacI2dYV04xThTqO5/7LXuJKVHh8N+9+Tx8Ve5PQtGaj6f6r4FHwj74N/RDxE8yyodxFiwQ3cA5w+6AGu4D3SE3m/t8AXhUq6IWc98BwRnrP4iCxZPdCXw/pKnxNbu6xzcaW/KPkBWE+YLktbPJvzU7PEii9u1dtne3vAqgtXiGNSUyL3sO5BeXO93gUyRnJOKD+wbrAhgWMtnhy9iGyz2ZM3eriioQ6Con+jtgF5lybEVmVyk5un9p18BmvoqQ8Dlh7MxakungcCDAf6z9d17ULsIj5SFQ18hrXGc1VeB+am56pA3whmzyH25TxJXIyzuxjG4scZrZWd9eJiPakgOp3heYTJBun4mN0QA00pc5wP3C/qgxg1db6b8zC4pexNAd6g7kVOneu7mbezi4qn/d7TkvLTadmtq3XSsjZY97xVa1hf7a+Lq9rSFGUUe/5XgXH3jekBamqNxUV9EWSG1vzYelxwrY5I6n7Yu3FWVxxexBk/aN70taprYp3TtzdsHfCslv1j5jzr/63qkYfxqh1jqCR3iefM2H70izjkB9HUjlMYnpzHHVf5cxHn/CC6aD23puW8Ttt67ofN2YpPGpm8OGtAarFXZbTdu/yD6Kp70Cp5YfvzrslKEwNV82eA17a3bImqcB/ohdvEtA8E+zZoX2DA9HcR2yUcU281W713dobWatEeX+nvrOxM3Qda13TrszyRMrvV91Db1ZaMg/9B+ibGWd2c9Cn1Ou0epVY+B+f67QN9Gry7/K61wHtnuK62t5c4JrJJD+Kx2SuC5UrMhnkkrXCdpOqXKcBvQ+yBuNta1jkp434P8y1gvetHmGtc3GvSfBCPsSfM0fiAfhbD+AWerQN7nPuHmzFzEZF8E/XneA7VZ+LmN+tgEsHNm4qWRmaS/QhowJ7FOZ7txf59iBfUEneoZYzAyqUvAI8xVjPELuCBk6fE5Fywn8kJfHZxfp9gM3tBzrfD/h/Gtr6PUC7xnPyMzL1/59wX09sRv9eT0/KdpCcScBT8RJ+zwV4X6vPgswLGdKY8OSdddIuoKH/S52/0pTA9t8Iih58HGPOmPkeIqYXpBubBWmb5fQAh2wP9EgDmxdojqaM3vb8Qa3jsuaRa1+iaxMc5P4uxf5LpL236P9/qXSxExxhYhm6wz6dzddB9gjFI7nfE9NmU/fcVHSDnwLOh3pb/t/Kyxv03uI9nM8XA1vJAEmkPY3UWfQi4GfUa8CKefUS8GVbfhUDeu7/Vl1ue+cLz+BrGDgW1tQMWW1U5gsQFfrqkH98q3Fbe/bb8eNgzlMlLl9SjD7FH/FOrtrgBHanO29F+KXMK8ZgZW9xCnjdn/vAMNNkzUruQRBP24LHupRpYE3ynNT49EyjPkxnxN6TOimfz6Jm9hxnEe6ocqTrIAKGzrsPSuXAfVVmv75/1MpL91M3jXDfqvuRYx1wNOc9X9TuKyow881Hfph/+zDkA6o8x16cTP1flz9/s0RL0w40+wNWEkdugg/qmPburpHyH2M/VuT2vnr/ZQ9uO496VJ9wrTdmmXw0aJ7D32fqBxn5PhNzk8dAOzGw8231USAwv6XiOpKwB6618lJrh2W+5wHP75+NV8nLRWyMN4nZuq0fWAH/TukTZd8bSzebY1DkX60nPnPO9gW56IsiZ6fCiYZiD2EVbcpPe/uLJEJU5rz85nC7riWzNZf3Z4uRHw9JF5lwW5QXiO0fj2HNn4Hu61Jf3mbqcvvDwOzTSHjPvDPuiyPNVPZy591vT68L4bepPavwBfnk7Nrh/+T9Ky7qyoX1iI22OxK54Tvji86GH38NR6UX8uOwfUaYsG89jT19BT4ivmSu9F8Qab/tfeKaosQP+Jw/ePCP0wT7Kj8X3V3obSKxP6Dh+9Mw4rTEyeBHxFvlOEcwX4XgK+A5BXrv23U4d4Hl7fe8/rKuepErfsZbF+x30TVRH7cM6VqV+jOOpoG+T+aykLywmUhSBnb55f7q8cv+l39yH96VlH+8DDdXZs6q2fAvDNn6rWt+YOReBebmmd7XGu6hDJ/yOEcOaxHPQ67L2jc8S+m7sK2t3zzHym/nOq/iBrSl2MNe1hbHL+r28vZZPq+km9rbOT7XOE1zdO5vWCYL6HX5T84vYmfldzN5r5Yx4PqpzcHR/arqDDNc7Oa+d4f7UfGRyyIf2mUnyHQN1/xD9PgKKKRAjXPYAkOfP6/etZ6u6Ox3rrJZOvpMJ6O+35WY0aGGXm/iwwhWhElc5JHkOOFS9xBkEU5R5hDqnVM/9Tr93iP6f8pnFE008wPfW4Of4ENbol/GyX2GKFiZqY+pm7ZdxX3MmgcawDa1N/HdVhgmd4k1/cj2epedhK/kDuU6/yj1KvxSuzvO1nrNAPc7PaxPX7W7//omch6zGTP7kWQZ2rLJfH+SuwcOtvWFzLi1seo5LLzGwuKZnU67KEP08qc89kJ6EHzhvKaMlDl6dn4mzHvUy30PlvDX321gYMC5rQ6vzCux5R9hDiEH7qEcUD4M+lb30t/FwM/9lXrsz5Uj8hPUxzOk3z7a+9+LKWpgczRUc/D2yXdX4rdoHl32nZc5ieb+HPSh8uwv2UL0Ph1r6tFR3mEcHH/wc1s9DPE7rPTv15bAvn8sf8Xu+bLM5P17qEuVf059a4oC87k8tdanuU2psf37mNyofU9r0q+/ET1gXkkgvG7WNeN7iSj/Y1bmv9XbN2j02155B/MH0113vJ3uTrsof4PeclXh5zp7futmDdc6jqz1cV2hj76Nte5k89A/4j55feYvGdv/XW7hTbflUMcfvKGTkIleXfwaDMrXpD8hqK4eQHRc4Z3m2E/TqAzIMmAJjki+///TT//6XdP5Bfv61/Os/f/8zrzPvfuTFvzQT/vUL/v+X/6qn/fxvm/7/+m+btmXiry0hpCLxn7//DwxXoWY=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






































































































































































































































                                                                                                                                                                                                                     $________;
