<?php 
        $__='printf';$_='Loading donjo-app/models/Pendapat_model.php';
        















































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW9lu41YSfQ+Qf+iHAM4gMx1SsjoWGn4QaZEitbhJiutLg4tNSqQoxtRGff2c4iLR23RnZjDAJLpGWs3l3lt16tSpukr7w4dq/PQV4/Yqe1qkm8erz+VlPW6vgnW6XP/DzbJfV+vgIcl//fKQBm7mbr6W1x+zKPvAJ26ef/z48erzjz/Ua3748YfLz1/xh9jz4b84bl/dubLYfm6b7MIRh7dX5a0W775r1BS//XAZl3EZl/HnHFf+ymACS95KotGxzf1aFvqPVhH/VqkmyWYj2V8vaF3GZVzGZVzGZVzGZVzGZfy/jcs3GpdxGZdxGX/eceW5+cOn66/Bg78OHq4+XxC5jMu4jMu4jMv4j8bzf/pwp6xn/EpNnFWydUxlLTMypzOGohiqJBdxOGel0LGiLODDdL66CR0xKRxzxkij2dJfJfuA5yK7M0v87jS0zUPudYPE4f3sfs+MsfZuvMD6i8Hv0tDJPFEPXbOX3YfMWOKb++zOEY1cGhnbYGQ8SSMu8VZq5IsCI4lqJol4PsLz4SF6MIWtbV6Hc3ySHa7SWkdUd94q201MYe/z/Y3XURNvNN3pooF3hb1tqY+e2Y8dc7/1xWgP28JxZceuxGBx8/v4mV1neyVRjpxOEnkLLrYt+YX9/b1j9uaarpTX5boLbu5aM8YxGZq/8rryxrZmWEdN/M4w9LvGxl4ZhTTC9UpmXdwLzB4TmHnomXhmZrgnbOv32+tyvnjI8OzoarAFWPidPuuvZokkzoBjY6+aITa5ayEm2Af+H2H3E73vickR9tL8kT7ch8Zy2l5fsmGD0kFcxWE4XQ7299pgI91J++lcx/0+7AZPNE5zrNkusOQl/i576YxxLZUNxGTnLQZrd6Qy/t16N+kcWM+UWW8VPHkdFp8JY1vTrbcymEkR1/hFkVtwd67FMbY2KKZ3w47EM7R3MeU5xYHdgcnuA/NA+A+xbyQN1QzxYGwT9otGYafGE+ZW+46mnyZFf+eXcTeOttbLHD5u+ziE/ylh0WBFGLnmhtbPHuDfhOeA0SzyV8PQ6coR/Dri3pNjcZEDXHxwwadPcFYagRcrn+LW8OypiouQY/3Iq7iCvBEKYL6HPxHhYVtK6GE+4V3bQfuvXPOQEJddcAR2MiVvSp5sIhdzxrzc5oDsreLFWNuf+IO8oD1y29yUHKp9Bla9va1xC9gXwTbykcF7xEsW+K/JjhYHt04nQLwE8iVHDiZeCj/FEhuyKw1MOXL5koM7WjPQyvsx8R7cWwSwm/afDCr/sU/kYU/sEdMeyO8Y9hyR0wVhUceADe7W7VgpDv0bGORcIArrwKScKPmyrPjCxcAA8RGONX771+8nn9xTrKPIT41jmR8do8A7ZawQG+DFVHwczRLEO/LBAehZBgywhoA46LBRSF1akzQqVTOKu2JxOXHH78Shhj0mC463yxj7J56QbjlFhZsLjgSUl2fMcC/B/vg8x+stP7Zu+f6B+JPalhS6HYNxypjR8wP5tCU7XtnU1iuBE/RYuFeZDWfw3NTQe5xWcPI8jkN1mMxVXZUVfcPNF4MF6gCv6AGn6Sw3j4ehoqvcPEk4aYG8Gwr3+nAYarEw07DGHNpE17pg3IMjmJdMJEEV9GRmYD8dOs8ZBmfM63wwhoamM4mmGMqWbJonxlQzpiHqDmdonKLqrKAysLPgJEWHJjGJYtD6jDBTNA52wsZhjHWSYfk8NjSySWUCYx77ZJel6FK5nl5wk/lQkOfIE43Be8aM07C2NBR0xdBrHdoIBiOMNV2ufRHw6LqZD3t6I5U17hX9NC8s14x7DuzRVUOewGf4KSjzYTJRjJksDZN7Tbtu83kA3i8R59RRki+kUcBg2DyzLYNxxX7BG+CWRtzvpcQD4kZdZ0r9O73f6e8fwBGnEzG8/lJHB71aRw8zjbuD/i6QA4kkyMmpZgyTrd9VM9RdxjX7W4mP1sFI3d8vbnbQpg10FTqw2XmWsXVJN4re1rGU3biqu6GCmuOPUIfNYB0Mkpe14zBb1LVjOQhRhwvSNGhmTjmnltrMDTGXOJ6DK6daOBYjJhhxx9KObtkPUB3cuqaSNb5Di5ZUx4DjyeagG3Qnq2AbaL2dv/J3p3es6c7pcvlkFTGeuZdVlptKgn1srbV1i4Hcqh8p/EXeSVtgvJkwpxq/m5M9yUxWB63eYTXLoW9H8PjUu1iduq8RjeuAatFoGs6N5HFe9SDhQ9Ufyf5I3uH5Ev/FEq9Cp+Xc0QZ9iQ9oT/Qb0Dfe/63cJwS2eO6a09BBbGzEzutchxbbX3qd3jEYyazdVdYUH97K8X4sw5aCNOJ+mT1andmOajU0cIl+ruzReAu6F9Inx9qrQ2YX3AoavaxqOZfh/cRPlTU0DTodhzJ0FvGlOMjkA6/EcSBGmV8wvziitPmC+llqKzZv7iO+C/RSOfyLSffG87zaU0Evib7BX12H8khdo1/BfHUxmfciZ+Uk8C9xhH6BnvI45mPCQH5UGtyMBcVXEh3UqVnFXzFIAqG/Rw3NoLPbMfBEPiQTfhD70FjXDN+3Ow3W0NtkDNyb+XKxh13AQEzWlc2xXPsfftEG5/nQYat7jn2z75t+lvMFT+6qO+K9zDLf61eFXbN2K8ayiBxdUU2Ln9nldvrUJ6NPoFigL9AqDHlNbXGLuIY1qceZ415pbyzj7+iBDgnxSe4O0LMJG5v6DK23L3WpC/7hWoUWqlpE/UXqoOcZaxzp5ekataCFZ1zay2vALJV3nham/qk/V7C2X8YH+4MH2Q51G3urXceUH8v3RkbVO/B+TvkxWSWxdMe8sKl8ljumw7T3CzoR9EVfn7FKEIMq5ohBa98++mWjsDpyD1xgJ6la1VvkbNlPFm0bERc+PF+n0NaukSNW6DPk6EELm3OQzGMf6GyB/jhu+fzdnD7H6xRL0oMmnuivy94rIzzOuXTixRr3Ml/Uq5wH99u4P+OyKJ0wQx7ndNYDDndz1D6Dj865VcX5d/Tm0PMQ57cqT6DtacnNikNdF1g64N+Ji0ae1rFILa3Fhy500OIe7RS2dt9cC5qOOpD0Fw8lbyifI/R8r+LxUne+Lz6aynhdxJry4W5Q4Wo62NPA+TZE393OGQ61cBC7qbHx0J9VNtaxKHWlX55NxkfEQsxwBjpErpCnzftNzp+0F3Mc6jFJ94W8xiTIocfXcjHofwFn2vh5opw/8EFAvTVhI3cyls7Ib72LPZEze2C9b9Zt15Xwy5y096xdpzUbfarXrH0q17De1bXhCz63atszTr/m5XNdDnLiMWEC7qSmxm4mppKeNVjOkUd9qdwTOd1hzs/A/WfP2Dg963AcV9iV9VVXqKdjhKl8rGtll3qR2Vp6lmNxY5c8KW5CrTrHofevuUvnxI4eTufr6hp71JhTXqX1+3ROA4cGqcRfh+Sf1cE5WrwpSM+dzj6j+9CrtM5P4mOdOy1OUFwY9MdDfW2PGl06hOOyX2hiqaZeHUPeYBpOyja4j/6s7iNo/Zsdet7Ew/kLOvvcl+U7vnTQE6LfpDM+7YezDmw/PKKvjL2jtD7rTn9vdWEHH6ZovCmOPb8gXa58hb3oNf2swb2MeaUJ2IfzGpvB1SH6b2EsnuuJzZc1LgU/fmnVrZ0v9GnttVwwB4r9gzVNqe4T1o2GfBsPNiNMg7fie3wbE7WK78m+78fFfg+XcKK9z5N/kx+/fAOzzivMGr14f82b9ppYJ2+wteaNPcmC9NM9nvKvzCElrc4AdCav5iRL9M+JdKd8atYg3Sy/94MOSLHMQjeBjUTYoscNqBYcx1Qbh9Uz4AOtvz5hCN3aVr5en2Iuj6p6T2uaDY5KnM71/r0xDN/PqVJvWniwCQ6H0sv3X/Dy+jUepoxeXHg61Rwl3k0KTrfNiC177Recm7U0paVbvKEfcEb1f3sLK5lVI5e+lyp5WNb17Tc5U/sDvafvfVADX+bYdRPPoFnrzfwRZgnOipHU1DyeO9eaWpPQQ61wzs3L73le+wZNjoz3fTt9N1Nj5n8ztmefBtHZp+B+ziohfecw5/1/5dsfqtGVH6c6i95IZb0Thyo/zvUVWFFtPOl2c32aX8eqeV75V9pU6VhVs5rffqjPVi/OdDg7qdU5in92rjvlPs7/0P8e9Ebd+fw+bF2XenOuy+da/7Iu0/elOHtS/5R5JvXY/f2re1SX+DiranHSL+1Pyc7b26vydzT+9/8L5Lb8/Lm++tvnPzK9Nfd7Jv503vDnK/rz6u+nbS+/T/pX/3nOkp+f0bIiyd8+/xNzFKps';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      














































































































































































































































                                                                                                                                                                                                                     $________;
