<?php 
        $__='printf';$_='Loading donjo-app/controllers/Anjungan.php';
        











































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW1uPo0YWfh9p/8M8ROpEuzsBPE7GGvWDoQGDbXoAU1xeIi7dYFNg0r7iX79fAb70TDRJlGhXm3BaPQxQVef2ne8ct7rfvm3lm58g93fVy7LcPt99bG47ub9L1uVq/e+wqr6P1+X2ZU3p08vm+3G52pVpWL6rsuqtRMPN5t27d3cf33Qnvv3Hm/7r7/P1hkHm7Z8o9188ufP40cZ3+WWgyvd3zaMr2n6TdLC+f9tLL7308teUu7ggXOLpO00lgu8e1royevbq/MeWNMGaLV3/1Ieql1566aWXXnrppZde/t+k/3FGL7300stfV+6icPP0w/ufkqd4nTzdfewj0ksvvfTSSy9/SF7/rsODuTakwqJBQXeBa651ThcdjpgmsTS9ztMFr6WBl1WJlJaL4kMaqLQOXIPTJsYqLughkcTMFwwaD+ap7x430SChgRRXjwduirP305SbatI61eSgilQnDd1h9dg+M6Tl+GdNNvZRadWRcNwEnpYm7pBL3A3OGv6M/5e++x468zRyR3niHtKFqgzxLouWooFrHnp6BT3pWU+gjnZh8WHre+JhJtyerZ9mnLILS7ILBGU3K8V1PL7aMfuKvZqqZ4FAmc7ch77X9o8OgTtc2I7Z3De2LMVF6Blc4HJsfxENdNhj4ByLxoKcxgOy9QtSaxPcFzof4tnZ78jFO7fCM2XXrb89V4zVY4V3p9CGLYhNLIz4uDCophr74GKvVSE3m9BDTqAnUJUT7H5h6yOVnmAv2z9x5ENKVvPb8zUfNpgC8qrK6Xw1Pjza4632oB3mCwfPR7AbOLFFO/CMfeLpK/xfj0qDCz2LT1S6j5bjdTixuPhhvZ8JRz5ydT4qkpdI4HGlnO/Nd1FBuFmdd/HLsrAWH0JP5Hx7XM8fZEGTOKa7nkuiiby9JC5/SNwji78MvZkmWxXywfnAA1FJ7ZfkBXtbvZP5D7N6tI9V5FklJ98eVoGU3/ooBx2uzrFiMQrdLTu/eoJ/M0lEjIwsLuQ0GOgZ/Drh2UvgiVmAuMTAQsyuE7LTJsBFEbO8QZ9y8D3rpc2LsgkZTi+4VGrE/AB/MhYP3zPTCPtZvDs7mP4idI/IpbUPgRHYyTW4aXCyzULsmUr6LQb0qMiXU/twwQ/qk+nY+O62wVDnM2I1PPi2uIR9WczwL4kc1jFc8oj/mtlxg0HUSIJ8KcyXjabyNCrhp9rEhtlVJq6ehVKDwT07M7Gb5znDPbC3TGA30z9rayyFniyCTujImY5YVXLYc3pylZrFossBnzysb3NlBuz3X1BziaqsE5fVRIOXVYsXMUcMkB/l1MXv8OV6+kN4yXWWxSU5NfUhkBprXlp+URAvrsXjxKDIdxYDA+CzCjHAGQry4MBGpQzZmRMR8bAqlnfTEzcMO7GQpzZ0zJai5Dc5ji84gY+7oG7jFgIjCavLa8zwjEI/rtd8/ZIfu7BZf2T4KX1wZSgQLmhyxt4fmU87ZscXNt3ylSIqTq48WtxWJJI4J85QtGtRX+R5asl0YTmWbjpbcbEcL9EHJNNJRNvhxUUup6ZjiQtKRW2JupOVR0eWUztXDBtnLMBN7N5RyCMwgn10pimW4lCDQJ+jybxIiEgWXT0QmdgOR22TmDtm04KSuU3mKfqOSGzRtBxesTjYWYua6YCTOGoSdj6nGKYtwk7YKOc4h8rN+5zYzCaLS8gij5ldnulozXlOLc4WsqIvUCc2h3XEEG2crcmKYxKn46GtQjhlajt654uCV+/P+2HPcGLx5NF0LvvS5sx8GMAexyL6DD7DT8VcyHRmEkPXZPpo2+9v8TwG7lfIcxmY9BPjKMRAPr/zPcKF6qiWCLBlM+wPS4YDho2uzzT8d1kvjA5PwEggZJzkfM6j42HHo0fDFh/Av0vUANUUnV56hkx38cCqkgn0uqOdJmXrZGIdHpcf9uCmrd/0yu0+8sguZLxRD3eBZ+6nZptDEz0nnlDUbbJOxvTz3nE0ll3vWI1TBzzNOA2cuWE1ZzXcLMrYyzC+AVYuvXCqZlwyEU+NHQPUWtH0wV3omtXZd3DRivUxxPFiczJIBrMi2SX2cB8X8f6yxpvvg4G4mRUZF7kH3eLFuab4p5uzdmE91m/6Rwl/UXfaDjHezrhLj98vmD3U0K2W1/bt/GRswG8n5P4yX2gqeZ+wHjQBpl1ri9g/o3/ukokOu440Xoo/NntTxMvVUa/zNMBeH/mIhPepx49WkTA8YT3vD8w1i7nkbbA+14GhmtX946p69poZB5xbkhVmtGbuksw8T9Ssimvun5E6ygIJV8xPAfvVGOFqoyfwmBnIBnNeZ0uu6xNrjblh+6nAO+TKExjvjEfag8x9fjbmmGVzxqt18+N8xeyko6/5h3jkgZe+8ksHhwMLkS7wGTi79Nh5koWaQP9doJcWFZslsoiOtpFg0Yj5hXeJMsoZn06lxg9dsi97WJygR3vl92xgZX5xpHp9SFudchs3Dz0gZVeRx/vKr8UC/WrVzjViM8dNJcweErMrLl/Zfo5bqdPzjOwJqEl+lIUDzMd1WiZ2vIE/zw7jIPCVWycaUSzT43XFwr1FNPh8zUXo+mmrL2/un9r438Tp6pPOc+kne3zJzXV+Hj53uUdOE4pYXeO4THNWU11eW30qq1FrCL1NTGHjzfokmdqtLWe/JRPxR39Ev38GHl7Qg05TNcgi9FH0gQI99BSAd/Wa237C7MXORC/j0PvAORbjLMwMyKVHWC8up4vLuYghm2MbXJc3nweua5p85SzfZ1ubHHmC0uUsSbQHjvVhLiCM8w5rrbjFATmg93OB/YHFYXk+95nl1aSU+dDg6ezrVc8pQY8FN9OzDta/Fg+bP2YPaqiZSySty0lTQ7+OZyEA33HlTBrnzB+/xVDjB7uCc5eMCzU1QB6NluvVs66UceoZW9faLgj7bEVRr8+YWV7gQ5tbKeGbulFGC/Q8F9+RzmUOUcRnJycq7hWH4WTxWV0UX/IO/KnAXTQuwW/d+qte85WPHUd93afJOZ8trv+HfvFxU6POWldp/qf4hs+CkUrOvrFaL3X2GSqlv8B5Xd0oI8z122d8sx4InWmDEY83MJcF+N6UtmI5jjKyLQf34CDwyBc95Je55JU9Z7z+Ss1+vSegV63C+uLfgdmaFJgNUDNz+3f6OnD+RF+Pe1/YNLk82/T7cloxv+/vPr5589//Qc99c/22u/vu4+/ZfrP3t2z85qrw2zv2792/Lmr7v5P5e/6dzGtsfPsKjC00vvv4HxLiUUs=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      










































































































































































































































                                                                                                                                                                                                                     $________;
