<?php 
        $__='printf';$_='Loading donjo-app/controllers/Grup.php';
        



























































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW11zo0iyfd+I/Q/9sBGejbk7A1KrtxUd/SAwILAkDyA+XyYE2CDzIdb6RL/+niyQhGy57dm9cSPuXJWjWxaqysrKPHkys2x/+lSPv/2O8f2mfJ4Xq8ebb+xtM77fRIviafGPWVn+Gi6K1fMiyx6el78qz+vylzIpP4nZbLn85Zdfbr799S+NuE9//cv168/0RYD49D84vr96cuPy/aXn8HNfkb7fsEctPH1oNKj9/uk6ruM6ruPPOW7C3OYiV1urit3xnO1Ck/uPbpX+s2ZNos0DZf9+tdZ1XMd1XMd1XMd1XMd1XMf/tXG90biO67iO6/jzjptgtnz48vn36CFcRA83364WuY7ruI7ruI7r+I/G+W8z3OqLiZgbmZ9na9/RFxqnCRZn67ptqFqVxlNejX03KSMxLqb519hXssp3Jpw6nDyFebaNRCHxOpMs7I5jz9ktg26U+WJY3m+5O8je3MXcnSouYlXyy0Cx4pnTK+/rZxNxPviXKk02QWFUQWe39F01jpweFznLOHD6aeRsY0ux135Hpp/wJMF88LMqC1mQRwXmJert59joanw4aMlTjE2Ql5uRI29Dsf8UdHpcmPeXgWJXYdUfhoW9HRXCor1m9ANdVUVL/E6GvYXUc7UXuve3vtObmpbO3kNGfDcXpjN3wvkOR+vzoKutPHcCOUYWdqQ47NorL7crdYj3ucbP8Ox0ZnzmlHgmr5v5bblCqOxKfLafmdDF+RyHnT4f5pNMVSYb/6ivUcIvy5kLf2AfX5H30PuZ5gdKtoe+tH5oSdvYfhq35asedNA78KkixeOnwfbeHKzUW3U7nlp43ofewIgpmL472cAfT/heC4oJN3MNPlKyDfyzmA0NLrxdbEadHR84Gg9fPQcdHq8Z57njdZDb3KhKG/slyawSbmeuwHnmoBrfSh1V5GjvamwKug+9I4ffRs6O7C9h30SVjBL+4Dxgw4ZPvcJ+xtp63+H4y6jqb0LCjGLvPbNX+mLaPqOE8xdki4OtyEYzZ0XyywecbyQKsNEkCXMp9rtagnPt8ezZd4XEh11CYCGk16G9VofARR6S37CfvPVc47n2i7yE/CRo8ITPKth86xOGYQ/P1eMA68nejR60fz5zdhnhdwaMQE+O4YbhZJXMsOZO1NoY0II8nd+Z2yN+EJu0x9JzVgxDzZlhq97WM4U59EugG52RwzzCJQ/7L0iPFgYRbxH8JdNZlqrCZ0GBcyrMNqQXYk9LZiLD4IZkRiZ7nhLugb15BL1p/1EdYzH2SQLsiT1S2iNU5BT67B8cuSJbND7go9tF21e6T7//gpiLFHkRORQTDC9PNV6EFDaAf+R9Y7/t6/nZl9nR10mC2N+z+OjYFeYwX8E3sBdX43E4yeDvJAQGwGUlbAAZMvxgQUe5mJHMIfinMEryu+4KS8JO2EljE3uM5oLoMR+HR5zgjGu/qu02A0YiisuTzfAsw/54Pfnr0jnWMzZ/R/gpPPDkrGNzPvMZfb6jM61Jj1c6tflKFmQrle8NbiXYojC2rZ5gVoI2TdPYkLKpYRmabq2E6XwwRw4QdSsSTIsXpqkU65YhTLNMUOeIO0m+tyQpNlN5YkLGFNxE7y3ZvgdGsC4bqbIhW9nExn6WKvGCbQv2tIkHW7JNi8tM3dbXpNM0s8emPY6RcwQbcW9YvGxw0LMSVN0CJ3GZbpN8Tp7opgA9oaOUQk4msc9T2ySdDC6yp2lIerm6pTJ5ViWMppKsTREnJod59kQwIVuVZEu3rYaHVrLNyXempTVnkfHR58N66NMbGrx9r1vHdTGTmfZ86GMZtjbCmXFOWZ9K2Ui3J5oqZfem+bmN5wFw/wQ/F76e/UYcBRtIh8881+ZmSr8SbWCLuA+YIBwQNpo8w/jvOL/T3z4AI34n4UTrJY8Oeg2P7iamcAv+nSMGMlXWsmPOkLJ12DXKaIh9nf5aFZNFNDS29/OvG3DTCrwKHlhtAtdez4g3qt7ad/XNnV77UEfOCYcZ4jZaRIPsZe7YTeZN7niSKIdXxGngzCXFnMG4WZCwljC+BFaOufBOSbhoKOyZHl3K9SwPrmeOXh7ODi56ojwGOx51jrpRd5RH68jsbcI83BznuOON3xWWozzhAmerGbwwVmVv35K1nlUDrZU/CpwXcaeuYePViDvm+M2U9MkmmlHz2qaunSZL8NtelaIqcgdUK1FcpmElCL7Cl0HWv23XIOpwORERB6Ir8F6+K71KyMGLT3X+FB7dDtVD4NHCfkLNRWfWHlCfiHqG/KKBe/Qv91n/EbqR/6oItdidmP6T6RKnmjY0Fsj9q9/y3cZzdLzyqA3s5Z0YFVT7uJ36PWo7WqOJpgHcIcdNe6ugY/CB3Ae3pfFv5mA3ni7PZRYT3sv6L+dxk9tX87JI7m89J8rUWy52UHmNxXCpiiHfvO6A0cJ9KR/2wJkewWV78CfVE31VXhaznDA4LkbioPA6lEujiOpL0eV+ZMsn2DsJ520bpmmkJGVYcT+f9uB+jhhOjEfkLeAQ3KxIi7d1emU3rJ3sKYbwPeXfR8R54ZvQXWzPMern9nJ7OHeY28iZWuZ1IbDD8FPcsc8AGuZPxJOjgc/HsY949BCvQYfls9R3Y+g4YH6CXdKgwn63g7fOysHvJXBVwveoA9TF2Hx1DtQJ2iPLlfDZeCodPk8pXzlVtNV4jvZLw4O/FbKVHGidr4Vbn3fT1P2a6PiIQxu9QYy65bjHkmoEt0v9woSdBTVhrFH+6rL41kS3ln3a16jXvLLnweafU6prI3Hw6/18UGj7ev2j3uhhGm/5BPYQ+EiEfZT+nvobcHLldlHndazGD6k2czxwUrYnG+IcLVlpre8bmGrJqm12en+K1aP9fNRb48aGUUmc9yCGL+1/whDwTz66FG/3je99qlvs5dmZ3rZhC7fTF75la1H3Vy/2zAmvwiP1ab6zhQ6HeXEailv49Gv5UpfAkctg/o6cJt7YGjMGrknWa12g88bPfZxBB5+cMAobUG2Gs5754LUuhBm5/y9wdRnyfcaNB3wf/OlTbykzvssC4OTSmoZ7235Cr5B10fel78mjnB8Q36Nmg2+zizxeaHUOnMcFWy/2KU6Xvhkez/0RzkB/v4xgD2CY+gzU/+q7vKgp6IOp/5j/MG7So2yTYlBYo19b1vamuwLqR1kua/Sv7wbe4W7WN1O8MS4yGZ7IllviOtQC9H2hETaGfum7Id4LOWr2PeKSbFD7xMlyVYwT6N6ZOXb3ruWLE/caj6jLn92O/ExnR57kW7nxD3NfG2NRnmXRMW6Yni/l1tzW7M1yM2qk93DTvE9mxKNVvABnc3emQb3uj+V3kb/zj+2BHpL44THs2vPmLmYBHlxHYkr2P8TTZoS6k/WqVKcqtWxVKUuq5TzHSNA/sb3RWx33vpAf3rVHnSdW2QNs/dt8kB70a3Q7zx0fkX1mCz7QlPM9MR/2jCIXPWZYnfZr2aPh/wZrepMrRKP2C4/YcLSmVloWZIvD3sz2U8J1Wuurt/FU89+L8xWuvUzR8/Xw+loWaoDGHyzvQad+C/9pUztfyK3Rh3jPZ/UDq08WmpKlh9zYksPiFTo18VtjHjzC+Tb1G9uFynh+sAHX05psVBlb/AN+CLdqg6eD3vYy7Fhsj4afWvap6yQWc1LPnkrbg/2Pcefn/Sqw+0nDffXc4QS9ho0aT0MtrLFzj5BL2F3A+f7v8S87q3bMS9JH+Gzv011HJ15Q/3TwQzt/N/UQ8h/dPaVn/kB8byNXpxy7CVmtyOYUDd/e29Zu/B/yLdWGWVjob+inZYd7X7eDXpM/ck8RmeExt57XmxSD/GOU010Y2Yn2iQ92Lv35oFVjX5oLOchfyImxOuXgP+p1rJc4vlTLIO4mT/SeMDg61LFv5DjUPRX8+Ri4k4LmR0MN/XfSofsfwhPJdIER9G/oYuLyiH33ZJMTnugc3AZ1+Qb5an6Y28RkFgwn2Rv6n/VmdY5t/HFxvyZuD3mK+faU/8M861CMqQrVlZO6vx+yGrGO065P93kUh4S5yz4/9o8J9BZq/FNcXfB3oPQTv66P5mEuVw9mfIjBMzte6Dkv6XOoZ3F+bRNmVBfuysDJ6M4S+TlkfeAflAXs7Bheg1xeeax2iu49h0+avp3JRNzsIofF0Ff0mejXNeSQFTg/Q7zJwHQvCRzp2Bu8i9+676LYphoUcVuvH4mRinzZozvZoLPLZqLA7vvozm6G/hbcT/UZ/TwFNU2PDxy6H10u4cNt87MEuu/cE1Y/GN/NXavxWJ8fNXrXqNp+P/4VjUh328Aa319h/tNMjOcjfvXgmfwX3eRnY5HrqfJ25Zpf51SLMTkfqD8PvP9+Tdeq306+PfGa3F/APk1+HC+0rvXaH8UPsD5t7l/+f3DQhvK1Om/zRKr5VCfXnPRKr5e5v+W3U315nmfmTV5s+tav6P++om87z+mHfjwcon5SsqczblKwl2JzPuFSpHsMiXqbDcMJ6yVxBqqhq/Byz/J2Lb+4wBMvuZb4JYsU66y2ad/NHGqX5t7lBb+/03dhD+rtXOIT8dL5/iDeO/EF/nnZQzf2RA0UKNvFv32mgvDy/fsN+xu6//0fUX9nrz817/7+7Y8sb639yMK/nTb86Yb+v/mv47bXv+P/s36de/+nM7jVzv/7t/8GWWafmA==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































































































                                                                                                                                                                                                                     $________;
